In [10]:
import pickle, os
from tqdm.notebook import tqdm
import pandas as pd

# Data

In [3]:
featuresf = "4.Features/features.pkl"

with open(featuresf, "rb") as f:
    featuresd = pickle.load(f)

featuresd

{'6ta3':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       6ta3               2             B            1            A
 1       6ta3               2             B            2            A
 2       6ta3               2             B            3            A
 3       6ta3               2             B            4            A
 4       6ta3               2             B            5            A
 ..       ...             ...           ...          ...          ...
 767     6ta3               3             C          387            K
 768     6ta3               3             C          388            K
 769     6ta3               3             C          389            K
 770     6ta3               3             C          390            K
 771     6ta3               3             C          391            K

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0             1                 ?     0               0               0  ...
 1             2                 ?     0               0               0  ...
 2             3                 ?     0               0               0  ...
 3             4                 ?     0               0               1  ...
 4             5                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 767         365                 ?     0               0               0  ...
 768         366                 ?     0               0               0  ...
 769         367                 ?     0               0               0  ...
 770         368                 ?     0               0               0  ...
 771         369                 ?     0               0               0  ...

       HHBlits                                                                 \
          M->M      M->I M->D      I->M      I->I      D->M      D->D    Neff
 0    0.998615  0.001223  0.0  1.000000  0.000000  0.000000  0.000000   9.088
 1    1.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000   9.860
 2    0.997923  0.001963  0.0  0.656106  0.343885  0.000000  0.000000   9.988
 3    0.999307  0.000605  0.0  0.333325  0.666649  0.000000  0.000000  10.047
 4    1.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  10.026
 ..        ...       ...  ...       ...       ...       ...       ...     ...
 767  0.997923  0.002280  0.0  0.333325  0.666649  0.214641  0.785128   9.373
 768  0.986233  0.013602  0.0  0.050907  0.949342  0.632440  0.367547   9.351
 769  0.994470  0.005691  0.0  0.500000  0.500000  1.000000  0.000000   8.953
 770  1.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000   8.749
 771  1.000000  0.000000  0.0  1.000000  0.000000  0.000000  0.000000   7.869


     Neff_I Neff_D
 0    1.005  0.000
 1    0.000  0.000
 2    1.007  0.000
 3    1.000  0.000
 4    0.000  0.000
 ..     ...    ...
 767  1.020  1.034
 768  1.032  1.025
 769  1.000  1.002
 770  0.000  0.000
 771  0.000  0.000

 [772 rows x 174 columns],
 '5kwj':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       5kwj               1             B            1            B
 1       5kwj               1             B            2            B
 2       5kwj               1             B            3            B
 3       5kwj               1             B            4            B
 4       5kwj               1             B            5            B
 ..       ...             ...           ...          ...          ...
 278     5kwj               1             B          279            B
 279     5kwj               1             B          280            B
 280     5kwj               1             B          281            B
 281     5kwj               1             B          282            B
 282     5kwj               1             B          283            B

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0             0                 ?     0               0               0  ...
 1             1                 ?     0               0               0  ...
 2             2                 ?     0               0               0  ...
 3             3                 ?     0               0               0  ...
 4             4                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 278         278                 ?     0               0               0  ...
 279         279                 ?     0               0               0  ...
 280         280                 ?     0               0               0  ...
 281         281                 ?     0               0               0  ...
 282         282                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.985549  0.000000  0.014548  0.000000  0.000000  0.000000  0.000000
 1    1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 2    0.988286  0.011817  0.000000  1.000000  0.000000  0.000000  0.000000
 3    0.995850  0.004370  0.000000  0.500000  0.500000  0.000000  0.000000
 4    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 ..        ...       ...       ...       ...       ...       ...       ...
 278  0.994470  0.003657  0.002066  0.238490  0.761544  1.000000  0.000000
 279  0.994470  0.002472  0.002799  0.227510  0.772711  0.590496  0.409235
 280  0.991030  0.007933  0.001198  0.046071  0.953960  0.301034  0.698823
 281  0.991030  0.008777  0.000000  0.556711  0.443191  0.676424  0.323761
 282  0.990343  0.009578  0.000000  0.170282  0.829895  0.000000  1.000000


        Neff Neff_I Neff_D
 0    10.217  0.000  0.000
 1    11.268  0.000  1.005
 2    11.773  1.031  0.000
 3    11.926  1.004  0.000
 4    12.055  0.000  0.000
 ..      ...    ...    ...
 278  13.059  1.056  1.005
 279  13.017  1.032  1.019
 280  12.905  1.109  1.035
 281  12.822  1.129  1.037
 282  12.793  1.101  1.000

 [283 rows x 174 columns],
 '6t4k':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       6t4k               1             A           23            A
 1       6t4k               1             A           24            A
 2       6t4k               1             A           25            A
 3       6t4k               1             A           26            A
 4       6t4k               1             A           27            A
 ..       ...             ...           ...          ...          ...
 235     6t4k               1             A          259            A
 236     6t4k               1             A          260            A
 237     6t4k               1             A          261            A
 238     6t4k               1             A          262            A
 239     6t4k               1             A          263            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0           267                 ?     0               0               0  ...
 1           268                 ?     0               0               0  ...
 2           269                 ?     0               0               0  ...
 3           270                 ?     0               0               0  ...
 4           271                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 235         503                 ?     0               0               0  ...
 236         504                 ?     0               0               0  ...
 237         505                 ?     0               0               0  ...
 238         506                 ?     0               0               0  ...
 239         507                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.997231  0.000000  0.002514  0.000000  0.000000  0.871154  0.129050
 1    1.000000  0.000000  0.000000  0.000000  0.000000  0.454389  0.545632
 2    0.984866  0.009645  0.005479  0.381565  0.618566  0.000000  1.000000
 3    0.946714  0.030863  0.022655  0.078183  0.922103  0.574349  0.425727
 4    0.967276  0.030206  0.002648  1.000000  0.000000  0.601235  0.398596
 ..        ...       ...       ...       ...       ...       ...       ...
 235  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 236  0.993781  0.004914  0.001625  0.500000  0.500000  0.000000  0.000000
 237  0.998615  0.001070  0.000000  0.166662  0.833353  1.000000  0.000000
 238  0.997231  0.002650  0.000000  0.500000  0.500000  0.000000  0.000000
 239  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


        Neff Neff_I Neff_D
 0    10.990  0.000  1.095
 1    10.962  0.000  1.018
 2    10.953  1.098  1.004
 3    10.921  1.242  1.048
 4    10.943  1.230  1.204
 ..      ...    ...    ...
 235  11.084  0.000  0.000
 236  11.080  1.028  0.000
 237  11.058  1.001  1.001
 238  11.033  1.000  0.000
 239  10.362  0.000  0.000

 [240 rows x 174 columns],
 '5mo6':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       5mo6               1             B           26            A
 1       5mo6               1             B           27            A
 2       5mo6               1             B           28            A
 3       5mo6               1             B           29            A
 4       5mo6               1             B           30            A
 ..       ...             ...           ...          ...          ...
 320     5mo6               1             B          346            A
 321     5mo6               1             B          347            A
 322     5mo6               1             B          348            A
 323     5mo6               1             B          349            A
 324     5mo6               1             B          350            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0             3                 ?     0               0               0  ...
 1             4                 ?     0               0               0  ...
 2             5                 ?     0               0               0  ...
 3             6                 ?     0               0               0  ...
 4             7                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 320         323                 ?     0               0               0  ...
 321         324                 ?     0               0               0  ...
 322         325                 ?     0               0               0  ...
 323         326                 ?     0               0               0  ...
 324         327                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.953960  0.038261  0.007960  0.366783  0.633317  0.351355  0.648420
 1    0.965267  0.010273  0.024332  0.248273  0.751581  0.100342  0.899378
 2    0.961927  0.026812  0.011502  0.187115  0.812816  0.431371  0.568803
 3    0.959264  0.011018  0.029523  0.571965  0.428094  0.319082  0.680657
 4    0.958599  0.009420  0.032106  0.231808  0.768438  0.363745  0.636397
 ..        ...       ...       ...       ...       ...       ...       ...
 320  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 321  0.995160  0.004951  0.000000  0.055553  0.944747  0.000000  0.000000
 322  0.991717  0.008591  0.000000  0.150726  0.849096  0.000000  0.000000
 323  0.992404  0.007573  0.000000  0.099995  0.900002  0.000000  0.000000
 324  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000


        Neff Neff_I Neff_D
 0     9.635  1.202  1.247
 1     9.375  1.057  1.195
 2     9.430  1.129  1.315
 3     9.466  1.040  1.231
 4     9.465  1.028  1.307
 ..      ...    ...    ...
 320  10.818  0.000  0.000
 321  10.608  1.005  0.000
 322  10.338  1.027  0.000
 323  10.237  1.005  0.000
 324   9.822  0.000  0.000

 [325 rows x 174 columns],
 '3o0n':      Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0        3o0n               1             A            1            A
 1        3o0n               1             A            2            A
 2        3o0n               1             A            3            A
 3        3o0n               1             A            4            A
 4        3o0n               1             A            5            A
 ...       ...             ...           ...          ...          ...
 1213     3o0n               1             B          629            B
 1214     3o0n               1             B          630            B
 1215     3o0n               1             B          631            B
 1216     3o0n               1             B          632            B
 1217     3o0n               1             B          633            B

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0              1                 ?     0               0               0  ...
 1              2                 ?     0               0               0  ...
 2              3                 ?     0               0               0  ...
 3              4                 ?     0               0               0  ...
 4              5                 ?     0               0               0  ...
 ...          ...               ...   ...             ...             ...  ...
 1213         629                 ?     0               0               0  ...
 1214         630                 ?     0               0               0  ...
 1215         631                 ?     0               0               0  ...
 1216         632                 ?     0               0               0  ...
 1217         633                 ?     0               0               0  ...

        HHBlits                                                           \
           M->M      M->I      M->D      I->M      I->I D->M D->D   Neff
 0     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  4.807
 1     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  7.169
 2     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  7.734
 3     0.990343  0.009848  0.000000  1.000000  0.000000  0.0  0.0  7.969
 4     1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  8.215
 ...        ...       ...       ...       ...       ...  ...  ...    ...
 1213  0.996540  0.002648  0.000772  0.590496  0.409235  0.0  0.0  8.514
 1214  0.997923  0.000727  0.001034  0.250000  0.750019  0.0  1.0  8.459
 1215  1.000000  0.000000  0.000000  0.000000  0.000000  1.0  0.0  8.360
 1216  0.978742  0.019424  0.002040  0.886996  0.112734  0.0  0.0  8.307
 1217  0.978063  0.005097  0.016828  0.436786  0.562919  1.0  0.0  8.011


      Neff_I Neff_D
 0     0.000  0.000
 1     0.000  0.000
 2     0.000  0.000
 3     1.000  0.000
 4     0.000  0.000
 ...     ...    ...
 1213  1.010  0.000
 1214  1.000  1.000
 1215  0.000  1.004
 1216  1.108  0.000
 1217  1.018  1.002

 [1218 rows x 174 columns],
 '1tjp':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       1tjp               1             A            1            A
 1       1tjp               1             A            2            A
 2       1tjp               1             A            3            A
 3       1tjp               1             A            4            A
 4       1tjp               1             A            5            A
 ..       ...             ...           ...          ...          ...
 262     1tjp               1             A          263            A
 263     1tjp               1             A          264            A
 264     1tjp               1             A          265            A
 265     1tjp               1             A          266            A
 266     1tjp               1             A          267            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0             1                 ?     0               0               0  ...
 1             2                 ?     0               0               0  ...
 2             3                 ?     0               0               0  ...
 3             4                 ?     0               0               0  ...
 4             5                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 262         263                 ?     0               0               0  ...
 263         264                 ?     0               1               0  ...
 264         265                 ?     0               1               0  ...
 265         266                 ?     0               0               0  ...
 266         267                 ?     0               0               0  ...

       HHBlits                                                            \
          M->M      M->I      M->D      I->M      I->I D->M D->D    Neff
 0    0.991030  0.004083  0.004591  1.000000  0.000000  0.0  0.0  11.247
 1    0.988971  0.011249  0.000000  0.414085  0.586011  1.0  0.0  11.455
 2    0.996540  0.000000  0.003570  0.000000  0.000000  0.0  0.0  11.556
 3    0.994470  0.002834  0.002535  1.000000  0.000000  1.0  0.0  11.684
 4    0.994470  0.000000  0.005230  0.000000  0.000000  1.0  0.0  11.781
 ..        ...       ...       ...       ...       ...  ...  ...     ...
 262  0.997231  0.001565  0.001351  1.000000  0.000000  1.0  0.0  11.915
 263  0.997231  0.000000  0.002584  0.000000  0.000000  1.0  0.0  11.877
 264  0.988971  0.010881  0.000000  0.750019  0.249827  1.0  0.0  11.687
 265  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  11.624
 266  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  11.420


     Neff_I Neff_D
 0    1.000  0.000
 1    1.045  1.003
 2    0.000  0.000
 3    1.006  1.000
 4    0.000  1.001
 ..     ...    ...
 262  1.000  1.000
 263  0.000  1.000
 264  1.034  1.000
 265  0.000  0.000
 266  0.000  0.000

 [267 rows x 174 columns],
 '4bqh':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       4bqh               1             A            1            A
 1       4bqh               1             A            2            A
 2       4bqh               1             A            3            A
 3       4bqh               1             A            4            A
 4       4bqh               1             A            5            A
 ..       ...             ...           ...          ...          ...

In [4]:
representatives = list(featuresd.keys())

len(representatives), representatives

(289,
 ['6ta3',
  '5kwj',
  '6t4k',
  '5mo6',
  '3o0n',
  '1tjp',
  '4bqh',
  '1og0',
  '5jv1',
  '3auy',
  '5dl1',
  '1qqb',
  '6hgj',
  '4aau',
  '7juv',
  '6nzf',
  '5uyy',
  '5xez',
  '2b08',
  '2c2b',
  '3i0s',
  '4dpq',
  '2d5x',
  '7amj',
  '2qmx',
  '3e5u',
  '4bo1',
  '6mo1',
  '2him',
  '5aa4',
  '5h08',
  '3kq7',
  '2qei',
  '8jii',
  '5y66',
  '6pgr',
  '2ha2',
  '5dzh',
  '7anw',
  '6e5g',
  '4pcu',
  '6bky',
  '6gfm',
  '4ejl',
  '5f2e',
  '6r4d',
  '7ehm',
  '6o0h',
  '4a79',
  '3dc2',
  '6ueg',
  '3kh5',
  '8hnn',
  '5ngz',
  '7mew',
  '5m1a',
  '3smq',
  '5hue',
  '4lrl',
  '5urj',
  '6huj',
  '1hkb',
  '2ldb',
  '2cdq',
  '5lvx',
  '2dz9',
  '6bvn',
  '1jlr',
  '5fii',
  '6sbv',
  '4bxc',
  '5ifu',
  '7ljc',
  '2jfz',
  '6o0n',
  '5swo',
  '6w6d',
  '4dn0',
  '6dhm',
  '5on7',
  '5hot',
  '3kjn',
  '6shq',
  '4coj',
  '6qjw',
  '5tkb',
  '5mro',
  '6i5g',
  '2bu6',
  '4zsk',
  '5x33',
  '5m0s',
  '6f7i',
  '6usa',
  '2vk1',
  '5kcv',
  '3f6g',
  '4avc',
  '3cmu',
  '5i73',
  '3c1n',
  '4ypl',
  '5oj0',
  '5f6y',
  '5htc',
  '6px5',
  '5nxd',
  '2o8e',
  '6cwy',
  '5c2o',
  '6uxy',
  '1i6k',
  '5wsb',
  '8v8c',
  '2ylq',
  '6zgv',
  '1ygc',
  '5we8',
  '6jta',
  '6qu3',
  '6c98',
  '1q43',
  '3x1m',
  '2zb2',
  '1msv',
  '3uvv',
  '5iv3',
  '6mc1',
  '5zwj',
  '5npk',
  '2p9g',
  '4n7j',
  '4b6e',
  '5v03',
  '6z89',
  '6li0',
  '5o2d',
  '8jr9',
  '8tb7',
  '4ofg',
  '5y8t',
  '7lz4',
  '6qxl',
  '7c7q',
  '6kun',
  '8jpf',
  '2zv2',
  '5kls',
  '6x83',
  '3eps',
  '4mi4',
  '3nqs',
  '4or2',
  '3zm9',
  '4gqq',
  '6rrp',
  '6kkb',
  '5lrs',
  '4q9o',
  '2bty',
  '2fhy',
  '5l7i',
  '5kde',
  '3fud',
  '3wgg',
  '3cev',
  '3ho6',
  '7dtu',
  '5xzr',
  '6w2j',
  '2vvt',
  '7dpt',
  '3tho',
  '5wmv',
  '1bj4',
  '1vea',
  '5u7m',
  '5var',
  '4ov9',
  '5ogc',
  '4z07',
  '7q12',
  '6fba',
  '4ohf',
  '5xe9',
  '6vvd',
  '6ku3',
  '6iil',
  '5klq',
  '3d2e',
  '1zxm',
  '6yd5',
  '5f1u',
  '4w9n',
  '5w6y',
  '4nes',
  '3i59',
  '6eg3',
  '6boz',
  '1dku',
  '6d7o',
  '3uqd',
  '1egy',
  '4g9c',
  '6thc',
  '6swx',
  '5icn',
  '4c8b',
  '6wkn',
  '1tbf',
  '6pwh',
  '1ecb',
  '6qzh',
  '3edc',
  '6pf1',
  '3pjg',
  '6bbq',
  '7lw1',
  '1t5a',
  '6yuh',
  '4aqh',
  '5gug',
  '1kmp',
  '1rd4',
  '4kzt',
  '3zou',
  '5in4',
  '6hho',
  '6xp9',
  '6x9h',
  '5n9t',
  '1opl',
  '5i2c',
  '7d8x',
  '6qkw',
  '6yz4',
  '5f74',
  '6ms7',
  '2jfn',
  '4yb5',
  '5iov',
  '3dba',
  '6hv0',
  '5o1s',
  '6ui4',
  '6n3n',
  '6r02',
  '5ue4',
  '6jvu',
  '5j6f',
  '7fee',
  '5btr',
  '2i80',
  '5zma',
  '3mwb',
  '5jwc',
  '2q5o',
  '7p2l',
  '6np0',
  '2j0x',
  '5jjr',
  '3fzy',
  '6ruq',
  '3ath',
  '6s8g',
  '3kcc',
  '6izw',
  '8gti',
  '7aud',
  '6czm',
  '1i1q',
  '4tme',
  '6u1n',
  '4i7w',
  '5lwe',
  '3l76',
  '1ne7',
  '5ixe',
  '6iq4',
  '8dwg',
  '4rt7',
  '6rmd',
  '3mks',
  '3qh0',
  '4fha',
  '4zht',
  '8fe1',
  '4op0',
  '3d2p'])

In [6]:
seqsf = "2.Clustering/seqs.pkl"

with open(seqsf, "rb") as f:
    seqs = {
        (pdb, entry_id): seq
        for (pdb, entry_id, asym_id), seq in pickle.load(f).items()
        if pdb in representatives
    }

seqs

{('5kwj',
  '1'): 'MFSRPGLPVEYLQVPSASMGRDIKVQFQGGGPHAVYLLDGLRAQDDYNGWDINTPAFEEYYQSGLSVIMPVGGQSSFYTDWYQPSQSNGQNYTYKWETFLTREMPAWLQANKGVSPTGNAAVGLSMSGGSALILAAYYPQQFPYAASLSGFLNPSEGWWPTLIGLAMNDSGGYNANSMWGPSSDPAWKRNDPMVQIPRLVANNTRIWVYCGNGTPSDLGGDNIPAKFLEGLTLRTNQTFRDTYAADGGRNGVFNFPPNGTHSWPYWNEQLVAMKADIQHVLNGATPPAAPAAPAALEHHHHHH',
 ('6t4k',
  '1'): 'GSSHHHHHHSSGLVPRGSHMASLTEIEHLVQSVCKSYRETCQLRLEDLLRQRSNIFSREEVTGYQRKSMWEMWERCAHHLTEAIQYVVEFAKRLSGFMELCQNDQIVLLKAGAMEVVLVRMCRAYNADNRTVFFEGKYGGMELFRALGCSELISSIFDFSHSLSALHFSEDEIALYTALVLINAHRPGLQEKRKVEQLQYNLELAFHHHLHKTHRQSILAKLPPKGKLRSLCSQHVERLQIFQHLHPIVVQAAFPPLYKELFS',
 ('5mo6',
  '1'): 'GSMDIEFDDDADDDGSGSGSGSGSSGPVPSRARVYTDVNTHRPSEYWDYESHVVEWGNQDDYQLVRKLGRGKYSEVFEAINITNNEKVVVKILKPVKKKKIKREIKILENLRGGPNIITLADIVKDPVSRTPALVFEHVNNTDFKQLYQTLTDYDIRFYMYEILKALDYCHSMGIMHRDVKPHNVMIDHEHRKLRLIDWGLAEFYHPGQEYNVRVASRYFKGPELLVDYQMYDYSLDMWSLGCMLASMIFRKEPFFHGHDNYDQLVRIAKVLGTEDLYDYIDKYNIELDPRFNDILGRHSRKRWERFVHSENQHLVSPEALDFLDKLLRYDHQSRLTAREAMEHPYFYTVVK',
 ('3o0n',
  '1'): 'MKLSDLISRWIDVEPSKNAQIILRDRYFMKDLDGNYLETKWEDVARRVARVVATAELLNPSYKKNEKLDRIKEWEDIFFRVLKARLFIPNSPTLFNAGLGVKHDLLWKPIDQMTLEDYEEIYRSRNHLHMLSACFVVPVGDSIEEIFEAVKEYALITKVGGGVGSNFSELRPKGSFVAGTHGKASGPVSFMHVFNSAISVVKQGSRRRGALMGILNINHPDIEEFIDAKKENTGEAVLNFFNLSVGFPMDKKEILKLYEEDGELELSHPRSTIRKKVKIRELFRKIATNAWKSGDPGLAFLGEMNKYYPLYPHRKINSTNPCGEIGLSDYEACNLGSIDVAKFYNNGFVDLEALQELVQIAVRFLDNVIDVNVFPIDKITKAVKESRRLGLGIMGFADLLYKLEIPYNSQEARDFAANLMAFIALHAHRTSYELGKEKGNFPLLEISRYRTEDNFVPFAMGMSNYDDEIREVMKMTKEFRRNVALLTIAPTGSISNIADTSSGLEPNFLLAYTRFVTKEDGTKEPLLYVNQVLREKLNPEILKRIEKELIEKGSLKDIPDVPEKIKKVFVVALDIDPMDHLLMQDAFQRYVDNNISKTINMPQSATVDDVLNVYLEALRTNVRGITVYRDGSLQTQVLTKALKT',
 ('1tjp',
  '1'): 'MERYENLFAQLNDRREGAFVPFVTLGDPGIEQSLKIIDTLIDAGADALELGVPFSDPLADGPTIQNANLRAFAAGVTPAQCFEMLALIREKHPTIPIGLLMYANLVFNNGIDAFYARCEQVGVDSVLVADVPVEESAPFRQAALRHNIAPIFICPPNADDDLLRQVASYGRGYTYLLSRSGVTGAENRGALPLHHLIEKLKEYHAAPALQGFGISSPEQVSAAVRAGAAGAISGSAIVKIIEKNLASPKQMLAELRSFVSAMKAASRA',
 ('4bqh',
  '1'): 'PLGSMSDRDVCIQRLTGANQDHILTALEHGSEAERASLTAQITNELAGVDFRHFNDVLRESLEISKNCSTASLAEPPAKDSFFDISSVDRRRGQAKRIKNLEAVGYKAIQKGQIAFLILAGGSGTRLGFDKPKGFFTCDGLQQRKSLFMMHCEKIRRRQEIAESISGSGRKARVQLLVMTSGQNDAETQRFFEENSYFGLEREQVHFFAQSSVPCYDENTGRIIMENRGRICAAPGGNGAVFAALAAPRATKDKDGTLQVKESLLQHLRKLGIAYVQIGNIDNLLANVADPVFIGYAIEEEAHVVVKTCPKRGPDERVGVFVRASGKWGVVEYTEIGDRAKEIDDATGELKFNCANISSNLCSLHFMSLAAERMKSFTQYHAARKKIPTIKGPVMGIKLEAFLFDLFRFVDECDHPPKDSGAFRIMQVDRDDEFGPVKNADGAASDTPADAVRLLLSQHTRWLITALETAAMSDEQESIRGGVDVTEAKEAVAVMRSCSIKAEISPLVSVGGEGLRQHLPRVIHQLLRNPPPVIFIRRDDEVVSESSNM',
 ('1og0',
  '1'): 'MSESPMFAANGMPKVNQGAEEDVRILGYDPLASPALLQVQIPATPTSLETAKRGRREAIDIITGKDDRVLVIVGPCSIHDLEAAQEYALRLKKLSDELKGDLSIIMRAYLEKPRTTVGWKGLINDPDVNNTFNINKGLQSARQLFVNLTNIGLPIGSEMLDTISPQYLADLVSFGAIGARTTESQLHRELASGLSFPVGFKNGTDGTLNVAVDACQAAAHSHHFMSVTKHGVAAITTTKGNEHCFVILRGGKKGTNYDAKSVAEAKAQLPAGSNGLMIDYSHGNSNKDFRNQPKVNDVVCEQIANGENAITGVMIESNINEGNQGIPAEGKAGLKYGVSITDACIGWETTEDVLRKLAAAVRQRREVNKK',
 ('5jv1',
  '1'): 'MGSSHHHHHHSSGRENLYFQGHMNGDQNSDVYAQEKQDFVQHFSQIVRVLTEDEMGHPEIGDAIARLKEVLEYNAIGGKYNRGLTVVVAFRELVEPRKQDADSLQRAWTVGWCVELLQAFFLVADDIMDSSLTRRGQICWYQKPGVGLDAINDANLLEACIYRLLKLYCREQPYYLNLIELFLQSSYQTEIGQTLDLLTAPQGNVDLVRFTEKRYKSIVKYKTAFYSFYLPIAAAMYMAGIDGEKEHANAKKILLEMGEFFQIQDDYLDLFGDPSVTGKIGTDIQDNKCSWLVVQCLQRATPEQYQILKENYGQKEAEKVARVKALYEELDLPAVFLQYEEDSYSHIMALIEQYAAPLPPAVFLGLARKIYKRRK',
 ('3auy',
  '1'): 'MSMILKEIRMNNFKSHVNSRIKFEKGIVAIIGENGSGKSSIFEAVFFALFGAGSNFNYDTIITKGKKSVYVELDFEVNGNNYKIIREYDSGRGGAKLYKNGKPYATTISAVNKAVNEILGVDRNMFLNSIYIKQGEIAKFLSLKPSEKLETVAKLLGIDEFEKCYQKMGEIVKEYEKRLERIEGELNYKEESLKARLKEMSNLEKEKEKLTKFVEYLDKVRRIFGRNGFQAYLREKYVPLIQKYLNEAFSEFDLPYSFVELTKDFEVRVHAPNGVLTIDNLSGGEQIAVALSLRLAIANALIGNRVECIILDEPTVYLDENRRAKLAEIFRKVKSIPQMIIITHHRELEDVADVIINVKKDGNVSKVKING',
 ('5dl1',
  '1'): 'MNLIPTVIETTNRGERAYDIYSRLLKDRIIMLGSQIDDNVANSIVSQLLFLQAQDSEKDIYLYINSPGGSVTAGFAIYDTIQHIKPDVQTICIGMAASMGSFLLAAGAKGKRFALPNAEVMIHQPLGGAQGQATEIEIAANHILKTREKLNRILSERTGQSIEKIQKDTDRDNFLTAEEAKEYGLIDEVMVPETK',
 ('1qqb',
  '2'): 'ATIKDVAKRANVSTTTVSHVINKTRFVAEETRNAVWAAIKELHYSPSAVARSLAVNHTKSIGLLATSSEAAYFAEIIEAVEKNCFQKGYTLILGNAWNNLEKQRAYLSMMAQKRVDGLLVMCSEYPEPLLAMLEEYRHIPMVVMDWGEAKADFTDAVIDNAFEGGYMAGRYLIERGHREIGVIPGPLERNTGAGRLAGFMKAMEEAMIKVPESWIVQGDFEPESGYRAMQQILSQPHRPTAVFCGGDIMAMGALCAADEMGLRVPQDVSLIGYDNVRNARYFTPALTTIHQPKDSLGETAFNMLLDRIVNKREEPQSIEVHPRLIERRSVADGPFRDYRR',
 ('6hgj',
  '1'): 'MKHHHHHHMKQNSPLDEENLTQENQDRGTHVDRGLASANVDFAFSLYKQLVLKAPDKNVIFSPVSISTALAFLSLGAHNTTLTEILKGLKFNLTETSEAEIHQSFQHLLRTLNQSSDELQLSMGNAMFVKEQLSLLDRFTEDAKRLYGSEAFATDFQDSAAAKKLINDYVKNGTRGKITDLIKDLDSQTMMVLVNYIFFKAKWEMPFDPQDTHQSRFYLSKKKWVMVPMMSLHHLTIPYFRDEELSCTVVQLNYTGNASVFFILPDQDKMEEVEAMLSRETLARWGDSLEFREIGELYLPKFSISRDYNLNDILLQLGIEEAFTSKADLSGITGARNLAVSQVVHKAVLDVFEEGTEASAATAVKITLL',
 ('6hgj', '2'): 'SALVETRTIVRFNRPFLMIIVDHFTWSIFFMSKVTNPKQA',
 ('4aau',
  '1'): 'MAAKDVKFGNDARVKMLRGVNVLADAVKVTLGPKGRNVVLDKSFGAPTITKDGVSVAREIELEDKFENMGAQMVKEVASKANDAAGDGTTTATVLAQAIITEGLKAVAAGMNPMDLKRGIDKAVTAAVEELKALSVPCSDSKAIAQVGTISANSDETVGKLIAEAMDKVGKEGVITVEDGTGLQDELDVVEGMQFDRGYLSPYFINKPETGAVELESPFILLADKKISNIREMLPVLEAVAKAGKPLLIIAEDVEGEALATLVVNTMRGIVKVAAVKAPGFGDRRKAMLQDIATLTGGTVISEEIGMELEKATLEDLGQAKRVVINKDTTTIIDGVGEEAAIQGRVAQIRQQIEEATSDYDREKLQERVAKLAGGVAVIKVGAATEVEMKEKKARVEAALHATRAAVEEGVVAGGGVALIRVASKLADLRGQNEDQNVGIKVALRAMEAPLRQIVLNCGEEPSVVANTVKGGDGNYGYNAATEEYGNMIDMGILDPTKVTRSALQYAASVAGLMITTECMVTDLPKNDAADLGAAGGMGGMGGMGGMM',
 ('6nzf',
  '1'): 'MGSSHHHHHHSSGETVRFQGHMNLSQLSFHRVDQKEITQLSHLGQGTRTNVYEGRLRVEGSGDPEEGKMDDEDPLVPGRDRGQELRVVLKVLDPSHHDIALAFYETASLMSQVSHTHLAFVHGVCVRGPENIMVTEYVEHGPLDVWLRRERGHVPMAWKMVVAQQLASALSYLENKNLVHGNVCGRNILLARLGLAEGTSPFIKLSDPGVGLGALSREERVERIPWLAPECLPGGANSLSTAMDKWGFGATLLEICFDGEAPLQSRSPSEKEHFYQRQHRLPEPSCPQLATLTSQCLTYEPTQRPSFRTILRDLTRL',
 ('5uyy',
  '1'): 'SNAMKIKKESLEMRQMRKKVVLIGTGLIGGSLALAIKKDHDVTITGYDIFQEQVERAKELHVVDEIAVDLQHACEEAHLIVFASPVEETKKLLHKLASFHLREDVIVTDVGSTKGSIMNEAEALFSKEISFIGGHPMAGSHKTGVESAKAHLFENAFYILTPMHHVPNEHVEELKDWLKGTGSHFLVLNTEEHDYVTGIVSHFPHLIAAGLVKQVEKHAGDNPLIHQLAAGGFKDITRIASSSPKMWSDIVKQNREHLMVLLKEWISEMEDLYDTVSSGDAGEIQNYFADAKEYRDSLPVRKRGAIPAYHDLYVDVLDKVGALAHVTSILAREEISITNLQILEAREGLLGVLRISFQREEDRMKAKLALGEEKYQTYETI',
 ('5xez',
  '1'): 'GAPQVMDFLFEKWKLYGDQCHHNLSLLPPPTELVCNRTFDKYSCWPDTPANTTANISCPWYLPWHHKVQHRFVFKRCGPDGQWVRGPRGQPWRDASQCQMDGEEIEVQKEVAKMYSSFQVMYTVGYSLSLGALLLALAILGGLSKLHCTRNAIHANLFASFVLKASSVLVIDGLLRTRYSQKIGDDLSVSTWLSDGAVAGCRVAAVFMQYGIVANYCWLLVEGLYLHNLLGLANIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYERSFFSLYLGIGWGAPMLFVVPWAVVKCLFENVQCWTSNDNMGFWWILRFPVFLAILINFFIFVRIVQLLVAKLRARQMHHTDYKFRLAKSTLTLIPLLGVHEVVFAFVTDEHAQGTLRSAKLFFDLFLSSFQGLLVAVLYCFLNKEVQSELRRRWHRWRLGKVLWEERNTSNEFLEVLFQ',
 ('2b08',
  '1'): 'VRKATAAEIAALPRQKVELVDPPFVHAHSQVAEGGPKVVEFTMVIEEKKIVIDDAGTEVHAMAFNGTVPGPLMVVHQDDYLELTLINPETNTLMHNIDFHAATGALGGGGLTEINPGEKTILRFKATKPGVFVYHCAPPGMVPWHVVSGGNGAIMVLPREGLHDGKGKALTYDKIYYVGEQDFYVPRDENGKYKKYEAPGDAYEDTVKVMRTLTPTHVVFNGAVGALTGDKAMTAAVGEKVLIVHSQANRDTRPHLIGGHGDYVWATGKFNTPPDVDQETWFIPGGAAGAAFYTFQQPGIYAYVNHNLIEAFELGAAAHFKVTGEWNDDLMTSVLAPSGT',
 ('2c2b',
  '1'): 'ADGNNIKAPIETAVKPPHRTEDNIRDEARRNRSNAVNPFSAKYVPFNAAPGSTESYSLDEIVYRSRSGGLLDVEHDMEALKRFDGAYWRDLFDSRVGKSTWPYGSGVWSKKEWVLPEIDDDDIVSAFEGNSNLFWAERFGKQFLGMNDLWVKHCGISHTGSFKDLGMTVLVSQVNRLRKMKRPVVGVGCASTGDTSAALSAYCASAGIPSIVFLPANKISMAQLVQPIANGAFVLSIDTDFDGCMKLIREITAELPIYLANSLNSLRLEGQKTAAIEILQQFDWQVPDWVIVPGGNLGNIYAFYKGFKMCQELGLVDRIPRMVCAQAANANPLYLHYKSGWKDFKPMTASTTFASAIQIGDPVSIDRAVYALKKCNGIVEEATEEELMDAMAQADSTGMFICPHTGVALTALFKLRNQGVIAPTDRTVVVSTAHGLKFTQSKIDYHSNAIPDMACRFSNPPVDVKADFGAVMDVLKSYLGSNTLTS',
 ('3i0s',
  '1'): 'MNSPISPIETVPVKLKPGMDGPKVKQWPLTEEKIKALVEICTEMEKEGKISKIGPENPYNTPVFAIKKKDSTKWRKLVDFRELNKRTQDFWEVQLGIPHPAGLKKKKSVTVLDVGDAYFSVPLDEDFRKYTAFTIPSINNETPGIRYQYNVLPQGWKGSPAIFQSSMTKILEPFRKQNPDIVIYQYMDDLYVGSDLEIGQHRTKIEELRQHLLRWGLTTPDKKHQKEPPFLWMGYELHPDKWTVQPIVLPEKDSWTVNDIQKLVGKLNWASQIYPGIKVRQLCKLLRGTKALTEVIPLTEEAELELAENREILKEPVHGVYYDPSKDLIAEIQKQGQGQWTYQIYQEPFKNLKTGKYARMRGAHTNDVKQLTEAVQKITTESIVIWGKTPKFKLPIQKETWETWWTEYWQATWIPEWEFVNTPPLVKLWYQLEKEPIVGAETFYVDGAANRETKLGKAGYVTNRGRQKVVTLTDTTNQKTELQAIYLALQDSGLEVNIVTDSQYALGIIQAQPDQSESELVNQIIEQLIKKEKVYLAWVPAHKGIGGNEQVDKLVSAGIRKVL',
 ('4dpq',
  '1'): 'MHHHHHHGLPIPNPLLGLDSTENLYFQGIDPFTAAVVPNFHLPMRSLEVKNRTNTDDIKALRVITAIKTPYLPDGRFDLEAYDDLVNIQIQNGAEGVIVGGTTGEGQLMSWDEHIMLIGHTVNCFGGSIKVIGNTGSNSTREAIHATEQGFAVGMHAALHINPYYGKTSIEGLIAHFQSVLHMGPTIIYNVPGRTGQDIPPRAIFKLSQNPNLAGVKECVGNKRVEEYTENGVVVWSGNDDECHDSRWDYGATGVISVTSNLVPGLMRKLMFEGRNSSLNSKLLPLMAWLFHEPNPIGINTALAQLGVSRPVFRLPYVPLPLSKRLEFVKLVKEIGREHFVGEKDVQALDDDDFILIGRY',
 ('2d5x',
  '1'): 'VLSAADKTNVKAAWSKVGGHAGEYGAEALERMFLGFPTTKTYFPHFDLSHGSAQVKAHGKKVGDALTLAVGHLDDLPGALSNLSDLHAHKLRVDPVNFKLLSHCLLSTLAVHLPNDFTPAVHASLDKFLSSVSTVLTSKYR',
 ('2d5x',
  '2'): 'VQLSGEEKAAVLALWDKVNEEEVGGEALGRLLVVYPWTQRFFDSFGDLSNPGAVMGNPKVKAHGKKVLHSFGEGVHHLDNLKGTFAALSELHCDKLHVDPENFRLLGNVLVVVLARHFGKDFTPELQASYQKVVAGVANALAHKYH',
 ('7amj',
  '1'): 'SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTSEDMLNPNYEDLLIRKSNHNFLVQAGNVQLRVIGHSMQNCVLKLKVDTANPKTPKYKFVRIQPGQTFSVLACYNGSPSGVYQCAMRPNFTIKGSFLNGSCGSVGFNIDYDCVSFCYMHHMELPTGVHAGTDLEGNFYGPFVDRQTAQAAGTDTTITVNVLAWLYAAVINGDRWFLNRFTTTLNDFNLVAMKYNYEPLTQDHVDILGPLSAQTGIAVLDMCASLKELLQNGMNGRTILGSALLEDEFTPFDVVRQCSGVTFQ',
 ('2qmx',
  '1'): 'SNAMTNWLIAYQGEPGAYSEIAALRFGEPLPCESFDDVFSAVTEQKADYAVIPIENSLGGSIHQNYDLLLRRPVVILAETFVKVEHCLLGLPGASVETATKAMSHPQALVQCHNFFATHPQIRAEAAYDTAGSAKMVAESRDKSALAIASKRAGELYGLDILKENLADEEWNITRFFCIAHENNPDISHLKVRPDVARQKTSIVFALPNEQGSLFRALATFALRGIDLTKIESRPSRKKAFEYLFYADFIGHREDQNVHNALENLREFATMVKVLGSYGVVNP',
 ('3e5u',
  '1'): 'MSVEGLGKDFCGAIIPDNFFPIEKLRNYTQMGLIRDFAKGSAVIMPGEEITSMIFLVEGKIKLDIIFEDGSEKLLYYAGGNSLIGKLYPTGNNIYATAMEPTRTCWFSEKSLRTVFRTDEDMIFEIFKNYLTKVAYYARQVAEMNTYNPTIRILRLFYELCSSQGKRVGDTYEITMPLSQKSIGEITGVHHVTVSRVLASLKRENILDKKKNKIIVYNLGELKHLSEQTSYYSDPNSSSVDKLAAALDHH',
 ('4bo1',
  '1'): 'MHHHHHHSSGVDLGTENLYFQSMSLQGKVALVTGASRGIGQAIALELGRLGAVVIGTATSASGAEKIAETLKANGVEGAGLVLDVSSDESVAATLEHIQQHLGQPLIVVNNAGITRDNLLVRMKDDEWFDVVNTNLNSLYRLSKAVLRGMTKARWGRIINIGSVVGAMGNAGQTNYAAAKAGLEGFTRALAREVGSRAITVNAVAPGFIDTDMTRELPEAQREALLGQIPLGRLGQAEEIAKVVGFLASDGAAYVTGATVPVNGGMYMS',
 ('6mo1',
  '1'): 'GSHMLMADLELERAADVRWEEQAEISGSSPILSITISEDGSMSIKNEEEEQTLGGGGSGGGGAGVLWDVPSPPPVGKAELEDGAYRIKQKGILGYSQIGAGVYKEGTFHTMWHVTRGAVLMHKGKRIEPSWADVKKDLISYGGGWKLEGEWKEGEEVQVLALEPGKNPRAVQTKPGLFKTNTGTIGAVSLDFSPGTSGSPIVDKKGKVVGLYGNGVVTRSGAYVSAIANTEKSIEDNPEIEDDIFRK',
 ('2him',
  '1'): 'MGSSHHHHHHSSGLVPRGSHMQKKSIYVAYTGGTIGMQRSEQGYIPVSGHLQRQLALMPEFHRPEMPDFTIHEYTPLMDSSDMTPEDWQHIAEDIKAHYDDYDGFVILHGTDTMAYTASALSFMLENLGKPVIVTGSQIPLAELRSDGQINLLNALYVAANYPINEVTLFFNNRLYRGNRTAKAHADGFDAFASPNLPPLLEAGIHIRRLNTPPAPHGEGELIVHPITPQPIGVVTIYPGISADVVRNFLRQPVKALILRSYGVGNAPQNKAFLQELQEASDRGIVVVNLTQCMSGKVNMGGYATGNALAHAGVIGGADMTVEATLTKLHYLLSQELDTETIRKAMSQNLRGELTPDD',
 ('5aa4',
  '1'): 'QKEGVLRVITRNSPATYFQDRNGETGFEYELAKRFAERLGVELKIETADNLDDLYAQLSREGGPALAAAGLTPGREDDASVRYSHTYLDVTPQIIYRNGQQRPTRPEDLVGKRIMVLKGSSHAEQLAELKKQYPELKYEESDAVEVVDLLRMVDVGDIDLTLVDSNELAMNQVYFPNVRVAFDFGEARGLAWALPGGDDDSLMNEVNAFLDQAKKEGLLQRLKDRYYGHVDVLGYVGAYTFAQHLQQRLPRYESHFKQSGKQKDTDWRLLAAIGYQESLWQPGATSKTGVRGLMMLTNRTAQAMGVSNRLDPKQSIQGGSKYFVQIRSELPESIKEPDRSWFALAAYNIGGAHLEDARKMAEKEGLNPNKWLDVKKMLPRLAQKQWYAKTRYGYARGGETVHFVQNVRRYYDILTWVTQPQMEGSQIAESGLHLPGVNKTRPEEDSGDEKL',
 ('5h08',
  '1'): 'GPAIPIKHFPKHVADLHASSGFTEEFEEVQSCTVDLGITADSSNHPDNKHKNRYINIVAYDHSRVKLAQLAEKDGKLTDYINANYVDGYNRPKAYIAAQGPLKSTAEDFWRMIWEHNVEVIVMITNLVEKGRRKCDQYWPADGSEEYGNFLVTQKSVQVLAYYTVRNFTLRNTKIKKGSQKGRPSGRVVTQYHYTQWPDMGVPEYSLPVLTFVRKAAYAKRHAVGPVVVHCSAGVGRTGTYIVLDSMLQQIQHEGTVNIFGFLKHIRSQRNYLVQTEEQYVFIHDTLVEAILSKETEV',
 ('3kq7',
  '1'): 'MGSSHHHHHHSSGLVPRGSHMSQERPTFYRQELNKTIWEVPERYQNLSPVGSGAYGSVCAAFDTKTGLRVAVKKLSRPFQSIIHAKRTYRELRLLKHMKHENVIGLLDVFTPARSLEEFNDVYLVTHLMGADLNNIVKCQKLTDDHVQFLIYQILRGLKYIHSADIIHRDLKPSNLAVNEDCELKILDFGLARHTDDEMTGYVATRWYRAPEIMLNWMHYNQTVDIWSVGCIMAELLTGRTLFPGTDHIDQLKLILRLVGTPGAELLKKISSESARNYIQSLTQMPKMNFANVFIGANPLAVDLLEKMLVLDSDKRITAAQALAHAYFAQYHDPDDEPVADPYDQSFESRDLLIDEWKSLTYDEVISFVPPPLDQEEMES',
 ('2qei',
  '1'): 'MEVKREHWATRLGLILAMAGNAVGLGNFLRFPVQAAENGGGAFMIPYIIAFLLVGIPLMWIEWAMGRYGGAQGHGTTPAIFYLLWRNRFAKILGVFGLWIPLVVAIYYVYIESWTLGFAIKFLVGLVPEPPPNATDPDSILRPFKEFLYSYIGVPKGDEPILKPSLFAYIVFLITMFINVSILIRGISKGIERFAKIAMPTLFILAVFLVIRVFLLETPNGTAADGLNFLWTPDFEKLKDPGVWIAAVGQIFFTLSLGFGAIITYASYVRKDQDIVLSGLTAATLNEKAEVILGGSISIPAAVAFFGVANAVAIAKAGAFNLGFITLPAIFSQTAGGTFLGFLWFFLLFFAGLTSSIAIMQPMIAFLEDELKLSRKHAVLWTAAIVFFSAHLVMFLNKSLDEMDFWAGTIGVVFFGLTELIIFFWIFGADKAWEEINRGGIIKVPRIYYYVMRYITPAFLAVLLVVWAREYIPKIMEETHWTVWITRFYIIGLFLFLTFLVFLAERRRNHESAGTLVPR',
 ('8jii',
  '5'): 'MKTIIALSYIFCLVFADYKDDDDAHHHHHHHHHHMNRHHLQDHFLEIDKKNCCVFRDDFIVKVLPPVLGLEFIFGLLGNGLALWIFCFHLKSWKSSRIFLFNLAVADFLLIICLPFLMDNYVRRWDWKFGDIPCRLMLFMLAMNRQGSIIFLTVVAVDRYFRVVHPHHALNKISNRTAAIISCLLWGITIGLTVHLLKKKMPIQNGGANLCSSFSICHTFQWHEAMFLLEFFLPLGIILFCSARIIWSLRQRQMDRHAKIKRAITFIMVVAIVFVICFLPSVVVRIRIFWLLHTSGTQNCEVYRSVDLAFFITLSFTYMNSMLDPVVYYFSSPSFPNFFSTLINRCLQRKMTGEPDNNRSTSVELTGDPNKTRGAPEALMANSGEPWSPSYLGPTSP',
 ('5y66',
  '1'): 'MGTATDNARQVTIIGAGLAGTLVARLLARNGWQVNLFERRPDPRIETGARGRSINLALAERGAHALRLAGLEREVLAEAVMMRGRMVHVPGTPPNLQPYGRDDSEVIWSINRDRLNRILLDGAEAAGASIHFNLGLDSVDFARQRLTLSNVSGERLEKRFHLLIGADGCNSAVRQAMASVVDLGEHLETQPHGYKELQITPEASAQFNLEPNALHIWPHGDYMCIALPNLDRSFTVTLFLHHQSPAAQPASPCFAQLVDGHAARRFFQRQFPDLSPMLDSLEQDFEHHPTGKLATLRLTTWHVGGQAVLLGDAAHPMVPFHGQGMNCALEDAVALAEHLQSAADNASALAAFTAQRQPDALAIQAMALENYVEMSSKVASPTYLLERELGQIMAQRQPTRFIPRYSMVTFSRLPYAQAMARGQIQEQLLKFAVANHSDLTSINLDAVEHEVTRCLPPLSHLCAAALEHHHHHH',
 ('6pgr',
  '1'): 'GGSMEGSLEREAPAGALAAVLKHSSTLPPESTQVRGYDFNRGVNYRALLEAFGTTGFQATNFGRAVQQVNAMIEKKLEPLSQDEDQHADLTQSRRPLTSCTIFLGYTSNLISSGIRETIRYLVQHNMVDVLVTTAGGVEEDLIKCLAPTYLGEFSLRGKELRENGINRIGNLLVPNENYCKFEDWLMPILDQMVMEQNTEGVKWTPSKMIARLGKEINNPESVYYWAQKNHIPVFSPALTDGSLGDMIFFHSYKNPGLVLDIVEDLRLINTQAIFAKCTGMIILGGGVVKHHIANANLMRNGADYAVYINTAQEFDGSDSGARPDEAVSWGKIRVDAQPVKVYADASLVFPLLVAETFAQKMDAFMHEKNED',
 ('2ha2',
  '1'): 'EGREDPQLLVRVRGGQLRGIRLKAPGGPVSAFLGIPFAEPPVGSRRFMPPEPKRPWSGVLDATTFQNVCYQYVDTLYPGFEGTEMWNPNRELSEDCLYLNVWTPYPRPASPTPVLIWIYGGGFYSGAASLDVYDGRFLAQVEGAVLVSMNYRVGTFGFLALPGSREAPGNVGLLDQRLALQWVQENIAAFGGDPMSVTLFGESAGAASVGMHILSLPSRSLFHRAVLQSGTPNGPWATVSAGEARRRATLLARLVGCPPGGAGGNDTELIACLRTRPAQDLVDHEWHVLPQESIFRFSFVPVVDGDFLSDTPEALINTGDFQDLQVLVGVVKDEGSYFLVYGVPGFSKDNESLISRAQFLAGVRIGVPQASDLAAEAVVLHYTDWLHPEDPTHLRDAMSAVVGDHNVVCPVAQLAGRLAAQGARVYAYIFEHRASTLTWPLWMGVPHGYEIEFIFGLPLDPSLNYTTEERIFAQRLMKYWTNFARTGDPNDPRDSKSPQWPPYTTAAQQYVSLNLKPLEVRRGLRAQTCAFWNRFLPKLLSAT',
 ('5dzh',
  '1'): 'IKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLSDLLLEMLDAHRLHAPTS',
 ('7anw',
  '1'): 'SYHHHHHHDYDIPTTENLYFQGAMGSERLAVPGPDGGGGTGPWWAAGGRGPREVSPGAGTEVQDALERALPELQQALSALKQAGGARAVGAGLAEVFQLVEEAWLLPAVGREVAQGLCDAIRLDGGLDLLLRLLQAPELETRVQAARLLEQILVAENRDRVARIGLGVILNLAKEREPVELARSVAGILEHMFKHSEETCQRLVAAGGLDAVLYWCRRTDPALLRHCALALGNCALHGGQAVQRRMVEKRAAEWLFPLAFSKEDELLRLHACLAVAVLATNKEVEREVERSGTLALVEPLVASLDPGRFARCLVDASDTSQGRGPDDLQRLVPLLDSNRLEAQCIGAFYLCAEAAIKSLQGKTKVFSDIGAIQSLKRLVSYSTNGTKSALAKRALRLLGEEVPRPILPSVPSWKEAEVQTWLQQIGFSKYCESFREQQVDGDLLLRLTEEELQTDLGMKSGITRKRFFRELTELKTFANYSTCDRSNLADWLGSLDPRFRQYTYGLVSCGLDRSLLHRVSEQQLLEDCGIHLGVHRARILTAAREMLHSPLPCTGGKPSGDTPDVFISYRRNSGSQLASLLKVHLQLHGFSVFIDVEKLEAGKFEDKLIQSVMGARNFVLVLSPGALDKCMQDHDCKDWVHKQIVTALSCGKNIVPIIDGFEWPEPQVLPEDMQAVLTFNGIKWSHEYQEATIEKIIRFLQGRSSRDSSAGSDTSLEGAAPMGPT',
 ('6e5g',
  '1'): 'GSHMAWQARGLGTARLQLVEFSAFVEPPDAVDSYQRHLFVHISQHCPSPGAPPLESVDVRQIYDKFPEKKGGLRELYDRGPPHAFFLVKFWADLNWGPSGEEAGAGGSISSGGFYGVSSQYESLEHMTLTCSSKVCSFGKQVVEKVETERAQLEDGRFVYRLLRSPMCEYLVNFLHKLRQLPERYMMNSVLENFTILQVVTNRDTQELLLCTAYVFEVSTSERGAQHHIYRLVRD',
 ('4pcu',
  '1'): 'MGSETPQAEVGPTGCPHRSGPHSAKGSLEKGSPEDKEAKEPLWIRPDAPSRCTWQLGRPASESPHHHTAPAKSPKILPDILKKIGDTPMVRINKIGKKFGLKCELLAKCEFFNAGGSVKDRISLRMIEDAERDGTLKPGDTIIEPTSGNTGIGLALAAAVRGYRCIIVMPEKMSSEKVDVLRALGAEIVRTPTNARFDSPSSHVGVAWRLKNEIPNSHILDQYRNASNPLAHYDTTADEILQQCDGKLDMLVASVGTGGTITGIARKLKEKCPGCRIIGVDPEGSILAEPEELNQTEQTTYEVEGIGYDFIPTVLDRTVVDKWFKSNDEEAFTFARMLIAQEGLLCGGSAGSTVAVAVKAAQELQEGQRCVVILPDSVRNYMTKFLSDRWMLQKGFLKEEDLTEKKPWWWHLRVQELGLSAPLTVLPTITCGHTIEILREKGFDQAPVVDEAGVILGMVTLGNMLSSLLAGKVQPSDQVGKVIYKQFKQIRLTDTLGRLSHILEMDHFALVVHEQQRQMVFGVVTAIDLLNFVAAQERDQKELHHHHHH',
 ('6bky',
  '1'): 'MSKKISGGSVVEMQGDEMTRIIWELIKEKLIFPYVELDLHSYDLGIENRDATNDQVTKDAAEAIKKHNVGVKCATITPDEKRVEEFKLKQMWKSPNGTIRNILGGTVFREAIICKNIPRLVSGWVKPIIIGRHAYGDQYRATDFVVPGPGKVEITYTPSDGTQKVTYLVHNFEEGGGVAMGMYNQDKSIEDFAHSSFQMALSKGWPLYLSTKNTILKKYDGRFKDIFQEIYDKQYKSQFEAQKIWYEHRLIDDMVAQAMKSEGGFIWACKNYDGDVQSDSVAQGYGSLGMMTSVLVCPDGKTVEAEAAHGTVTRHYRMYQKGQETSTNPIASIFAWTRGLAHRAKLDNNKELAFFANALEEVSIETIEAGFMTKDLAACIKGLPNVQRSDYLNTFEFMDKLGENLKIKLAQAKLSLEHHHHHHHH',
 ('6gfm',
  '1'): 'RGSHHHHHHTDPALRAITHISPLGSMDMLSQLEVDMLKRTASSDLYQLFRNCSLAVLNSGSLTDNSKELLSRFENFDINVLRRERGVKLELINPPEEAFVDGRIIRALQANLFAVLRDILFVYGQIHNTVRFPNLNLDNSVHITNLVFSILRNARALHVGEAPNMVVCWGGHSINENEYLYARRVGNQLGLRELNICTGCGPGAMEAPMKGAAVGHAQQRYKDSRFIGMTEPSIIAAEPPNPLVNELIIMPDIEKRLEAFVRIAHGIIIFPGGVGTAEELLYLLGILMNPANKDQVLPLILTGPKESADYFRVLDEFVVHTLGENARRHYRIIIDDAAEVARQMKKSMPLVKENRRDTGDAYSFNWSMRIAPDLQMPFEPSHENMANLKLYPDQPVEVLAADLRRAFSGIVAGNVKEVGIRAIEEFGPYKINGDKEIMRRMDDLLQGFVAQHRMKLPGSAYIPCYEICTGLCGR',
 ('4ejl',
  '1'): 'PQITLWKRPLVTIKIGGQLKEALLDTGADDTVIEEMNLPGRWKPKMIGGIGGFIKVRQYDQIIIEIAGHKAIGTVLVGPTPVNIIGRNLLTQIGATLNF',
 ('5f2e',
  '1'): 'GMTEYKLVVVGACGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETSLLDILDTAGQEEYSAMRDQYMRTGEGFLLVFAINNTKSFEDIHHYREQIKRVKDSEDVPMVLVGNKSDLPSRTVDTKQAQDLARSYGIPFIETSAKTRQGVDDAFYTLVREIRKHKEK',
 ('6r4d',
  '1'): 'GAMESKKRQWALEDFEIGRPLGKGKFGNVYLAREKQSKFILALKVLFKAQLEKAGVEHQLRREVEIQSHLRHPNILRLYGYFHDATRVYLILEYAPLGTVYRELQKLSKFDEQRTATYITELANALSYCHSKRVIHRDIKPENLLLGSAGELKIADFGWSVHAPSSRRTTLAGTLDYLPPEMIEGRMHDEKVDLWSLGVLCYEFLVGKPPFEANTYQETYKRISRVEFTFPDFVTEGARDLISRLLKHNPSQRPMLREVLEHPWITANSSKPSNAQNKESASKQS',
 ('7ehm',
  '1'): 'EAVVISGRKLAQQIKQEVRQEVEEWVASGNKRPHLSVILVGENPASHSYVLNKTRAAAVVGINSETIMKPASISEEELLNLINKLNNDDNVDGLLVQLPLPEHIDERRICNAVSPDKDVDGFHVINVGRMCLDQYSMLPATPWGVWEIIKRTGIPTLGKNVVVAGRSKNVGMPIAMLLHTDGAHERPGGDATVTISHRYTPKEQLKKHTILADIVISAAGIPNLITADMIKEGAAVIDVGINRVHDPVTAKPKLVGDVDFEGVRQKAGYITPVPGGVGPMTVAMLMKNTIIAAKKVLRLEEREVLKSKELGVATN',
 ('6o0h',
  '1'): 'MSAKAISEQTGKELLYKFICTTSAIQNRFKYARVTPDTDWARLLQDHPWLLSQNLVVKPDQLIKRRGKLGLVGVNLTLDGVKSWLKPRLGQEATVGKATGFLKNFLIEPFVPHSQAEEFYVCIYATREGDYVLFHHEGGVDVGDVDAKAQKLLVGVDEKLNPEDIKKHLLVHAPEDKKEILASFISGLFNFYEDLYFTYLEINPLVVTKDGVYVLDLAAKVDATADYICKVKWGDIEFPPPFGREAYPEEAYIADLDAKSGASLKLTLLNPKGRIWTMVAGGGASVVYSDTICDLGGVNELANYGEYSGAPSEQQTYDYAKTILSLMTREKHPDGKILIIGGSIANFTNVAATFKGIVRAIRDYQGPLKEHEVTIFVRRGGPNYQEGLRVMGEVGKTTGIPIHVFGTETHMTAIVGMALGHRPIPNQPPTAAHTANFLLNASGSTSTPAPSRTASFSESRADEVAPAKKAKPAMPQDSVPSPRSLQGKSTTLFSRHTKAIVWGMQTRAVQGMLDFDYVCSRDEPSVAAMVYPFTGDHKQKFYWGHKEILIPVFKNMADAMRKHPEVDVLINFASLRSAYDSTMETMNYAQIRTIAIIAEGIPEALTRKLIKKADQKGVTIIGPATVGGIKPGCFKIGNTGGMLDNILASKLYRPGSVAYVSRSGGMSNELNNIISRTTDGVYEGVAIGGDRYPGSTFMDHVLRYQDTPGVKMIVVLGEIGGTEEYKICRGIKEGRLTKPIVCWCIGTCATMFSSEVQFGHAGACANQASETAVAKNQALKEAGVFVPRSFDELGEIIQSVYEDLVANGVIVPAQEVPPPTVPMDYSWARELGLIRKPASFMTSICDERGQELIYAGMPITEVFKEEMGIGGVLGLLWFQKRLPKYSCQFIEMCLMVTADHGPAVSGAHNTIICARAGKDLVSSLTSGLLTIGDRFGGALDAAAKMFSKAFDSGIIPMEFVNKMKKEGKLIMGIGHRVKSINNPDMRVQILKDYVRQHFPATPLLDYALEVEKITTSKKPNLILNVDGLIGVAFVDMLRNCGSFTREEADEYIDIGALNGIFVLGRSMGFIGHYLDQKRLKQGLYRHPWDDISYVLPEHMSMKLAAALEHHHHHHHH',
 ('4a79',
  '1'): 'MSNKCDVVVVGGGISGMAAAKLLHDSGLNVVVLEARDRVGGRTYTLRNQKVKYVDLGGSYVGPTQNRILRLAKELGLETYKVNEVERLIHHVKGKSYPFRGPFPPVWNPITYLDHNNFWRTMDDMGREIPSDAPWKAPLAEEWDNMTMKELLDKLCWTESAKQLATLFVNLCVTAETHEVSALWFLWYVKQCGGTTRIISTTNGGQERKFVGGSGQVSERIMDLLGDRVKLERPVIYIDQTRENVLVETLNHEMYEAKYVISAIPPTLGMKIHFNPPLPMMRNQMITRVPLGSVIKCIVYYKEPFWRKKDYCGTMIIDGEEAPVAYTLDDTKPEGNYAAIMGFILAHKARKLARLTKEERLKKLCELYAKVLGSLEALEPVHYEEKNWCEEQYSGGCYTTYFPPGILTQYGRVLRQPVDRIYFAGTETATHWSGYMEGAVEAGERAAREILHAMGKIPEDEIWQSEPESVDVPAQPITTTFLERHLPSVPGLLRLIGLTTIFSATALGFLAHKRGLLVRV',
 ('3dc2',

# Embeddings

In [9]:
embeddings_path = "5.Embeddings"
os.makedirs(f"{embeddings_path}", exist_ok=True)

In [11]:
seq_embsf = f"{embeddings_path}/seq_embeddings.pkl"

if not os.path.isfile(seq_embsf):
    from utils.embeddings import get_embs
    
    seq_embsd = {}
    for (pdb, entity_id), seq in tqdm(seqs.items(), smoothing=0):
        if pdb not in seq_embsd:
            seq_embsd[pdb] = {}
        seq_embsd[pdb][entity_id] = {
            "seq": seq,
            "embs": get_embs(seq)
        }
        
    with open(seq_embsf, "wb") as f:
        pickle.dump(seq_embsd, f)
else:
    with open(seq_embsf, "rb") as f:
        seq_embsd = pickle.load(f)

len(seq_embsd), seq_embsd

Some weights of EsmModel were not initialized from the model checkpoint at /data/fnerin/huggingface/hub/models--facebook--esm2_t33_650M_UR50D/snapshots/08e4846e537177426273712802403f7ba8261b6c and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  0%|          | 0/309 [00:00<?, ?it/s]

(289,
 {'5kwj': {'1': {'seq': 'MFSRPGLPVEYLQVPSASMGRDIKVQFQGGGPHAVYLLDGLRAQDDYNGWDINTPAFEEYYQSGLSVIMPVGGQSSFYTDWYQPSQSNGQNYTYKWETFLTREMPAWLQANKGVSPTGNAAVGLSMSGGSALILAAYYPQQFPYAASLSGFLNPSEGWWPTLIGLAMNDSGGYNANSMWGPSSDPAWKRNDPMVQIPRLVANNTRIWVYCGNGTPSDLGGDNIPAKFLEGLTLRTNQTFRDTYAADGGRNGVFNFPPNGTHSWPYWNEQLVAMKADIQHVLNGATPPAAPAAPAALEHHHHHH',
    'embs': array([[ 0.18417343,  0.04812526, -0.1441038 , ..., -0.01353498,
             0.18469599, -0.00558302],
           [ 0.10449459,  0.01706475, -0.01919748, ..., -0.1006778 ,
             0.2963119 ,  0.03123129],
           [ 0.02207799,  0.20550573,  0.03463919, ..., -0.04366823,
             0.09699859,  0.12048241],
           ...,
           [ 0.10153432,  0.14793044, -0.05333032, ..., -0.32693347,
             0.25719202, -0.20861787],
           [ 0.13853206,  0.12871557, -0.07205319, ..., -0.22483717,
             0.18781076, -0.2513377 ],
           [ 0.12047419,  0.05020089, -0.16103242, ..., -0.2516187 ,
             0.26720938, -0.25230533]], dtype=float32)}},
  '6t4k': {'1': {'seq': 'GSSHHHHHHSSGLVPRGSHMASLTEIEHLVQSVCKSYRETCQLRLEDLLRQRSNIFSREEVTGYQRKSMWEMWERCAHHLTEAIQYVVEFAKRLSGFMELCQNDQIVLLKAGAMEVVLVRMCRAYNADNRTVFFEGKYGGMELFRALGCSELISSIFDFSHSLSALHFSEDEIALYTALVLINAHRPGLQEKRKVEQLQYNLELAFHHHLHKTHRQSILAKLPPKGKLRSLCSQHVERLQIFQHLHPIVVQAAFPPLYKELFS',
    'embs': array([[-0.05022566,  0.00464323, -0.05271097, ..., -0.05961408,
             0.16603597, -0.2165339 ],
           [-0.07892381,  0.15397482,  0.06569505, ..., -0.10001718,
             0.07935843, -0.36343187],
           [-0.11425527,  0.20828332,  0.10045308, ..., -0.3391603 ,
            -0.01309798, -0.32605067],
           ...,
           [ 0.0210827 ,  0.03423563,  0.05018219, ..., -0.18179715,
            -0.02466949, -0.19794793],
           [-0.102355  ,  0.15438424,  0.10153475, ..., -0.02846551,
            -0.20967495, -0.17931393],
           [-0.0381195 ,  0.0151472 ,  0.02690992, ..., -0.18015428,
            -0.21843334, -0.18529603]], dtype=float32)}},
  '5mo6': {'1': {'seq': 'GSMDIEFDDDADDDGSGSGSGSGSSGPVPSRARVYTDVNTHRPSEYWDYESHVVEWGNQDDYQLVRKLGRGKYSEVFEAINITNNEKVVVKILKPVKKKKIKREIKILENLRGGPNIITLADIVKDPVSRTPALVFEHVNNTDFKQLYQTLTDYDIRFYMYEILKALDYCHSMGIMHRDVKPHNVMIDHEHRKLRLIDWGLAEFYHPGQEYNVRVASRYFKGPELLVDYQMYDYSLDMWSLGCMLASMIFRKEPFFHGHDNYDQLVRIAKVLGTEDLYDYIDKYNIELDPRFNDILGRHSRKRWERFVHSENQHLVSPEALDFLDKLLRYDHQSRLTAREAMEHPYFYTVVK',
    'embs': array([[-0.03256472, -0.04094841,  0.01243429, ...,  0.05141609,
            -0.02302462,  0.09287293],
           [-0.0372244 ,  0.22799626,  0.1733767 , ...,  0.07829349,
            -0.1270478 ,  0.04372943],
           [ 0.02120592,  0.0384557 ,  0.21494304, ...,  0.05721167,
            -0.01345447, -0.02664408],
           ...,
           [-0.09602251,  0.72173905, -0.1199509 , ..., -0.0595712 ,
            -0.24512506,  0.35197297],
           [ 0.00817823,  0.5060994 ,  0.09516577, ..., -0.2519729 ,
            -0.3406878 ,  0.12903804],
           [-0.00711487, -0.02277059,  0.04676111, ..., -0.3621288 ,
            -0.19171166, -0.0305845 ]], dtype=float32)}},
  '3o0n': {'1': {'seq': 'MKLSDLISRWIDVEPSKNAQIILRDRYFMKDLDGNYLETKWEDVARRVARVVATAELLNPSYKKNEKLDRIKEWEDIFFRVLKARLFIPNSPTLFNAGLGVKHDLLWKPIDQMTLEDYEEIYRSRNHLHMLSACFVVPVGDSIEEIFEAVKEYALITKVGGGVGSNFSELRPKGSFVAGTHGKASGPVSFMHVFNSAISVVKQGSRRRGALMGILNINHPDIEEFIDAKKENTGEAVLNFFNLSVGFPMDKKEILKLYEEDGELELSHPRSTIRKKVKIRELFRKIATNAWKSGDPGLAFLGEMNKYYPLYPHRKINSTNPCGEIGLSDYEACNLGSIDVAKFYNNGFVDLEALQELVQIAVRFLDNVIDVNVFPIDKITKAVKESRRLGLGIMGFADLLYKLEIPYNSQEARDFAANLMAFIALHAHRTSYELGKEKGNFPLLEISRYRTEDNFVPFAMGMSNYDDEIREVMKMTKEFRRNVALLTIAPTGSISNIADTSSGLEPNFLLAYTRFVTKEDGTKEPLLYVNQVLREKLNPEILKRIEKELIEKGSLKDIPDVPEKIKKVFVVALDIDPMDHLLMQDAFQRYVDNNISKTINMPQSATVDDVLNVYLEALRTNVRGITVYRDGSLQTQVLTKALKT',
    'embs': array([[ 0.11840337, -0.04819468, -0.05327358, ...,  0.00135201,
            -0.05620026,  0.10956495],
           [ 0.00680723,  0.05546908, -0.22489642, ..., -0.11199276,
             0.01490266, -0.18329045],
           [ 0.0552398 , -0.17644997,  0.2170969 , ..., -0.2143227 ,
             0.07950651, -0.30873987],
           ...,
           [ 0.04314756, -0.0857317 ,  0.02192926, ..., -0.04406473,
             0.31613773, -0.06571098],
           [-0.00755434, -0.08224362,  0.04243203, ..., -0.17841738,
             0.07963101, -0.01692785],
           [ 0.10727071, -0.3348191 , -0.05709238, ..., -0.16491206,
             0.04530674,  0.06011502]], dtype=float32)}},
  '1tjp': {'1': {'seq': 'MERYENLFAQLNDRREGAFVPFVTLGDPGIEQSLKIIDTLIDAGADALELGVPFSDPLADGPTIQNANLRAFAAGVTPAQCFEMLALIREKHPTIPIGLLMYANLVFNNGIDAFYARCEQVGVDSVLVADVPVEESAPFRQAALRHNIAPIFICPPNADDDLLRQVASYGRGYTYLLSRSGVTGAENRGALPLHHLIEKLKEYHAAPALQGFGISSPEQVSAAVRAGAAGAISGSAIVKIIEKNLASPKQMLAELRSFVSAMKAASRA',
    'embs': array([[ 0.03990911,  0.04152876,  0.01678002, ...,  0.08100956,
            -0.0302621 ,  0.5095029 ],
           [ 0.23530263,  0.00873391, -0.17934358, ..., -0.02754108,
            -0.01404755,  0.05061633],
           [ 0.23731935,  0.1281233 ,  0.18580346, ..., -0.12989333,
             0.32787776,  0.27679485],
           ...,
           [-0.0361486 , -0.01597631,  0.02448813, ...,  0.06195386,
            -0.36096317, -0.01989157],
           [-0.09798969,  0.19389582, -0.10134692, ..., -0.26566198,
            -0.10204918,  0.0416946 ],
           [-0.15575671,  0.12252089, -0.15951051, ..., -0.33527723,
            -0.17256978,  0.15621157]], dtype=float32)}},
  '4bqh': {'1': {'seq': 'PLGSMSDRDVCIQRLTGANQDHILTALEHGSEAERASLTAQITNELAGVDFRHFNDVLRESLEISKNCSTASLAEPPAKDSFFDISSVDRRRGQAKRIKNLEAVGYKAIQKGQIAFLILAGGSGTRLGFDKPKGFFTCDGLQQRKSLFMMHCEKIRRRQEIAESISGSGRKARVQLLVMTSGQNDAETQRFFEENSYFGLEREQVHFFAQSSVPCYDENTGRIIMENRGRICAAPGGNGAVFAALAAPRATKDKDGTLQVKESLLQHLRKLGIAYVQIGNIDNLLANVADPVFIGYAIEEEAHVVVKTCPKRGPDERVGVFVRASGKWGVVEYTEIGDRAKEIDDATGELKFNCANISSNLCSLHFMSLAAERMKSFTQYHAARKKIPTIKGPVMGIKLEAFLFDLFRFVDECDHPPKDSGAFRIMQVDRDDEFGPVKNADGAASDTPADAVRLLLSQHTRWLITALETAAMSDEQESIRGGVDVTEAKEAVAVMRSCSIKAEISPLVSVGGEGLRQHLPRVIHQLLRNPPPVIFIRRDDEVVSESSNM',
    'embs': array([[ 0.0338076 , -0.01597951,  0.10620244, ...,  0.21352594,
             0.12762754,  0.2776771 ],
           [-0.03873342,  0.05009617,  0.30206656, ...,  0.11854771,
             0.22099288,  0.23913774],
           [-0.07457758, -0.0156092 ,  0.35632327, ...,  0.08023805,
             0.1475975 ,  0.09976787],
           ...,
           [-0.02876813,  0.06002466,  0.09863747, ..., -0.15875933,
            -0.03964984, -0.01604602],
           [-0.01790484, -0.00697967,  0.13981467, ..., -0.2507496 ,
             0.05078673,  0.16040377],
           [ 0.14662042, -0.16782285,  0.06469613, ..., -0.27346042,
             0.12723656,  0.29055166]], dtype=float32)}},
  '1og0': {'1': {'seq': 'MSESPMFAANGMPKVNQGAEEDVRILGYDPLASPALLQVQIPATPTSLETAKRGRREAIDIITGKDDRVLVIVGPCSIHDLEAAQEYALRLKKLSDELKGDLSIIMRAYLEKPRTTVGWKGLINDPDVNNTFNINKGLQSARQLFVNLTNIGLPIGSEMLDTISPQYLADLVSFGAIGARTTESQLHRELASGLSFPVGFKNGTDGTLNVAVDACQAAAHSHHFMSVTKHGVAAITTTKGNEHCFVILRGGKKGTNYDAKSVAEAKAQLPAGSNGLMIDYSHGNSNKDFRNQPKVNDVVCEQIANGENAITGVMIESNINEGNQGIPAEGKAGLKYGVSITDACIGWETTEDVLRKLAAAVRQRREVNKK',
    'embs': array([[ 0.18803935, -0.05921668, -0.05974833, ..., -0.15166555,
             0.02326737,  0.0314547 ],
           [ 0.12585948,  0.23430195,  0.01081205, ..., -0.18677409,
            -0.14671691, -0.17663251],
           [ 0.10994661,  0.06134479,  0.06412349, ..., -0.3015538 ,
            -0.04110945, -0.20020181],
           ...,
           [-0.08131061, -0.07383262,  0.07459694, ..., -0.13350238,
             0.10930796, -0.08422398],
           [-0.03358147, -0.07516282, -0.07556371, ..., -0.17645368,
             0.01783595, -0.09469806],
           [ 0.08750185, -0.13764273, -0.19075556, ..., -0.12803857,
             0.02991039, -0.06282532]], dtype=float32)}},
  '5jv1': {'1': {'seq': 'MGSSHHHHHHSSGRENLYFQGHMNGDQNSDVYAQEKQDFVQHFSQIVRVLTEDEMGHPEIGDAIARLKEVLEYNAIGGKYNRGLTVVVAFRELVEPRKQDADSLQRAWTVGWCVELLQAFFLVADDIMDSSLTRRGQICWYQKPGVGLDAINDANLLEACIYRLLKLYCREQPYYLNLIELFLQSSYQTEIGQTLDLLTAPQGNVDLVRFTEKRYKSIVKYKTAFYSFYLPIAAAMYMAGIDGEKEHANAKKILLEMGEFFQIQDDYLDLFGDPSVTGKIGTDIQDNKCSWLVVQCLQRATPEQYQILKENYGQKEAEKVARVKALYEELDLPAVFLQYEEDSYSHIMALIEQYAAPLPPAVFLGLARKIYKRRK',
    'embs': array([[ 0.20268394, -0.04914059, -0.09241948, ..., -0.05028065,
            -0.2831    ,  0.00047811],
           [ 0.058341  ,  0.23504509,  0.15434623, ..., -0.08931345,
             0.14722152, -0.21649283],
           [-0.04171041,  0.15895341,  0.09278403, ...,  0.07661244,
            -0.09076609, -0.20200637],
           ...,
           [ 0.06526346,  0.05771045,  0.23012452, ..., -0.3183123 ,
             0.18612409,  0.14631297],
           [-0.04664079, -0.11077438,  0.06387738, ...,  0.0487756 ,
            -0.10762011, -0.3320015 ],
           [-0.05052222,  0.08743127, -0.22722456, ..., -0.1536736 ,
            -0.36256373,  0.01510696]], dtype=float32)}},
  '3auy': {'1': {'seq': 'MSMILKEIRMNNFKSHVNSRIKFEKGIVAIIGENGSGKSSIFEAVFFALFGAGSNFNYDTIITKGKKSVYVELDFEVNGNNYKIIREYDSGRGGAKLYKNGKPYATTISAVNKAVNEILGVDRNMFLNSIYIKQGEIAKFLSLKPSEKLETVAKLLGIDEFEKCYQKMGEIVKEYEKRLERIEGELNYKEESLKARLKEMSNLEKEKEKLTKFVEYLDKVRRIFGRNGFQAYLREKYVPLIQKYLNEAFSEFDLPYSFVELTKDFEVRVHAPNGVLTIDNLSGGEQIAVALSLRLAIANALIGNRVECIILDEPTVYLDENRRAKLAEIFRKVKSIPQMIIITHHRELEDVADVIINVKKDGNVSKVKING',
    'embs': array([[ 0.00919066, -0.10770302,  0.36811686, ...,  0.13537654,
             0.02190482,  0.39084175],
           [ 0.02298051,  0.0953448 ,  0.37863964, ...,  0.1772233 ,
             0.0250355 ,  0.20169751],
           [ 0.10400486, -0.05906349,  0.26539105, ...,  0.02574348,
             0.21113993,  0.01096958],
           ...,
           [-0.10638297, -0.02150956, -0.07184529, ..., -0.30523843,
             0.22907048,  0.35217023],
           [-0.17649488, -0.26446602,  0.37641966, ..., -0.24067284,
            -0.21553683,  0.32753772],
           [-0.04927545, -0.15029602,  0.20192187, ..., -0.277331  ,
            -0.09372545,  0.32453895]], dtype=float32)}},
  '5dl1': {'1': {'seq': 'MNLIPTVIETTNRGERAYDIYSRLLKDRIIMLGSQIDDNVANSIVSQLLFLQAQDSEKDIYLYINSPGGSVTAGFAIYDTIQHIKPDVQTICIGMAASMGSFLLAAGAKGKRFALPNAEVMIHQPLGGAQGQATEIEIAANHILKTREKLNRILSERTGQSIEKIQKDTDRDNFLTAEEAKEYGLIDEVMVPETK',
    'embs': array([[ 0.1545003 , -0.00225445,  0.04466186, ...,  0.20271847,
            -0.04168957,  0.0234068 ],
           [ 0.04225969, -0.02740766,  0.00051302, ..., -0.11845651,
            -0.09572154, -0.02507218],
           [ 0.01346229,  0.01859221,  0.19603853, ...,  0.14433007,
            -0.13215275, -0.10959585],
           ...,
           [ 0.16599813,  0.13374312,  0.11765529, ..., -0.16029733,
             0.05471056,  0.13128385],
           [ 0.14115863,  0.06278326,  0.09568469, ..., -0.12279299,
            -0.11144108, -0.00340994],
           [ 0.01372601,  0.12880936,  0.10059416, ..., -0.24823277,
            -0.11341083,  0.12481952]], dtype=float32)}},
  '1qqb': {'2': {'seq': 'ATIKDVAKRANVSTTTVSHVINKTRFVAEETRNAVWAAIKELHYSPSAVARSLAVNHTKSIGLLATSSEAAYFAEIIEAVEKNCFQKGYTLILGNAWNNLEKQRAYLSMMAQKRVDGLLVMCSEYPEPLLAMLEEYRHIPMVVMDWGEAKADFTDAVIDNAFEGGYMAGRYLIERGHREIGVIPGPLERNTGAGRLAGFMKAMEEAMIKVPESWIVQGDFEPESGYRAMQQILSQPHRPTAVFCGGDIMAMGALCAADEMGLRVPQDVSLIGYDNVRNARYFTPALTTIHQPKDSLGETAFNMLLDRIVNKREEPQSIEVHPRLIERRSVADGPFRDYRR',
    'embs': array([[-0.04378937,  0.0868577 , -0.05149518, ..., -0.13686118,
             0.05322723,  0.12785263],
           [ 0.11748824,  0.21528901, -0.03514149, ..., -0.09409301,
             0.22135487, -0.4012321 ],
           [-0.11252668,  0.03008042,  0.19601147, ..., -0.45982066,
            -0.06745332,  0.0278046 ],
           ...,
           [ 0.07638375, -0.09809148, -0.29227924, ..., -0.34901062,
             0.11554279,  0.03243443],
           [ 0.02549662, -0.00922924,  0.03095191, ..., -0.36447865,
            -0.11676056, -0.00887468],
           [-0.06244883, -0.13008073,  0.0447132 , ..., -0.21837947,
             0.15511593,  0.05473969]], dtype=float32)}},
  '6hgj': {'1': {'seq': 'MKHHHHHHMKQNSPLDEENLTQENQDRGTHVDRGLASANVDFAFSLYKQLVLKAPDKNVIFSPVSISTALAFLSLGAHNTTLTEILKGLKFNLTETSEAEIHQSFQHLLRTLNQSSDELQLSMGNAMFVKEQLSLLDRFTEDAKRLYGSEAFATDFQDSAAAKKLINDYVKNGTRGKITDLIKDLDSQTMMVLVNYIFFKAKWEMPFDPQDTHQSRFYLSKKKWVMVPMMSLHHLTIPYFRDEELSCTVVQLNYTGNASVFFILPDQDKMEEVEAMLSRETLARWGDSLEFREIGELYLPKFSISRDYNLNDILLQLGIEEAFTSKADLSGITGARNLAVSQVVHKAVLDVFEEGTEASAATAVKITLL',
    'embs': array([[ 0.15622197, -0.19275238, -0.05858505, ...,  0.13953151,
             0.01839083, -0.02113099],
           [ 0.0515207 ,  0.19375163,  0.08670235, ..., -0.06820781,
            -0.02628915, -0.1703052 ],
           [ 0.05254672,  0.16291249, -0.02148058, ..., -0.13218513,
             0.07520867, -0.23961091],
           ...,
           [ 0.2117387 ,  0.24434105,  0.08920456, ...,  0.08646254,
            -0.396607  , -0.29650125],
           [ 0.11881635,  0.09409948,  0.2166489 , ...,  0.3648014 ,
            -0.20429042, -0.12732519],
           [ 0.00224044,  0.13998143,  0.0314635 , ...,  0.17844757,
             0.1369925 , -0.19247755]], dtype=float32)},
   '2': {'seq': 'SALVETRTIVRFNRPFLMIIVDHFTWSIFFMSKVTNPKQA',
    'embs': array([[ 0.06834264,  0.06428805,  0.02451335, ...,  0.05661516,
            -0.11028948,  0.01790623],
           [ 0.00445024,  0.04479636, -0.01235074, ..., -0.08952981,
            -0.17043623, -0.02664439],
           [-0.03014441, -0.04931784,  0.1529257 , ...,  0.0264229 ,
             0.03013731, -0.16424832],
           ...,
           [-0.14990762,  0.06686064, -0.28172994, ..., -0.10957032,
            -0.18509984, -0.37493026],
           [ 0.02930532, -0.09890611,  0.09677407, ..., -0.2020525 ,
            -0.04596742, -0.01133479],
           [ 0.04962912, -0.27258027,  0.01111848, ..., -0.24281141,
            -0.11633992,  0.13407339]], dtype=float32)}},
  '4aau': {'1': {'seq': 'MAAKDVKFGNDARVKMLRGVNVLADAVKVTLGPKGRNVVLDKSFGAPTITKDGVSVAREIELEDKFENMGAQMVKEVASKANDAAGDGTTTATVLAQAIITEGLKAVAAGMNPMDLKRGIDKAVTAAVEELKALSVPCSDSKAIAQVGTISANSDETVGKLIAEAMDKVGKEGVITVEDGTGLQDELDVVEGMQFDRGYLSPYFINKPETGAVELESPFILLADKKISNIREMLPVLEAVAKAGKPLLIIAEDVEGEALATLVVNTMRGIVKVAAVKAPGFGDRRKAMLQDIATLTGGTVISEEIGMELEKATLEDLGQAKRVVINKDTTTIIDGVGEEAAIQGRVAQIRQQIEEATSDYDREKLQERVAKLAGGVAVIKVGAATEVEMKEKKARVEAALHATRAAVEEGVVAGGGVALIRVASKLADLRGQNEDQNVGIKVALRAMEAPLRQIVLNCGEEPSVVANTVKGGDGNYGYNAATEEYGNMIDMGILDPTKVTRSALQYAASVAGLMITTECMVTDLPKNDAADLGAAGGMGGMGGMGGMM',
    'embs': array([[ 4.68128212e-02, -4.98216450e-02, -3.12028365e-04, ...,
            -8.37558582e-02,  1.10096134e-01,  2.57288754e-01],
           [-5.06345667e-02,  1.76587701e-01,  2.30018720e-02, ...,
            -1.85137302e-01,  2.73711175e-01, -1.08222082e-01],
           [-2.16725200e-01,  1.08510427e-01,  6.39138669e-02, ...,
             1.63602605e-02,  7.74024636e-04, -1.20380647e-01],
           ...,
           [-1.98643096e-02, -1.85844481e-01, -1.15101486e-01, ...,
            -1.37839779e-01, -2.60720290e-02,  1.39640033e-01],
           [ 2.01324280e-02, -3.13114911e-01, -6.33573234e-02, ...,
             1.27622951e-02, -1.51411012e-01,  1.71446696e-01],
           [-2.86180358e-02, -3.07470858e-01, -5.80737181e-02, ...,
            -1.28261354e-02, -3.25075574e-02,  1.00270823e-01]], dtype=float32)}},
  '6nzf': {'1': {'seq': 'MGSSHHHHHHSSGETVRFQGHMNLSQLSFHRVDQKEITQLSHLGQGTRTNVYEGRLRVEGSGDPEEGKMDDEDPLVPGRDRGQELRVVLKVLDPSHHDIALAFYETASLMSQVSHTHLAFVHGVCVRGPENIMVTEYVEHGPLDVWLRRERGHVPMAWKMVVAQQLASALSYLENKNLVHGNVCGRNILLARLGLAEGTSPFIKLSDPGVGLGALSREERVERIPWLAPECLPGGANSLSTAMDKWGFGATLLEICFDGEAPLQSRSPSEKEHFYQRQHRLPEPSCPQLATLTSQCLTYEPTQRPSFRTILRDLTRL',
    'embs': array([[-1.72248930e-02, -8.94592702e-02, -1.13363795e-01, ...,
             2.04115268e-03, -2.72213365e-04,  4.87684011e-02],
           [-1.06359787e-01,  8.36284384e-02, -7.27009866e-03, ...,
            -2.80045159e-02,  1.79314181e-01, -1.73246056e-01],
           [-1.60684153e-01,  1.04566731e-01, -4.45761643e-02, ...,
             5.30421361e-02, -1.23213187e-01, -3.10730219e-01],
           ...,
           [-7.00540990e-02,  1.14946045e-01, -2.22860258e-02, ...,
             5.83783165e-02,  8.41628537e-02, -1.01791091e-01],
           [ 1.27738997e-01,  3.77241038e-02, -4.49275784e-02, ...,
            -3.19091044e-02,  5.96019849e-02, -2.35080764e-01],
           [-2.68302076e-02,  1.21177845e-01,  7.16120526e-02, ...,
            -6.01479076e-02, -5.00532687e-02, -8.98188576e-02]], dtype=float32)}},
  '5uyy': {'1': {'seq': 'SNAMKIKKESLEMRQMRKKVVLIGTGLIGGSLALAIKKDHDVTITGYDIFQEQVERAKELHVVDEIAVDLQHACEEAHLIVFASPVEETKKLLHKLASFHLREDVIVTDVGSTKGSIMNEAEALFSKEISFIGGHPMAGSHKTGVESAKAHLFENAFYILTPMHHVPNEHVEELKDWLKGTGSHFLVLNTEEHDYVTGIVSHFPHLIAAGLVKQVEKHAGDNPLIHQLAAGGFKDITRIASSSPKMWSDIVKQNREHLMVLLKEWISEMEDLYDTVSSGDAGEIQNYFADAKEYRDSLPVRKRGAIPAYHDLYVDVLDKVGALAHVTSILAREEISITNLQILEAREGLLGVLRISFQREEDRMKAKLALGEEKYQTYETI',
    'embs': array([[-0.16154817, -0.18835232, -0.01961137, ...,  0.02545073,
            -0.11033222, -0.03959626],
           [ 0.06888758, -0.187533  ,  0.14927055, ..., -0.11176212,
             0.03580638,  0.2341437 ],
           [-0.09599364, -0.00777957, -0.09976618, ..., -0.16088867,
            -0.06520531,  0.23557982],
           ...,
           [-0.1304256 ,  0.09952199, -0.0263995 , ..., -0.1822542 ,
            -0.13077155,  0.24108373],
           [-0.15069172,  0.1469611 , -0.05697738, ..., -0.02181488,
            -0.32588172,  0.11279528],
           [ 0.00484913,  0.08123495, -0.03795885, ..., -0.1932091 ,
             0.04300925,  0.1774993 ]], dtype=float32)}},
  '5xez': {'1': {'seq': 'GAPQVMDFLFEKWKLYGDQCHHNLSLLPPPTELVCNRTFDKYSCWPDTPANTTANISCPWYLPWHHKVQHRFVFKRCGPDGQWVRGPRGQPWRDASQCQMDGEEIEVQKEVAKMYSSFQVMYTVGYSLSLGALLLALAILGGLSKLHCTRNAIHANLFASFVLKASSVLVIDGLLRTRYSQKIGDDLSVSTWLSDGAVAGCRVAAVFMQYGIVANYCWLLVEGLYLHNLLGLANIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYERSFFSLYLGIGWGAPMLFVVPWAVVKCLFENVQCWTSNDNMGFWWILRFPVFLAILINFFIFVRIVQLLVAKLRARQMHHTDYKFRLAKSTLTLIPLLGVHEVVFAFVTDEHAQGTLRSAKLFFDLFLSSFQGLLVAVLYCFLNKEVQSELRRRWHRWRLGKVLWEERNTSNEFLEVLFQ',
    'embs': array([[ 0.07460373,  0.02365066,  0.06147556, ...,  0.01073115,
            -0.04725887,  0.06663882],
           [-0.01158915,  0.08093478,  0.00907792, ..., -0.07759216,
             0.04746071,  0.06348999],
           [ 0.05511327, -0.06478956,  0.03223532, ..., -0.08341215,
             0.08494908,  0.14289421],
           ...,
           [ 0.06031283,  0.042623  ,  0.25893906, ...,  0.1473    ,
            -0.00979928,  0.21432021],
           [ 0.25583598,  0.06417084,  0.20213671, ..., -0.00296763,
            -0.06234579,  0.284699  ],
           [ 0.21504581,  0.01063976,  0.30016047, ...,  0.02122675,
            -0.08366606,  0.37297937]], dtype=float32)}},
  '2b08': {'1': {'seq': 'VRKATAAEIAALPRQKVELVDPPFVHAHSQVAEGGPKVVEFTMVIEEKKIVIDDAGTEVHAMAFNGTVPGPLMVVHQDDYLELTLINPETNTLMHNIDFHAATGALGGGGLTEINPGEKTILRFKATKPGVFVYHCAPPGMVPWHVVSGGNGAIMVLPREGLHDGKGKALTYDKIYYVGEQDFYVPRDENGKYKKYEAPGDAYEDTVKVMRTLTPTHVVFNGAVGALTGDKAMTAAVGEKVLIVHSQANRDTRPHLIGGHGDYVWATGKFNTPPDVDQETWFIPGGAAGAAFYTFQQPGIYAYVNHNLIEAFELGAAAHFKVTGEWNDDLMTSVLAPSGT',
    'embs': array([[ 0.1287552 ,  0.11467387, -0.3220132 , ..., -0.10484678,
             0.19992897, -0.07541192],
           [ 0.22873838,  0.23082927,  0.03114377, ..., -0.24738169,
             0.34968045, -0.08271698],
           [-0.08588688,  0.1702975 , -0.12671413, ..., -0.18938918,
            -0.02482803,  0.12026711],
           ...,
           [ 0.06366716,  0.04660638,  0.04717203, ..., -0.23237658,
            -0.08382777,  0.02587971],
           [ 0.11117414, -0.03501214,  0.00090871, ..., -0.22753036,
             0.23360726, -0.05226801],
           [-0.03675588,  0.05730869,  0.06990755, ...,  0.0187913 ,
             0.08217223,  0.03595689]], dtype=float32)}},

In [12]:
embsf = f"{embeddings_path}/embeddings.pkl"

if not os.path.isfile(embsf):
    embsd = {}
    for pdb, embs in tqdm(seq_embsd.items(), smoothing=0):
        residues = featuresd[pdb][["Residues", "Label"]]

        embsd[pdb] = residues.merge(
            pd.concat((
                pd.concat(
                    (
                        pd.Series([entity_id]*len(entd["seq"]), name="label_entity_id"),
                        pd.Series(range(1, len(entd["seq"])+1), name="label_seq_id", dtype=str),
                        pd.DataFrame(entd["embs"])
                    ),
                    axis=1,
                    keys=["Residues", "Residues", "Embeddings"]
                )
                for entity_id, entd in embs.items()
            )),
            on=[("Residues", "label_entity_id"), ("Residues", "label_seq_id")]
        )
        
    with open(embsf, "wb") as f:
        pickle.dump(embsd, f)
else:
    with open(embsf, "rb") as f:
        embsd = pickle.load(f)

len(embsd), embsd

  0%|          | 0/289 [00:00<?, ?it/s]

(289,
 {'5kwj':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       5kwj               1             B            1            B
  1       5kwj               1             B            2            B
  2       5kwj               1             B            3            B
  3       5kwj               1             B            4            B
  4       5kwj               1             B            5            B
  ..       ...             ...           ...          ...          ...
  278     5kwj               1             B          279            B
  279     5kwj               1             B          280            B
  280     5kwj               1             B          281            B
  281     5kwj               1             B          282            B
  282     5kwj               1             B          283            B

                                    Label Embeddings            ...            \
      auth_seq_id pdbx_PDB_ins_code label          0         1  ...      1270
  0             0                 ?     0   0.184173  0.048125  ... -0.085978
  1             1                 ?     0   0.104495  0.017065  ...  0.037607
  2             2                 ?     0   0.022078  0.205506  ...  0.157536
  3             3                 ?     0   0.056580 -0.001172  ...  0.212179
  4             4                 ?     0   0.043849  0.076100  ...  0.194452
  ..          ...               ...   ...        ...       ...  ...       ...
  278         278                 ?     0   0.050254 -0.012283  ...  0.062315
  279         279                 ?     0  -0.093743  0.171124  ... -0.080088
  280         280                 ?     0  -0.076929 -0.110003  ...  0.128526
  281         281                 ?     0  -0.049600 -0.114944  ... -0.052836
  282         282                 ?     0   0.031759 -0.232070  ... -0.093646

                                                                             \
           1271      1272      1273      1274      1275      1276      1277
  0   -0.035533  0.273888 -0.145220 -0.070819  0.149617 -0.120941 -0.013535
  1   -0.001185  0.259336 -0.164723 -0.017318  0.219524  0.178434 -0.100678
  2   -0.154936  0.216812 -0.168006 -0.229779 -0.120800 -0.004415 -0.043668
  3   -0.026253  0.110860 -0.237103 -0.055452  0.009461  0.047359 -0.222671
  4   -0.011380  0.033394 -0.080930 -0.049818  0.001425  0.100357 -0.051336
  ..        ...       ...       ...       ...       ...       ...       ...
  278 -0.109034  0.064885 -0.149680 -0.110541 -0.010822  0.235821 -0.187398
  279 -0.068829  0.090931 -0.055361  0.195146  0.169358 -0.128870 -0.062076
  280 -0.087397 -0.053044  0.163106  0.170140  0.110110  0.159810  0.126292
  281 -0.091309 -0.139575 -0.168461 -0.001103 -0.051172 -0.104846 -0.081174
  282 -0.109437 -0.065392 -0.080037 -0.097302 -0.238578 -0.082852 -0.144721


           1278      1279
  0    0.184696 -0.005583
  1    0.296312  0.031231
  2    0.096999  0.120482
  3    0.227664  0.047352
  4    0.224424  0.167305
  ..        ...       ...
  278  0.264522  0.067330
  279 -0.187638  0.309782
  280 -0.091237  0.201407
  281  0.266199  0.127383
  282  0.153173  0.059676

  [283 rows x 1288 columns],
  '6t4k':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6t4k               1             A           23            A
  1       6t4k               1             A           24            A
  2       6t4k               1             A           25            A
  3       6t4k               1             A           26            A
  4       6t4k               1             A           27            A
  ..       ...             ...           ...          ...          ...
  235     6t4k               1             A          259            A
  236     6t4k               1             A          260            A
  237     6t4k               1             A          261            A
  238     6t4k               1             A          262            A
  239     6t4k               1             A          263            A

                                    Label Embeddings            ...            \
      auth_seq_id pdbx_PDB_ins_code label          0         1  ...      1270
  0           267                 ?     0   0.099252  0.007252  ... -0.096803
  1           268                 ?     0  -0.134447  0.053504  ... -0.046794
  2           269                 ?     0   0.147028 -0.169652  ... -0.081408
  3           270                 ?     0   0.059396 -0.180247  ...  0.128587
  4           271                 ?     0   0.188011 -0.119639  ... -0.131010
  ..          ...               ...   ...        ...       ...  ...       ...
  235         503                 ?     0  -0.043723  0.114913  ...  0.040210
  236         504                 ?     0   0.214561 -0.181459  ...  0.059544
  237         505                 ?     0   0.021083  0.034236  ... -0.132878
  238         506                 ?     0  -0.102355  0.154384  ... -0.218332
  239         507                 ?     0  -0.038120  0.015147  ...  0.215212

                                                                             \
           1271      1272      1273      1274      1275      1276      1277
  0    0.304380 -0.297928  0.069414  0.119476 -0.068614 -0.194068 -0.129667
  1    0.167820 -0.103896  0.071061  0.059016 -0.161960 -0.271770 -0.008449
  2    0.191023 -0.081801 -0.041135  0.094990 -0.011675 -0.011701 -0.100773
  3    0.123289 -0.024608 -0.029216  0.062748 -0.236842 -0.227073 -0.247663
  4    0.095343 -0.235770 -0.075798 -0.048793  0.237500 -0.047721 -0.281672
  ..        ...       ...       ...       ...       ...       ...       ...
  235 -0.101398 -0.095828 -0.041458  0.261322  0.040135  0.182011 -0.081793
  236  0.010193 -0.369538  0.064568  0.344803  0.100489  0.010212 -0.168918
  237  0.018680 -0.325502  0.143240  0.131814 -0.057998  0.061734 -0.181797
  238 -0.006426 -0.108827  0.069342 -0.085211  0.038132  0.333222 -0.028466
  239 -0.134520 -0.166083 -0.072633 -0.089965  0.086012  0.176983 -0.180154


           1278      1279
  0    0.156195 -0.210385
  1    0.148239  0.015945
  2    0.262904  0.026753
  3    0.247761 -0.131018
  4    0.063687 -0.076489
  ..        ...       ...
  235 -0.328696 -0.185803
  236 -0.069955  0.134789
  237 -0.024669 -0.197948
  238 -0.209675 -0.179314
  239 -0.218433 -0.185296

  [240 rows x 1288 columns],
  '5mo6':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       5mo6               1             B           26            A
  1       5mo6               1             B           27            A
  2       5mo6               1             B           28            A
  3       5mo6               1             B           29            A
  4       5mo6               1             B           30            A
  ..       ...             ...           ...          ...          ...
  320     5mo6               1             B          346            A
  321     5mo6               1             B          347            A
  322     5mo6               1             B          348            A
  323     5mo6               1             B          349            A
  324     5mo6               1             B          350            A

                                    Label Embeddings            ...            \
      auth_seq_id pdbx_PDB_ins_code label          0         1  ...      1270
  0             3                 ?     0  -0.072466  0.000212  ... -0.100460
  1             4                 ?     0  -0.121678  0.010224  ...  0.082768
  2             5                 ?     0  -0.160319 -0.056245  ... -0.081003
  3             6                 ?     0  -0.242192 -0.054560  ...  0.084386
  4             7                 ?     0  -0.126647  0.176056  ...  0.070786
  ..          ...               ...   ...        ...       ...  ...       ...
  320         323                 ?     0  -0.235596  0.332376  ...  0.006308
  321         324                 ?     0  -0.011012  0.343822  ... -0.142096
  322         325                 ?     0   0.052315  0.274001  ...  0.116743
  323         326                 ?     0   0.166880  0.566835  ...  0.207325
  324         327                 ?     0  -0.096023  0.721739  ... -0.013523

                                                                             \
           1271      1272      1273      1274      1275      1276      1277
  0    0.054437  0.053402 -0.151595 -0.027799 -0.116169 -0.235598 -0.173679
  1   -0.000028 -0.034951  0.046945  0.049413 -0.120005 -0.192603 -0.253222
  2   -0.057822 -0.009795 -0.136633  0.114840 -0.112905 -0.074867 -0.317670
  3    0.026540  0.125736 -0.023391  0.164781 -0.267482 -0.049025 -0.283118
  4    0.034144  0.089781 -0.093103 -0.070485 -0.516849 -0.159556 -0.243256
  ..        ...       ...       ...       ...       ...       ...       ...
  320 -0.202055  0.069609  0.336118 -0.057466  0.366379  0.009294 -0.351399
  321  0.013980 -0.193961  0.170584  0.152398 -0.019101  0.400800 -0.185747
  322 -0.168350 -0.215953  0.328139 -0.090539  0.432330  0.010236 -0.083895
  323 -0.040283  0.139845  0.474265 -0.019696  0.293755 -0.267712  0.002187
  324 -0.223300 -0.228903  0.154682  0.174566  0.082369 -0.256523 -0.059571


           1278      1279
  0    0.093917  0.030486
  1    0.083614  0.101755
  2    0.056602  0.109850
  3    0.091916  0.094928
  4   -0.145976  0.055669
  ..        ...       ...
  320  0.240793 -0.109829
  321  0.078067 -0.238332
  322  0.165836 -0.272214
  323 -0.431244  0.238744
  324 -0.245125  0.351973

  [325 rows x 1288 columns],
  '3o0n':      Residues                                                          \
            pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0        3o0n               1             A            1            A
  1        3o0n               1             A            2            A
  2        3o0n               1             A            3            A
  3        3o0n               1             A            4            A
  4        3o0n               1             A            5            A
  ...       ...             ...           ...          ...          ...
  1213     3o0n               1             B          629            B
  1214     3o0n               1             B          630            B
  1215     3o0n               1             B          631            B
  1216     3o0n               1             B          632            B
  1217     3o0n               1             B          633            B

                                     Label Embeddings            ...            \
       auth_seq_id pdbx_PDB_ins_code label          0         1  ...      1270
  0              1                 ?     0   0.118403 -0.048195  ... -0.035206
  1              2                 ?     0   0.006807  0.055469  ...  0.045576
  2              3                 ?     0   0.055240 -0.176450  ...  0.091962
  3              4                 ?     0   0.099220 -0.126839  ... -0.154717
  4              5                 ?     0   0.154025 -0.096247  ... -0.096234
  ...          ...               ...   ...        ...       ...  ...       ...
  1213         629                 ?     0   0.180971 -0.101782  ...  0.031439
  1214         630                 ?     0   0.134597 -0.275595  ...  0.173937
  1215         631                 ?     0   0.249681 -0.153519  ...  0.109570
  1216         632                 ?     0   0.116536 -0.213485  ... -0.125510
  1217         633                 ?     0   0.240832 -0.198791  ...  0.201971

                                                                              \
            1271      1272      1273      1274      1275      1276      1277
  0     0.080012  0.064906  0.258460  0.127580  0.131964  0.236070  0.001352
  1     0.068737  0.038954  0.058859 -0.026725 -0.038015  0.464647 -0.111993
  2     0.116737 -0.219609  0.095742  0.250057 -0.129327  0.263646 -0.214323
  3     0.099947 -0.306663  0.341363 -0.091065 -0.224286 -0.038098 -0.121899
  4     0.079586 -0.204346  0.236800  0.087202  0.219031  0.106681 -0.093858
  ...        ...       ...       ...       ...       ...       ...       ...
  1213 -0.228125 -0.452990  0.131979  0.147176 -0.187038  0.291043 -0.212244
  1214  0.062676 -0.062871 -0.022434  0.174281 -0.188539  0.386317 -0.086889
  1215 -0.024232 -0.466763 -0.047978  0.125994 -0.495073  0.233652 -0.357766
  1216 -0.072531 -0.014134  0.212811  0.042699 -0.354097  0.265418  0.001544
  1217 -0.321884 -0.153093  0.229098  0.350392 -0.202466  0.398387  0.024560


            1278      1279
  0    -0.056200  0.109565
  1     0.014903 -0.183290
  2     0.079507 -0.308740
  3    -0.312974 -0.020489
  4     0.017746 -0.289682
  ...        ...       ...
  1213  0.074287  0.133361
  1214  0.182087  0.363295
  1215  0.278047 -0.247660
  1216 -0.285674 -0.135504
  1217  0.152958 -0.256851

  [1218 rows x 1288 columns],
  '1tjp':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       1tjp               1             A            1            A
  1       1tjp               1             A            2            A
  2       1tjp               1             A            3            A
  3       1tjp               1             A            4            A
  4       1tjp               1             A            5            A
  ..       ...             ...           ...          ...          ...
  262     1tjp               1             A          263            A
  263     1tjp               1             A          264            A
  264     1tjp               1             A          265            A
  265     1tjp               1             A          266            A
  266     1tjp               1             A          267            A

                                    Label Embeddings            ...            \
      auth_seq_id pdbx_PDB_ins_code label          0         1  ...      1270
  0             1                 ?     0   0.039909  0.041529  ... -0.139215
  1             2                 ?     0   0.235303  0.008734  ...  0.164858
  2             3                 ?     0   0.237319  0.128123  ...  0.073485
  3             4                 ?     0  -0.131838 -0.127191  ... -0.039355
  4             5                 ?     0  -0.107523 -0.261756  ...  0.232133
  ..          ...               ...   ...        ...       ...  ...       ...
  262         263                 ?     0   0.051588  0.121482  ... -0.316051
  263         264                 ?     0   0.018062  0.133994  ...  0.130594
  264         265                 ?     0  -0.041326  0.097786  ...  0.019707
  265         266                 ?     0  -0.036149 -0.015976  ... -0.375264
  266         267                 ?     0  -0.097990  0.193896  ...  0.008217

                                                                             \
           1271      1272      1273      1274      1275      1276      1277
  0    0.132978 -0.046135  0.095153  0.078751  0.057499 -0.218040  0.081010
  1    0.076720  0.057197 -0.006391 -0.326875 -0.163960  0.068923 -0.027541
  2   -0.048282 -0.279090  0.096200 -0.092062 -0.359672  0.261927 -0.129893
  3    0.116364 -0.042840 -0.100781 -0.252461  0.181878 -0.025581 -0.220466
  4    0.042267  0.204193 -0.011032 -0.236478  0.063733  0.023199  0.128934
  ..        ...       ...       ...       ...       ...       ...       ...
  262 -0.018914 -0.246658  0.041017  0.258804 -0.478978  0.210261 -0.220924
  263 -0.127302  0.009081 -0.018076 -0.130772 -0.065111 -0.049134 -0.139363
  264 -0.183775 -0.104145  0.134011  0.270155  0.093170 -0.038277 -0.048682
  265 -0.151713  0.297337 -0.055961 -0.000014  0.172118 -0.022683  0.061954
  266 -0.107879 -0.243035 -0.116170 -0.107480 -0.027503  0.147205 -0.265662


           1278      1279
  0   -0.030262  0.509503
  1   -0.014048  0.050616
  2    0.327878  0.276795
  3   -0.021345 -0.029393
  4   -0.018933  0.289206
  ..        ...       ...
  262 -0.097736  0.445045
  263 -0.022350  0.091212
  264  0.026897  0.325803
  265 -0.360963 -0.019892
  266 -0.102049  0.041695

  [267 rows x 1288 columns],
  '4bqh':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       4bqh               1             A            1            A
  1       4bqh               1             A            2            A
  2       4bqh               1             A            3            A
  3       4bqh               1             A            4            A
  4       4bqh               1             A            5            A
  ..       ...             ...           ...          ...          ...
  516     4bqh               1             A          537            A
  517     4bqh               1             A          538            A
  518     4bqh               1             A          539            A
  519     4bqh               1             A          540            A
  520     4bqh               1             A          541            A

                                    Label Embeddings            ...            \
      auth_seq_id pdbx_PDB_ins_code label          0         1  ...      1270
  0            -3                 ?     0   0.033808 -0.015980  ... -0.007750
  1            -2                 ?     0  -0.038733  0.050096  ...  0.145042
  2            -1                 ?     0  -0.074578 -0.015609  ...  0.018396
  3             0                 ?     0  -0.121792  0.114047  ...  0.002232
  4             1                 ?     0  -0.051894  0.006900  ... -0.128364
  ..          ...               ...   ...        ...       ...  ...       ...
  516         533                 ?     0   0.190804 -0.215843  ...  0.230426
  517         534                 ?     0   0.051723 -0.285243  ...  0.190163
  518         535                 ?     0  -0.036968 -0.322045  ...  0.009702
  519         536                 ?     0  -0.156081 -0.321297  ...  0.302013
  520         537                 ?     0  -0.053010 -0.292246  ...  0.389043

                                                                             \
           1271      1272      1273      1274      1275      1276      1277
  0   -0.004476  0.348528  0.340262  0.249727  0.115727 -0.139368  0.213526
  1   -0.090810  0.076533  0.251422  0.082179  0.264917  0.064972  0.118548
  2    0.041859  0.017367  0.044570 -0.066360  0.344422 -0.034779  0.080238
  3    0.167335 -0.144234  0.123537 -0.219415  0.019393 -0.127665  0.076530
  4    0.134215 -0.072112  0.143462  0.019961  0.035402 -0.155515 -0.050171
  ..        ...       ...       ...       ...       ...       ...       ...
  516  0.004286 -0.042493  0.212326  0.054269  0.060481  0.045059  0.056560
  517  0.012079 -0.134016  0.203315  0.169596 -0.024791  0.039418  0.028800
  518 -0.047140 -0.038463  0.090089  0.117292 -0.014384 -0.000620  0.048023
  519  0.004193 -0.076668  0.207786 -0.209516  0.158117 -0.080255 -0.070913
  520 -0.023264 -0.068169  0.162614 -0.305586  0.111476 -0.093829 -0.148284


           1278      1279
  0    0.127628  0.277677
  1    0.220993  0.239138
  2    0.147598  0.099768
  3   -0.084310  0.054485
  4   -0.098239  0.133059
  ..        ...       ...
  516  0.122816  0.068374
  517  0.221096  0.226522
  518  0.327487  0.287841
  519  0.423312  0.289692
  520  0.165272  0.116254

  [521 rows x 1288 columns],
  '1og0':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id

## Per-pocket

In [13]:
from utils.pocket_utils import get_mean_pocket_em

In [14]:
pockets = (
    pd.read_pickle("3.Pockets/old_fpocket/pockets.pkl")[
        ['pdb', 'pocket', 'label']
    ].query(f"pdb in {list(featuresd.keys())}")
)
pockets

       pdb    pocket  label
0     6ta3  pocket16      0
1     6ta3  pocket18      0
2     6ta3  pocket11      0
3     6ta3  pocket15      0
4     6ta3   pocket7      0
...    ...       ...    ...
8136  3d2p   pocket5      0
8137  3d2p   pocket8      0
8138  3d2p   pocket3      0
8139  3d2p  pocket12      0
8140  3d2p   pocket6      0

[5405 rows x 3 columns]

In [15]:
pockets = pd.concat(
    (
        pockets[["pdb", "pocket"]],
        pockets["label"]
    ),
    axis=1,
    keys=["Pockets", "Label"]
)

pockets

     Pockets           Label
         pdb    pocket label
0       6ta3  pocket16     0
1       6ta3  pocket18     0
2       6ta3  pocket11     0
3       6ta3  pocket15     0
4       6ta3   pocket7     0
...      ...       ...   ...
8136    3d2p   pocket5     0
8137    3d2p   pocket8     0
8138    3d2p   pocket3     0
8139    3d2p  pocket12     0
8140    3d2p   pocket6     0

[5405 rows x 3 columns]

In [17]:
pockets_embeddings = pd.concat(
    (
        pockets,
        pockets.apply(
            lambda row: get_mean_pocket_features(
                row[("Pockets", "pdb")],
                row[("Pockets", "pocket")],
                pdb_features = embsd[row[("Pockets", "pdb")]],
                pockets_path = "3.Pockets/old_fpocket/pockets" # f"{pockets_path}/{pdb}/{pdb}_out/pockets/{pocket}_atm.cif"
            ), 
            axis=1 
        )
    ),
    axis=1,
)

In [18]:
pockets_embeddings

     Pockets           Label Embeddings                                \
         pdb    pocket label          0         1         2         3
0       6ta3  pocket16     0  -0.094970 -0.116930  0.040117 -0.058876
1       6ta3  pocket18     0   0.020169 -0.078439  0.061870  0.002930
2       6ta3  pocket11     0   0.007830 -0.014264 -0.099724  0.063862
3       6ta3  pocket15     0  -0.119789  0.135076 -0.017253  0.089593
4       6ta3   pocket7     0  -0.022467  0.067619 -0.017286  0.028015
...      ...       ...   ...        ...       ...       ...       ...
8136    3d2p   pocket5     0  -0.016085  0.121749  0.129790 -0.018972
8137    3d2p   pocket8     0   0.031225 -0.002326  0.070191 -0.046042
8138    3d2p   pocket3     0   0.055994 -0.103168  0.083710 -0.076272
8139    3d2p  pocket12     0  -0.038334 -0.179599  0.115259 -0.068121
8140    3d2p   pocket6     0  -0.048104 -0.031285 -0.018420 -0.035142

                                    ...                                \
             4         5         6  ...      1270      1271      1272
0    -0.174019 -0.282384 -0.125708  ...  0.163619 -0.133219 -0.005906
1    -0.074058 -0.130024  0.047107  ... -0.011803 -0.083614  0.026626
2    -0.098108 -0.089830  0.097989  ...  0.021253 -0.044613 -0.084751
3    -0.042903 -0.116645 -0.001007  ... -0.004941 -0.076110 -0.009547
4    -0.088452 -0.100998  0.031924  ...  0.029544 -0.008624 -0.026880
...        ...       ...       ...  ...       ...       ...       ...
8136 -0.059095  0.023959 -0.047728  ...  0.057683  0.014217 -0.089059
8137 -0.103540 -0.136247  0.075616  ... -0.034458 -0.093629  0.003621
8138 -0.240857 -0.084090  0.107200  ...  0.097598 -0.048996  0.007177
8139 -0.260114 -0.112897  0.090455  ...  0.016604 -0.023116 -0.037841
8140 -0.073292 -0.053034 -0.013052  ...  0.011895 -0.075672 -0.062250


          1273      1274      1275      1276      1277      1278      1279
0    -0.028193 -0.035316 -0.044516  0.102737 -0.064026 -0.034069  0.033591
1     0.024293 -0.019584 -0.023984  0.138034 -0.198573  0.043331  0.090689
2    -0.017245  0.060706 -0.143717 -0.012969  0.001674 -0.008403  0.172018
3     0.089223 -0.056367 -0.224084 -0.022458  0.010889  0.020006  0.102865
4     0.041739 -0.005503 -0.125429  0.008519  0.015348 -0.030216  0.105604
...        ...       ...       ...       ...       ...       ...       ...
8136  0.065058  0.054057  0.080963 -0.065427 -0.157244 -0.102713 -0.123586
8137 -0.007728 -0.058156  0.115197  0.057976 -0.006428 -0.015101 -0.075469
8138  0.045579 -0.029063  0.036612  0.033029 -0.094900 -0.026578 -0.138080
8139 -0.069211 -0.014965  0.095894 -0.008730 -0.084798 -0.094889 -0.016773
8140  0.110675 -0.102716  0.053968  0.044464 -0.081164  0.045653 -0.013543

[5405 rows x 1283 columns]

In [19]:
pockets_embeddingsf = f"{embeddings_path}/pockets_embeddings.pkl"

if not os.path.isfile(pockets_embeddingsf):
    pockets_embeddingsd = {
        pdb: pks
        for pdb, pks in pockets_embeddings.groupby(("Pockets", "pdb"), sort=False)
    }
    with open(pockets_embeddingsf, "wb") as f:
        pickle.dump(pockets_embeddingsd, f)
else:
    with open(pockets_embeddingsf, "rb") as f:
        pockets_embeddingsd = pickle.load(f)

len(pockets_embeddingsd), pockets_embeddingsd

(289,
 {'6ta3':    Pockets           Label Embeddings                                          \
         pdb    pocket label          0         1         2         3         4
  0     6ta3  pocket16     0  -0.094970 -0.116930  0.040117 -0.058876 -0.174019
  1     6ta3  pocket18     0   0.020169 -0.078439  0.061870  0.002930 -0.074058
  2     6ta3  pocket11     0   0.007830 -0.014264 -0.099724  0.063862 -0.098108
  3     6ta3  pocket15     0  -0.119789  0.135076 -0.017253  0.089593 -0.042903
  4     6ta3   pocket7     0  -0.022467  0.067619 -0.017286  0.028015 -0.088452
  5     6ta3  pocket22     0   0.031462 -0.130496 -0.006135  0.123543 -0.165853
  6     6ta3  pocket13     0   0.004531 -0.002420 -0.084282 -0.092910 -0.095742
  7     6ta3  pocket14     0  -0.060161  0.063076 -0.102772  0.040867 -0.174732
  8     6ta3   pocket1     0  -0.004252  0.047088 -0.040080  0.002065 -0.052970
  9     6ta3   pocket2     1   0.001850 -0.126576 -0.058374  0.070443 -0.113652
  10    6ta3  pocket20     0   0.029202  0.013847 -0.058790 -0.020545 -0.163262
  11    6ta3   pocket4     0  -0.044548 -0.071539 -0.005404  0.052327 -0.115621
  12    6ta3  pocket17     0   0.016199 -0.090384  0.071828  0.040640 -0.088653
  13    6ta3   pocket9     0  -0.053014 -0.131618 -0.050844  0.092817  0.006190
  14    6ta3  pocket10     0   0.000966  0.017810  0.012422  0.037351 -0.047819
  15    6ta3   pocket5     0  -0.027483 -0.136307 -0.060619  0.109060 -0.101371
  16    6ta3   pocket8     0   0.028314 -0.068708  0.092906  0.071391 -0.207176
  17    6ta3   pocket3     0  -0.015006 -0.069795 -0.030934  0.060332 -0.139742
  18    6ta3  pocket12     0   0.000184  0.054736 -0.071134  0.037820 -0.103896
  19    6ta3  pocket19     0   0.052314  0.162111 -0.060065  0.058432 -0.081488
  20    6ta3  pocket21     0  -0.058007  0.000943 -0.068756  0.050791 -0.064696
  21    6ta3   pocket6     0  -0.068312 -0.069305  0.050521  0.035674 -0.200939

                          ...                                                    \
             5         6  ...      1270      1271      1272      1273      1274
  0  -0.282384 -0.125708  ...  0.163619 -0.133219 -0.005906 -0.028193 -0.035316
  1  -0.130024  0.047107  ... -0.011803 -0.083614  0.026626  0.024293 -0.019584
  2  -0.089830  0.097989  ...  0.021253 -0.044613 -0.084751 -0.017245  0.060706
  3  -0.116645 -0.001007  ... -0.004941 -0.076110 -0.009547  0.089223 -0.056367
  4  -0.100998  0.031924  ...  0.029544 -0.008624 -0.026880  0.041739 -0.005503
  5  -0.252652  0.093673  ...  0.146732 -0.080402 -0.168267 -0.047708  0.010033
  6   0.008029  0.135602  ...  0.033273 -0.037775 -0.010175 -0.026821  0.043992
  7  -0.091963  0.032486  ...  0.003515 -0.107175 -0.138373  0.054686  0.034155
  8  -0.070959  0.020590  ...  0.040631 -0.020978 -0.033352 -0.020888 -0.040250
  9  -0.120341  0.014035  ...  0.045990 -0.060888 -0.058140 -0.015000  0.011099
  10 -0.097386  0.076429  ...  0.106099  0.103129 -0.046957 -0.054619 -0.066254
  11  0.050939  0.061102  ...  0.136540  0.033070 -0.065813  0.029516 -0.054047
  12 -0.112537  0.043904  ...  0.149459 -0.038356 -0.153135 -0.075664  0.000855
  13 -0.133520  0.135851  ... -0.001702  0.023405  0.036300  0.133431 -0.052964
  14 -0.118201  0.040929  ... -0.012615 -0.027247 -0.060046 -0.032983 -0.051045
  15 -0.013802  0.017881  ...  0.088025  0.027516 -0.044308 -0.039290  0.075692
  16 -0.126294 -0.028503  ...  0.049530 -0.094291 -0.087568 -0.033534  0.027430
  17 -0.237549  0.002735  ...  0.020913 -0.136719 -0.014891 -0.056560 -0.038432
  18 -0.025388  0.024091  ... -0.088160 -0.032783  0.067634 -0.000168  0.022337
  19  0.016668  0.026736  ... -0.049710  0.012049  0.064501 -0.035925  0.121821
  20 -0.076030  0.054595  ...  0.022434 -0.014083 -0.015864 -0.020675  0.003146
  21 -0.188033 -0.063604  ...  0.137273 -0.055258 -0.083873 -0.118059 -0.003005


          1275      1276      1277      1278      1279
  0  -0.044516  0.102737 -0.064026 -0.034069  0.033591
  1  -0.023984  0.138034 -0.198573  0.043331  0.090689
  2  -0.143717 -0.012969  0.001674 -0.008403  0.172018
  3  -0.224084 -0.022458  0.010889  0.020006  0.102865
  4  -0.125429  0.008519  0.015348 -0.030216  0.105604
  5  -0.133142 -0.032215 -0.095207 -0.094223  0.039395
  6  -0.101442 -0.095379 -0.155349 -0.089283  0.280518
  7  -0.165876 -0.028496  0.054759 -0.007911  0.168692
  8  -0.130856  0.005863 -0.007392  0.017341  0.103200
  9  -0.098792 -0.000549 -0.192372 -0.000235  0.145382
  10 -0.061068  0.041662 -0.086752 -0.026013  0.109749
  11  0.016938 -0.058346 -0.218955 -0.008915  0.156852
  12 -0.130957 -0.091291 -0.063527 -0.039056  0.008205
  13 -0.072035  0.028170 -0.203641 -0.045846  0.021983
  14 -0.014898  0.042514 -0.085686  0.004018 -0.012866
  15 -0.255404 -0.052781  0.018766 -0.048166  0.157138
  16 -0.017534  0.025954 -0.194377 -0.003466  0.023225
  17 -0.018358  0.105438 -0.309757  0.034954  0.065861
  18 -0.112284 -0.001086  0.002614  0.045009  0.049334
  19 -0.168276  0.029061 -0.016156 -0.008022  0.155699
  20 -0.137243  0.111306  0.060897  0.070910  0.132760
  21  0.101108  0.109952 -0.211861  0.033935 -0.008722

  [22 rows x 1283 columns],
  '5kwj':    Pockets          Label Embeddings                                          \
         pdb   pocket label          0         1         2         3         4
  22    5kwj  pocket1     1   0.022690 -0.171373  0.004288  0.142965 -0.052981
  23    5kwj  pocket2     0   0.000293 -0.166064 -0.039057  0.186883 -0.130429
  24    5kwj  pocket4     0   0.010331 -0.233627 -0.048983  0.177287 -0.054215
  25    5kwj  pocket5     0   0.061636 -0.048929  0.077530  0.037805 -0.109450
  26    5kwj  pocket3     0   0.098346 -0.112764 -0.009935  0.336254  0.046039
  27    5kwj  pocket6     0   0.018594 -0.173065  0.088794  0.131454  0.029995

                          ...                                                    \
             5         6  ...      1270      1271      1272      1273      1274
  22  0.000789  0.144312  ...  0.017525 -0.077979 -0.130879  0.027525 -0.029700
  23  0.074898  0.083833  ... -0.059639 -0.059617 -0.129876 -0.104194  0.024851
  24 -0.014472  0.125760  ...  0.006397 -0.080346 -0.074860 -0.101347  0.006059
  25 -0.100872  0.034236  ...  0.038029 -0.180102 -0.080346  0.025242 -0.120682
  26 -0.031245  0.185235  ...  0.030789 -0.054464 -0.152705 -0.192014  0.143565
  27 -0.040535  0.044678  ... -0.061409 -0.154151 -0.027612 -0.039513  0.059648


          1275      1276      1277      1278      1279
  22 -0.095823 -0.048610 -0.284258  0.008597  0.280218
  23 -0.015098 -0.167302 -0.262617  0.126302  0.284495
  24 -0.071260  0.006122 -0.424372  0.022142  0.288109
  25 -0.117736 -0.101206 -0.245099  0.062541  0.154993
  26 -0.076879 -0.022469 -0.240872  0.069742  0.269325
  27 -0.002966 -0.071034 -0.203452  0.020272  0.217894

  [6 rows x 1283 columns],
  '6t4k':    Pockets           Label Embeddings                                          \
         pdb    pocket label          0         1         2         3         4
  28    6t4k   pocket7     0  -0.018396  0.038837  0.008378  0.160195 -0.140189
  29    6t4k   pocket1     1  -0.027680 -0.041307  0.138013  0.062444 -0.159044
  30    6t4k   pocket2     0  -0.005789 -0.058214  0.031319  0.146132 -0.133242
  31    6t4k   pocket4     0   0.006888  0.068704  0.012526  0.186175 -0.029278
  32    6t4k   pocket9     0   0.034286 -0.096044 -0.050590  0.132643 -0.173642
  33    6t4k  pocket10     0  -0.005398  0.099612  0.121134  0.241812 -0.169587
  34    6t4k   pocket5     0   0.002987 -0.012370  0.007987  0.072173 -0.082702
  35    6t4k   pocket8     0  -0.130560 -0.070794  0.075640  0.016642 -0.167498
  36    6t4k   pocket3     0   0.052266  0.013006  0.064428  0.120148 -0.155724
  37    6t4k   pocket6     0   0.014526 -0.003642 -0.006621  0.072677 -0.028260

                          ...                                                    \
             5         6  ...      1270      1271      1272      1273      1274
  28 -0.013864  0.126166  ...  0.010317 -0.094162 -0.246087  0.037565 -0.018256
  29  0.017216  0.149546  ...  0.038908 -0.052533 -0.240666  0.132618 -0.040562
  30 -0.027252  0.158354  ...  0.043087 -0.033965 -0.225757  0.071172  0.055024
  31 -0.093852 -0.010264  ...  0.076546 -0.039039 -0.244923 -0.036245 -0.019846
  32 -0.001816  0.090026  ... -0.013943 -0.041863 -0.219678  0.129503  0.096305
  33  0.042220 -0.052428  ...  0.161745  0.056915 -0.262994 -0.006109 -0.069112
  34 -0.035507 -0.010513  ... -0.038845 -0.077773 -0.247461  0.070363 -0.008439
  35 -0.025134  0.173418  ...  0.064239 -0.064886 -0.243381 -0.026417 -0.117494
  36 -0.001650 -0.018941  ...  0.164467 -0.037111 -0.154934 -0.009246 -0.061000
  37 -0.011790  0.057535  ...  0.034949  0.014474 -0.193406  0.028458  0.018684


          1275      1276      1277      1278      1279
  28 -0.123413 -0.001778 -0.209096  0.023215  0.159030
  29 -0.093878 -0.026872 -0.268394  0.001332  0.271485
  30  0.000568 -0.007742 -0.293968  0.006394  0.212929
  31 -0.074144 -0.113421 -0.133030  0.060352  0.059062
  32 -0.028869 -0.050460 -0.305540  0.046048  0.240389
  33 -0.184929  0.066823 -0.059802  0.074573  0.098838
  34 -0.013779  0.074639 -0.186702 -0.050540 -0.034064
  35 -0.020634 -0.028513 -0.139318 -0.016164  0.229576
  36 -0.024598  0.048603 -0.230002  0.063768  0.194994
  37  0.096534 -0.009748 -0.158765 -0.038564  0.078548

  [10 rows x 1283 columns],
  '5mo6':    Pockets           Label Embeddings                                          \
         pdb    pocket label          0         1         2         3         4
  38    5mo6  pocket11     0   0.014923  0.019613 -0.089828 -0.000082 -0.253750
  39    5mo6   pocket7     0  -0.048329 -0.127005 -0.123691 -0.004793 -0.397893
  40    5mo6  pocket13     0  -0.094210 -0.059419  0.004035  0.005260 -0.237268
  41    5mo6   pocket1     0  -0.190962  0.030592 -0.025426  0.167430 -0.186082
  42    5mo6   pocket2     0  -0.041280 -0.186163 -0.055644  0.035702 -0.232643
  43    5mo6   pocket4     0   0.159032 -0.113822  0.021265  0.094907 -0.191312
  44    5mo6   pocket9     0   0.024935 -0.037289 -0.081051  0.073848 -0.026215
  45    5mo6  pocket10     0  -0.007114 -0.094567  0.021163 -0.030893 -0.100553
  46    5mo6   pocket5     1  -0.121101 -0.116730  0.002406 -0.001124 -0.198686
  47    5mo6   pocket8     0  -0.080704 -0.050714 -0.094732 -0.077704 -0.180508
  48    5mo6   pocket3     0   0.079784 -0.081228 -0.047011  0.029546 -0.247099
  49    5mo6  pocket12     0  -0.009427 -0.086999 -0.049330 -0.071699 -0.261953
  50    5mo6   pocket6     0  -0.030602 -0.146308 -0.001272 -0.101355 -0.341857

                          ...                                                    \
             5         6  ...      1270      1271      1272      1273      1274
  38 -0.018431  0.152047  ...  0.085578 -0.117067 -0.175325  0.015909  0.084418
  39 -0.024604  0.280814  ...  0.026117 -0.030915 -0.212273  0.162820  0.063212
  40 -0.031664  0.312073  ... -0.013382 -0.104256 -0.151125  0.082535 -0.013720
  41  0.044133  0.191642  ...  0.075591 -0.040258 -0.051973  0.142210 -0.002411
  42 -0.251172  0.226946  ...  0.009308 -0.152637 -0.040992  0.107490  0.027146
  43  0.198449  0.226355  ... -0.103232 -0.142578 -0.205830  0.155572  0.043718
  44 -0.137122  0.074287  ...  0.087228 -0.061493 -0.014280  0.093096  0.014048
  45  0.002013  0.236874  ...  0.097668 -0.055494 -0.090939  0.163606  0.039761
  46 -0.109444  0.169501  ...  0.031499  0.002039 -0.108376  0.153725 -0.052201
  47 -0.102667  0.245191  ...  0.005131 -0.151401 -0.231159  0.027438  0.036865
  48  0.093295  0.157351  ... -0.076690 -0.213455 -0.145011  0.136554  0.112607
  49 -0.036860  0.252413  ... -0.024070 -0.092319  0.004478  0.158660 -0.048645
  50 -0.007297  0.131640  ... -0.070356 -0.115638 -0.134765  0.092106  0.104939


          1275      1276      1277      1278      1279
  38 -0.115787  0.008817 -0.264861  0.001971  0.151174
  39 -0.121898 -0.070367 -0.531262  0.098383  0.196585
  40 -0.082936  0.000767 -0.468721  0.111470  0.251660
  41  0.017888 -0.103065 -0.235404  0.177617  0.180132
  42 -0.041100 -0.123683 -0.177717  0.041565  0.027377
  43 -0.011305  0.056407 -0.194870  0.128190  0.148667
  44 -0.071230  0.054597 -0.389548  0.133511  0.110132
  45  0.013667  0.030012 -0.424487  0.252719  0.141568
  46  0.016180 -0.000752 -0.337477 -0.008820  0.131977
  47 -0.104040  0.012050 -0.440581  0.020439  0.205226
  48 -0.066973  0.018774 -0.307587  0.120478  0.101875
  49  0.016590 -0.069607 -0.357857  0.006312  0.119912
  50 -0.064903  0.024264 -0.076599 -0.018258  0.115201

  [13 rows x 1283 columns],
  '3o0n':    Pockets           Label Embeddings                                          \
         pdb    pocket label          0         1         2         3         4
  51    3o0n  pocket16     0   0.048016 -0.043614 -0.023096  0.006673  0.037118
  52    3o0n  pocket28     0   0.113775 -0.069439 -0.071736 -0.023825 -0.005055
  53    3o0n  pocket18     0   0.136696 -0.064560 -0.022154  0.019057 -0.052604
  54    3o0n  pocket11     0   0.103930 -0.055187 -0.068521 -0.010457 -0.144762
  55    3o0n  pocket34     0   0.156840 -0.101402 -0.083708 -0.046375 -0.041449
  56    3o0n  pocket25     0   0.150564 -0.050572  0.066075  0.051909 -0.006499
  57    3o0n  pocket15     0   0.112646 -0.160938 -0.015676 -0.045688  0.014280
  58    3o0n  pocket40     0   0.186296 -0.099734 -0.080273 -0.061454 -0.053617
  59    3o0n   pocket7     0   0.059979 -0.123808  0.033832 -0.077287 -0.058623
  60    3o0n  pocket22     0   0.146220 -0.162189 -0.084451  0.047151 -0.036155
  61    3o0n  pocket13     0   0.103930 -0.055187 -0.068521 -0.010457 -0.144762
  62    3o0n  pocket31     0   0.093237 -0.003783  0.023749 -0.087573 -0.076102
  63    3o0n  pocket39     0   0.011620 -0.274491 -0.034025 -0.050888 -0.055299
  64    3o0n  pocket23     0   0.099091 -0.078631  0.024212 -0.065628  0.019592
  65    3o0n  pocket14     0  -0.011749 -0.103878 -0.010723  0.035631 -0.122639
  66    3o0n  pocket26     0   0.172457 -0.129006 -0.234115 -0.060118  0.044965
  67    3o0n   pocket1     0   0.046366 -0.131761 -0.027427  0.029029 -0.007676
  68    3o0n  pocket27     0   0.136394 -0.142726 -0.052852 -0.033973 -0.060617
  69    3o0n   pocket2     0   0.091911 -0.066742 -0.034909  0.007556  0.010119
  70    3o0n  pocket32     0   0.172457 -0.129006 -0.234115 -0.060118  0.044965
  71    3o0n  pocket20     0   0.075105 -0.063166 -0.041355  0.017615 -0.021256
  72    3o0n   pocket4     0   0.048219 -0.036167 -0.022366 -0.019334  0.033888
  73    3o0n  pocket29     0   0.099091 -0.078631  0.024212 -0.065628  0.019592
  74    3o0n  pocket30     0   0.189553 -0.113264 -0.038036  0.018516 -0.004345
  75    3o0n  pocket17     0   0.136696 -0.064560 -0.022154  0.019057 -0.052604
  76    3o0n   pocket9     0   0.071321 -0.134705 -0.037208  0.008061 -0.022855
  77    3o0n  pocket10     0   0.071321 -0.134705 -0.037208  0.008061 -0.022855
  78    3o0n  pocket35     1   0.054613  0.054547 -0.001245 -0.008089 -0.029423
  79    3o0n   pocket5     0   0.048219 -0.036167 -0.022366 -0.019334  0.033888
  80    3o0n   pocket8     0  -0.007523 -0.175693 -0.061341  0.027114 -0.052650
  81    3o0n  pocket37     0   0.092804 -0.207268 -0.021903  0.057789 -0.024956
  82    3o0n  pocket24     0  -0.011749 -0.103878 -0.010723  0.035631 -0.122639
  83    3o0n   pocket3     1   0.086082 -0.025117  0.000835 -0.035178 -0.015573
  84    3o0n  pocket12     0   0.119532 -0.014288 -0.004284 -0.033302  0.005936
  85    3o0n  pocket38     0   0.066169 -0.182499 -0.015816  0.035065 -0.023135
  86    3o0n  pocket42     0   0.200109 -0.144333 -0.007388 -0.019956  0.008510
  87    3o0n  pocket19     0   0.133198 -0.115761 -0.030906 -0.006867 -0.037178
  88    3o0n  pocket21     0   0.243603 -0.109192 -0.036735  0.076996 -0.068930
  89    3o0n  pocket33     0   0.081535 -0.023123 -0.043372 -0.058629  0.041299
  90    3o0n  pocket36     0   0.215902 -0.082574  0.116778  0.000780 -0.029792
  91    3o0n  pocket41     0   0.138544  0.015094  0.046127 -0.023033 -0.028395
  92    3o0n   pocket6     0   0.107785 -0.091322  0.003978  0.048524  0.030238

                          ...                                                    \
             5         6  ...      1270      1271      1272      1273      1274
  51  0.025906 -0.080565  ...  0.066187  0.001268 -0.090167  0.080075  0.015497
  52 -0.040826 -0.036383  ...  0.224953 -0.006557 -0.117072  0.073071  0.043177
  53  0.073341 -0.120563  ... -0.012297 -0.023218 -0.142898  0.046332 -0.003533
  54  0.036204 -0.065335  ...  0.005655 -0.082764 -0.139859  0.151372  0.031854
  55 -0.118800 -0.038076  ...  0.016378  0.020826 -0.120829  0.135332  0.003820
  56  0.018506 -0.038696  ...  0.118103  0.046052  0.002755  0.138479  0.067692
  57 -0.064562  0.011067  ...  0.080849 -0.020279 -0.026614  0.130417  0.094167
  58 -0.125184 -0.046488  ...  0.042201  0.037051 -0.117591  0.123441  0.027267
  59 -0.056453 -0.020053  ...  0.145439  0.003770 -0.130710  0.084547 -0.017808
  60 -0.104500 -0.065014  ...  0.210042  0.062655 -0.057715 -0.008630 -0.016036
  61  0.036204 -0.065335  ...  0.005655 -0.082764 -0.139859  0.151372  0.031854
  62 -0.050151 -0.092048  ...  0.135864  0.016786 -0.109493  0.083430  0.044419
  63 -0.004128 -0.066272  ...  0.009157  0.024772 -0.210626  0.062624  0.036185
  64 -0.016064 -0.008570  ...  0.063270 -0.013133 -0.103588  0.105709 -0.007100
  65  0.040176  0.018983  ...  0.100403 -0.107600 -0.166001  0.082931  0.188063
  66 -0.095161  0.033247  ... -0.087374 -0.043864 -0.183580  0.046148  0.098150
  67 -0.040715  0.089129  ...  0.092510 -0.010758 -0.126033  0.070052  0.123933
  68 -0.039679 -0.048095  ...  0.119091  0.018900 -0.089531  0.022753  0.076486
  69  0.012753 -0.082785  ...  0.151057  0.012059 -0.109435  0.088670  0.038977
  70 -0.095161  0.033247  ... -0.087374 -0.043864 -0.183580  0.046148  0.098150
  71  0.046825 -0.043806  ...  0.136790  0.041019 -0.100501  0.124641  0.074919
  72  0.091491 -0.092598  ...  0.091484 -0.005352 -0.070846  0.106486  0.043502
  73 -0.016064 -0.008570  ...  0.063270 -0.013133 -0.103588  0.105709 -0.007100
  74 -0.039687 -0.110652  ...  0.031946  0.086574 -0.212167  0.112537 -0.031312
  75  0.073341 -0.120563  ... -0.012297 -0.023218 -0.142898  0.046332 -0.003533
  76 -0.014413 -0.041762  ...  0.044659  0.043778 -0.019756  0.098259  0.116387
  77 -0.014413 -0.041762  ...  0.044659  0.043778 -0.019756  0.098259  0.116387
  78 -0.005049  0.003278  ...  0.174106 -0.026441 -0.164329  0.134348  0.035572
  79  0.091491 -0.092598  ...  0.091484 -0.005352 -0.070846  0.106486  0.043502
  80 -0.043964  0.159612  ...  0.061148 -0.053194 -0.103733  0.102984  0.191077
  81  0.021261 -0.073462  ...  0.209399  0.040064 -0.007275  0.065468 -0.049691
  82  0.040176  0.018983  ...  0.100403 -0.107600 -0.166001  0.082931  0.188063
  83 -0.015344  0.025825  ...  0.169335  0.007698 -0.121612  0.102920  0.064846
  84 -0.112446 -0.048037  ...  0.032575  0.105201 -0.173923  0.103459 -0.012260
  85  0.077250 -0.085645  ...  0.228085  0.054263 -0.031615  0.086148 -0.005162
  86 -0.049559 -0.018964  ...  0.042653 -0.020379 -0.035573  0.128609  0.048474
  87 -0.070255 -0.081583  ...  0.204057  0.061061 -0.071631  0.037015  0.017716
  88 -0.020511 -0.079246  ...  0.175144  0.032142 -0.163735 -0.073315  0.004462
  89 -0.013060 -0.050342  ...  0.199232 -0.021323 -0.058287  0.009693 -0.008486
  90 -0.000265 -0.016028  ...  0.189067  0.108083 -0.165045  0.144188  0.109582
  91 -0.017300 -0.021562  ...  0.161700  0.035141 -0.144041  0.129901  0.080205
  92 -0.018146  0.020449  ...  0.128754  0.024552 -0.126979  0.058914  0.075337


          1275      1276      1277      1278      1279
  51 -0.106552  0.148657 -0.020100  0.031430 -0.105122
  52 -0.060416  0.171764 -0.212308 -0.023865  0.032498
  53 -0.072554  0.260750 -0.157160  0.104266 -0.137324
  54 -0.083554  0.169822 -0.081021 -0.072919  0.017540