# Requisites

- Environment with dependencies in `conda_env.yaml`
- External dependencies to be downloaded and place in `training_data/utils/external`:
    - predict_ddG.py script from PyRosetta (https://github.com/RosettaCommons/PyRosetta.notebooks/blob/master/notebooks/additional_scripts/predict_ddG.py)
    - DSPP software executable (https://github.com/PDB-REDO/dssp/releases/download/v4.4.0/mkdssp-4.4.0-linux-x64)

In [1]:
from predict import \
get_cif, view_pdb, get_clean_pdb, Site, get_pockets, \
get_colabfold_msa, get_features, get_pockets_features, \
prepare_data, model, view_pockets, get_pathways, view_pockets_pathways

from predict import path as predict_path

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/nglview/__init__.py:12: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

<br>

**Files are written by default to the `predict` folder, customize it with using a different `path=` argument in the functions below.**

<br>

# Predict

## Get protein structure

In [2]:
pdb = get_cif(
    pdb_id="6t4k"
    # file="6t4k.pdb"
)

view_pdb(pdb)

PDBeMolstar(bg_color='#F7F7F7', custom_data={'data': "data_6T4K\n#\n_entry.id 6T4K\n#\n_citation.abstract ?\n_…

In [3]:
pdb.atoms

,group_PDB,id,type_symbol,label_atom_id,label_alt_id,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,...,auth_seq_id,auth_comp_id,auth_asym_id,auth_atom_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,ATOM,1,N,N,.,LEU,A,1,23,?,...,267,LEU,A,N,1,23,UNP,P51449,267,L
1,ATOM,2,C,CA,.,LEU,A,1,23,?,...,267,LEU,A,CA,1,23,UNP,P51449,267,L
2,ATOM,3,C,C,.,LEU,A,1,23,?,...,267,LEU,A,C,1,23,UNP,P51449,267,L
3,ATOM,4,O,O,.,LEU,A,1,23,?,...,267,LEU,A,O,1,23,UNP,P51449,267,L
4,ATOM,5,C,CB,.,LEU,A,1,23,?,...,267,LEU,A,CB,1,23,UNP,P51449,267,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2170,HETATM,2171,O,O,.,HOH,F,5,.,?,...,767,HOH,A,O,1,767,?,?,?,?
2171,HETATM,2172,O,O,.,HOH,F,5,.,?,...,768,HOH,A,O,1,768,?,?,?,?
2172,HETATM,2173,O,O,.,HOH,F,5,.,?,...,769,HOH,A,O,1,769,?,?,?,?
2173,HETATM,2174,O,O,.,HOH,F,5,.,?,...,770,HOH,A,O,1,770,?,?,?,?
2174,HETATM,2175,O,O,.,HOH,F,5,.,?,...,771,HOH,A,O,1,771,?,?,?,?

In [4]:
pdb.residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,LEU,A,1,23,?,267,LEU,A,1,23,UNP,P51449,267,L
8,THR,A,1,24,?,268,THR,A,1,24,UNP,P51449,268,T
15,GLU,A,1,25,?,269,GLU,A,1,25,UNP,P51449,269,E
24,ILE,A,1,26,?,270,ILE,A,1,26,UNP,P51449,270,I
32,GLU,A,1,27,?,271,GLU,A,1,27,UNP,P51449,271,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2170,HOH,F,5,.,?,767,HOH,A,1,767,?,?,?,?
2171,HOH,F,5,.,?,768,HOH,A,1,768,?,?,?,?
2172,HOH,F,5,.,?,769,HOH,A,1,769,?,?,?,?
2173,HOH,F,5,.,?,770,HOH,A,1,770,?,?,?,?
2174,HOH,F,5,.,?,771,HOH,A,1,771,?,?,?,?

## Optional: set a target site

### With a modulator molecule

In [5]:
# Desired modulator is label_asym_id 'C'
pdb.residues.query("label_asym_id == 'C'")

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
2061,4F1,C,3,.,?,602,4F1,A,1,602,?,?,?,?

In [6]:
site = Site(
    pdb, 
    modulator_residues=pdb.residues.query("label_asym_id == 'C'"), 
    only_protein=True
)
site

In [7]:
site.modulator_residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
2061,4F1,C,3,.,?,602,4F1,A,1,602,?,?,?,?

In [8]:
site.residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,TRP,A,1,73,?,317,TRP,A,1,73,UNP,P51449,317,W
1,ALA,A,1,77,?,321,ALA,A,1,77,UNP,P51449,321,A
2,HIS,A,1,78,?,322,HIS,A,1,78,UNP,P51449,322,H
3,LEU,A,1,80,?,324,LEU,A,1,80,UNP,P51449,324,L
4,THR,A,1,81,?,325,THR,A,1,81,UNP,P51449,325,T
5,ILE,A,1,84,?,328,ILE,A,1,84,UNP,P51449,328,I
6,GLN,A,1,85,?,329,GLN,A,1,85,UNP,P51449,329,Q
7,VAL,A,1,88,?,332,VAL,A,1,88,UNP,P51449,332,V
8,LEU,A,1,109,?,353,LEU,A,1,109,UNP,P51449,353,L
9,LYS,A,1,110,?,354,LYS,A,1,110,UNP,P51449,354,K
10,ALA,A,1,111,?,355,ALA,A,1,111,UNP,P51449,355,A
11,GLY,A,1,112,?,356,GLY,A,1,112,UNP,P51449,356,G
12,ALA,A,1,113,?,357,ALA,A,1,113,UNP,P51449,357,A
13,MET,A,1,114,?,358,MET,A,1,114,UNP,P51449,358,M
14,CYS,A,1,232,?,476,CYS,A,1,232,UNP,P51449,476,C
15,HIS,A,1,235,?,479,HIS,A,1,235,UNP,P51449,479,H
16,VAL,A,1,236,?,480,VAL,A,1,236,UNP,P51449,480,V
17,ARG,A,1,238,?,482,ARG,A,1,238,UNP,P51449,482,R
18,LEU,A,1,239,?,483,LEU,A,1,239,UNP,P51449,483,L
19,GLN,A,1,240,?,484,GLN,A,1,240,UNP,P51449,484,Q
20,ILE,A,1,241,?,485,ILE,A,1,241,UNP,P51449,485,I
21,GLN,A,1,243,?,487,GLN,A,1,243,UNP,P51449,487,Q
22,ILE,A,1,248,?,492,ILE,A,1,248,UNP,P51449,492,I
23,VAL,A,1,250,?,494,VAL,A,1,250,UNP,P51449,494,V
24,GLN,A,1,251,?,495,GLN,A,1,251,UNP,P51449,495,Q
25,ALA,A,1,252,?,496,ALA,A,1,252,UNP,P51449,496,A
26,ALA,A,1,253,?,497,ALA,A,1,253,UNP,P51449,497,A
27,PHE,A,1,254,?,498,PHE,A,1,254,UNP,P51449,498,F
28,PRO,A,1,255,?,499,PRO,A,1,255,UNP,P51449,499,P
29,LEU,A,1,257,?,501,LEU,A,1,257,UNP,P51449,501,L
30,TYR,A,1,258,?,502,TYR,A,1,258,UNP,P51449,502,Y
31,LEU,A,1,261,?,505,LEU,A,1,261,UNP,P51449,505,L
32,PHE,A,1,262,?,506,PHE,A,1,262,UNP,P51449,506,F

In [9]:
# List of residue numbers of site
resnums = site.residues.label_seq_id.to_list()
resnums

['73',
 '77',
 '78',
 '80',
 '81',
 '84',
 '85',
 '88',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '232',
 '235',
 '236',
 '238',
 '239',
 '240',
 '241',
 '243',
 '248',
 '250',
 '251',
 '252',
 '253',
 '254',
 '255',
 '257',
 '258',
 '261',
 '262']

### With a list of residues

In [10]:
# Site can be defined with a list of residues instead of a modulator
res_site = Site(
    pdb=pdb,
    residues=[{"label_asym_id": "A", "label_seq_id": seqnum} for seqnum in resnums],
    only_protein=True
)
res_site.residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,TRP,A,1,73,?,317,TRP,A,1,73,UNP,P51449,317,W
1,ALA,A,1,77,?,321,ALA,A,1,77,UNP,P51449,321,A
2,HIS,A,1,78,?,322,HIS,A,1,78,UNP,P51449,322,H
3,LEU,A,1,80,?,324,LEU,A,1,80,UNP,P51449,324,L
4,THR,A,1,81,?,325,THR,A,1,81,UNP,P51449,325,T
5,ILE,A,1,84,?,328,ILE,A,1,84,UNP,P51449,328,I
6,GLN,A,1,85,?,329,GLN,A,1,85,UNP,P51449,329,Q
7,VAL,A,1,88,?,332,VAL,A,1,88,UNP,P51449,332,V
8,LEU,A,1,109,?,353,LEU,A,1,109,UNP,P51449,353,L
9,LYS,A,1,110,?,354,LYS,A,1,110,UNP,P51449,354,K
10,ALA,A,1,111,?,355,ALA,A,1,111,UNP,P51449,355,A
11,GLY,A,1,112,?,356,GLY,A,1,112,UNP,P51449,356,G
12,ALA,A,1,113,?,357,ALA,A,1,113,UNP,P51449,357,A
13,MET,A,1,114,?,358,MET,A,1,114,UNP,P51449,358,M
14,CYS,A,1,232,?,476,CYS,A,1,232,UNP,P51449,476,C
15,HIS,A,1,235,?,479,HIS,A,1,235,UNP,P51449,479,H
16,VAL,A,1,236,?,480,VAL,A,1,236,UNP,P51449,480,V
17,ARG,A,1,238,?,482,ARG,A,1,238,UNP,P51449,482,R
18,LEU,A,1,239,?,483,LEU,A,1,239,UNP,P51449,483,L
19,GLN,A,1,240,?,484,GLN,A,1,240,UNP,P51449,484,Q
20,ILE,A,1,241,?,485,ILE,A,1,241,UNP,P51449,485,I
21,GLN,A,1,243,?,487,GLN,A,1,243,UNP,P51449,487,Q
22,ILE,A,1,248,?,492,ILE,A,1,248,UNP,P51449,492,I
23,VAL,A,1,250,?,494,VAL,A,1,250,UNP,P51449,494,V
24,GLN,A,1,251,?,495,GLN,A,1,251,UNP,P51449,495,Q
25,ALA,A,1,252,?,496,ALA,A,1,252,UNP,P51449,496,A
26,ALA,A,1,253,?,497,ALA,A,1,253,UNP,P51449,497,A
27,PHE,A,1,254,?,498,PHE,A,1,254,UNP,P51449,498,F
28,PRO,A,1,255,?,499,PRO,A,1,255,UNP,P51449,499,P
29,LEU,A,1,257,?,501,LEU,A,1,257,UNP,P51449,501,L
30,TYR,A,1,258,?,502,TYR,A,1,258,UNP,P51449,502,Y
31,LEU,A,1,261,?,505,LEU,A,1,261,UNP,P51449,505,L
32,PHE,A,1,262,?,506,PHE,A,1,262,UNP,P51449,506,F

## Process protein structure

In [11]:
clean_pdb = get_clean_pdb(
    pdb,
    protein_chains=["A"]
)
clean_pdb.residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,LEU,A,1,23,?,267,LEU,A,1,23,UNP,P51449,267,L
8,THR,A,1,24,?,268,THR,A,1,24,UNP,P51449,268,T
15,GLU,A,1,25,?,269,GLU,A,1,25,UNP,P51449,269,E
24,ILE,A,1,26,?,270,ILE,A,1,26,UNP,P51449,270,I
32,GLU,A,1,27,?,271,GLU,A,1,27,UNP,P51449,271,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1930,LYS,A,1,259,?,503,LYS,A,1,259,UNP,P51449,503,K
1939,GLU,A,1,260,?,504,GLU,A,1,260,UNP,P51449,504,E
1948,LEU,A,1,261,?,505,LEU,A,1,261,UNP,P51449,505,L
1956,PHE,A,1,262,?,506,PHE,A,1,262,UNP,P51449,506,F
1967,SER,A,1,263,?,507,SER,A,1,263,UNP,P51449,507,S

## Pockets

In [12]:
pockets = get_pockets(clean_pdb)

pockets

***** POCKET HUNTING BEGINS *****
***** POCKET HUNTING ENDS *****

     pocket
0   pocket7
1   pocket1
2   pocket2
3   pocket4
4   pocket9
5  pocket10
6   pocket5
7   pocket8
8   pocket3
9   pocket6

## Extra: pocket information

In [13]:
from utils.pocket_utils import Pocket, get_pockets_info
import pandas as pd

In [14]:
path = predict_path
path

'predict'

In [15]:
# Number of residues forming the pocket, and pocket-site overlap percentages
## site_in_pocket: % of residues of the site that are part of the pocket (% with the site of the PDB that gives the maximum %, comparing all sites of the PDB with the pocket)
## pocket_in_site: % of residues of the pocket that are part of the allosetric site (% with the site of the PDB that gives the maximum %)

pockets = pd.DataFrame((
    pocket
    for pocket in get_pockets_info(
        clean_pdb, 
        sites = ({
            # "mod": site.modulator_residues,
            "site": site.residues
        },),
        pockets_path = path
    )
))

pockets.loc[
    pockets[['site_in_pocket', 'pocket_in_site']].max(axis=1).sort_values(ascending=False).index
]

    pdb    pocket  nres  site_in_pocket  pocket_in_site
2  6t4k   pocket2    24        0.727273        1.000000
4  6t4k   pocket9    12        0.121212        0.333333
1  6t4k   pocket1    32        0.212121        0.218750
0  6t4k   pocket7    18        0.000000        0.000000
3  6t4k   pocket4    11        0.000000        0.000000
5  6t4k  pocket10     8        0.000000        0.000000
6  6t4k   pocket5    18        0.000000        0.000000
7  6t4k   pocket8     9        0.000000        0.000000
8  6t4k   pocket3    12        0.000000        0.000000
9  6t4k   pocket6    12        0.000000        0.000000

In [16]:
pocket_id = "pocket1"

pocket = Pocket(f"{path}/{clean_pdb.entry_id}/{clean_pdb.entry_id}_out/pockets/{pocket_id}_atm.cif")
pocket

In [17]:
pocket.residues.sort_values("label_seq_id")

,label_comp_id,label_asym_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_asym_id
54,MET,A,114,?,358,A
1,VAL,A,117,?,361,A
6,LEU,A,118,?,362,A
3,ARG,A,120,?,364,A
20,MET,A,121,?,365,A
30,ARG,A,123,?,367,A
31,ALA,A,124,?,368,A
68,VAL,A,132,?,376,A
82,PHE,A,133,?,377,A
15,PHE,A,134,?,378,A
28,PHE,A,144,?,388,A
27,LEU,A,147,?,391,A
25,CYS,A,149,?,393,A
8,LEU,A,152,?,396,A
26,ILE,A,153,?,397,A
39,ILE,A,156,?,400,A
40,PHE,A,157,?,401,A
12,HIS,A,235,?,479,A
10,ARG,A,238,?,482,A
9,LEU,A,239,?,483,A
23,PHE,A,242,?,486,A
33,TYR,A,37,?,281,A
36,CYS,A,41,?,285,A
0,GLN,A,42,?,286,A
35,LEU,A,43,?,287,A
29,LEU,A,48,?,292,A
46,TRP,A,73,?,317,A
14,CYS,A,76,?,320,A
56,ALA,A,77,?,321,A
16,HIS,A,79,?,323,A
57,LEU,A,80,?,324,A
21,ALA,A,83,?,327,A

In [18]:
site.residues

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,TRP,A,1,73,?,317,TRP,A,1,73,UNP,P51449,317,W
1,ALA,A,1,77,?,321,ALA,A,1,77,UNP,P51449,321,A
2,HIS,A,1,78,?,322,HIS,A,1,78,UNP,P51449,322,H
3,LEU,A,1,80,?,324,LEU,A,1,80,UNP,P51449,324,L
4,THR,A,1,81,?,325,THR,A,1,81,UNP,P51449,325,T
5,ILE,A,1,84,?,328,ILE,A,1,84,UNP,P51449,328,I
6,GLN,A,1,85,?,329,GLN,A,1,85,UNP,P51449,329,Q
7,VAL,A,1,88,?,332,VAL,A,1,88,UNP,P51449,332,V
8,LEU,A,1,109,?,353,LEU,A,1,109,UNP,P51449,353,L
9,LYS,A,1,110,?,354,LYS,A,1,110,UNP,P51449,354,K
10,ALA,A,1,111,?,355,ALA,A,1,111,UNP,P51449,355,A
11,GLY,A,1,112,?,356,GLY,A,1,112,UNP,P51449,356,G
12,ALA,A,1,113,?,357,ALA,A,1,113,UNP,P51449,357,A
13,MET,A,1,114,?,358,MET,A,1,114,UNP,P51449,358,M
14,CYS,A,1,232,?,476,CYS,A,1,232,UNP,P51449,476,C
15,HIS,A,1,235,?,479,HIS,A,1,235,UNP,P51449,479,H
16,VAL,A,1,236,?,480,VAL,A,1,236,UNP,P51449,480,V
17,ARG,A,1,238,?,482,ARG,A,1,238,UNP,P51449,482,R
18,LEU,A,1,239,?,483,LEU,A,1,239,UNP,P51449,483,L
19,GLN,A,1,240,?,484,GLN,A,1,240,UNP,P51449,484,Q
20,ILE,A,1,241,?,485,ILE,A,1,241,UNP,P51449,485,I
21,GLN,A,1,243,?,487,GLN,A,1,243,UNP,P51449,487,Q
22,ILE,A,1,248,?,492,ILE,A,1,248,UNP,P51449,492,I
23,VAL,A,1,250,?,494,VAL,A,1,250,UNP,P51449,494,V
24,GLN,A,1,251,?,495,GLN,A,1,251,UNP,P51449,495,Q
25,ALA,A,1,252,?,496,ALA,A,1,252,UNP,P51449,496,A
26,ALA,A,1,253,?,497,ALA,A,1,253,UNP,P51449,497,A
27,PHE,A,1,254,?,498,PHE,A,1,254,UNP,P51449,498,F
28,PRO,A,1,255,?,499,PRO,A,1,255,UNP,P51449,499,P
29,LEU,A,1,257,?,501,LEU,A,1,257,UNP,P51449,501,L
30,TYR,A,1,258,?,502,TYR,A,1,258,UNP,P51449,502,Y
31,LEU,A,1,261,?,505,LEU,A,1,261,UNP,P51449,505,L
32,PHE,A,1,262,?,506,PHE,A,1,262,UNP,P51449,506,F

In [19]:
pocket.feats

{'Pocket Score': 0.6382,
 'Drug Score': 0.9502,
 'Number of alpha spheres': 149.0,
 'Mean alpha-sphere radius': 3.6986,
 'Mean alpha-sphere Solvent Acc.': 0.521,
 'Mean B-factor of pocket residues': 0.0775,
 'Hydrophobicity Score': 64.7188,
 'Polarity Score': 8.0,
 'Amino Acid based volume Score': 4.875,
 'Pocket volume (Monte Carlo)': 982.4406,
 'Pocket volume (convex hull)': 617.746,
 'Charge Score': 5.0,
 'Local hydrophobic density Score': 68.7478,
 'Number of apolar alpha sphere': 115.0,
 'Proportion of apolar alpha sphere': 0.7718,
 'Total SASA': 187.486,
 'Polar SASA': 32.277,
 'Apolar SASA': 155.21,
 'Proportion of polar atoms': 20.879,
 'Alpha sphere density': 8.34,
 'Cent. of mass - Alpha Sphere max dist': 20.956,
 'Flexibility': 0.077}

## Features

**ColabFold MSA**

For single predictions, HHBlits' resource-intensive calculations are substituted by an HHM built from a Multiple Sequence Alignment computed through ColabFold. To use ColabFold's MSA services, please provide your email to the server's call below, respect [ColabFold's MSA server usage limits](https://github.com/sokrypton/ColabFold#:~:text=Is%20it%20okay%20to%20use%20the%20MMseqs2%20MSA%20server%20(cf.run_mmseqs2)%20on%20a%20local%20computer%3F) and [acknowledge the tool](https://github.com/sokrypton/ColabFold#how-do-i-reference-this-work) appropriately. Consider switching to the [local setup of HHBlits](https://github.com/frannerin/AlloPockets#hhblits-for-multiple-predictions) to perform multiple AlloPockets computations.

In [20]:
get_colabfold_msa(
    clean_pdb,
    "youremail@yourinstitution.com"
)

### Features

In [21]:
features = get_features(
    clean_pdb
)
features

  0%|          | 0/9 [00:00<?, ?it/s]

Output()

core.chemical.GlobalResidueTypeSet: Finished initializing fa_standard residue type set.  Created 985 residue types
core.chemical.GlobalResidueTypeSet: Total time to initialize 0.382262 seconds.
core.import_pose.import_pose: File 'predict/6t4k.cif' automatically determined to be of type mmCIF from contents.

2025-07-16 17:35:38,109 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-07-16 17:35:38,110 - .prody - WARNING - WARNING No anisotropic B factors found
2025-07-16 17:35:38,110 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.03s.
2025-07-16 17:35:38,175 - .prody - DEBUG - Hessian was built in 0.06s.
2025-07-16 17:35:41,313 - .prody - DEBUG - 714 modes were calculated in 3.14s.
2025-07-16 17:35:41,383 - .prody - INFO - Calculating stiffness matrix.
2025-07-16 17:35:41,502 - .prody - DEBUG - Stiffness matrix calculated in 0.12s.
2025-07-16 17:35:41,510 - .prody - INFO - The range of effective force constant is: 7.608823820052636 to 24.362333890274677.
2025-07-16 17:35:41,517 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:41,721 - .prody - DEBUG - 10 modes were calculated in 0.20s.
2025-07-16 17:35:41,732 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:41,981 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:35:41,987 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:42,230 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:35:42,238 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:42,483 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:35:42,494 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:42,713 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:35:42,722 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:42,957 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:42,968 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,195 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:43,208 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,422 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:35:43,431 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,589 - .prody - DEBUG - 10 modes were calculated in 0.16s.
2025-07-16 17:35:43,598 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,600 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,605 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,609 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,618 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,625 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:43,630 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,636 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:43,644 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,648 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,653 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,656 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,664 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,677 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:43,683 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,685 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,698 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,703 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,708 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,711 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,716 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,733 - .prody - DEBUG - 10 modes were calculated in 0.02s.
2025-07-16 17:35:43,738 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,741 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,746 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,749 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,754 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,757 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,762 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,778 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:43,783 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,786 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,798 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,803 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,809 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,812 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,818 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,820 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,834 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,837 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,843 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,846 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,852 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,855 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,861 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,865 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,876 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,881 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,887 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,890 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,897 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,899 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,909 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,913 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,918 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,922 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,935 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,940 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,947 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,950 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,956 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,958 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,967 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:43,976 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:43,981 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,984 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,989 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:43,992 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:43,997 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,000 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,014 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,017 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,022 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,025 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,030 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,033 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,039 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,042 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,055 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,059 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,065 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,080 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:44,087 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,090 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,096 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,099 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,105 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,116 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:44,122 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,124 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,130 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:44,132 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,146 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:44,151 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:44,162 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:44,432 - .prody - DEBUG - 10 modes were calculated in 0.27s.
2025-07-16 17:35:44,444 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:44,667 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:35:44,683 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:44,951 - .prody - DEBUG - 10 modes were calculated in 0.26s.
2025-07-16 17:35:44,961 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:45,199 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:45,209 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:45,428 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:35:45,437 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:45,686 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:35:45,693 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:45,758 - .prody - DEBUG - 10 modes were calculated in 0.06s.
2025-07-16 17:35:45,764 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:45,767 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:45,772 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:45,775 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:45,780 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:45,783 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:45,795 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:45,970 - .prody - DEBUG - 10 modes were calculated in 0.17s.
2025-07-16 17:35:45,983 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:45,999 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:46,011 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:46,042 - .prody - DEBUG - 10 modes were calculated in 0.03s.
2025-07-16 17:35:46,053 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:46,123 - .prody - DEBUG - 10 modes were calculated in 0.07s.
2025-07-16 17:35:46,132 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:46,326 - .prody - DEBUG - 10 modes were calculated in 0.19s.
2025-07-16 17:35:46,334 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:46,558 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:35:46,563 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:46,747 - .prody - DEBUG - 10 modes were calculated in 0.18s.
2025-07-16 17:35:46,756 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:46,921 - .prody - DEBUG - 10 modes were calculated in 0.16s.
2025-07-16 17:35:46,928 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:47,133 - .prody - DEBUG - 10 modes were calculated in 0.20s.
2025-07-16 17:35:47,145 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:47,355 - .prody - DEBUG - 10 modes were calculated in 0.21s.
2025-07-16 17:35:47,360 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:47,598 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:47,603 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:47,826 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:35:47,832 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:47,835 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:47,841 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:47,872 - .prody - DEBUG - 10 modes were calculated in 0.03s.
2025-07-16 17:35:47,880 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:47,885 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:47,894 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:48,118 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:35:48,128 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:48,360 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:48,366 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:48,554 - .prody - DEBUG - 10 modes were calculated in 0.18s.
2025-07-16 17:35:48,565 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:48,795 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:48,800 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:49,041 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:35:49,050 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:49,282 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:49,292 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:49,538 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:35:49,549 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:49,810 - .prody - DEBUG - 10 modes were calculated in 0.26s.
2025-07-16 17:35:49,819 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:50,056 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:35:50,066 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:50,083 - .prody - DEBUG - 10 modes were calculated in 0.02s.
2025-07-16 17:35:50,089 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,091 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,097 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,104 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:50,109 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,112 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,118 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,121 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,126 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,129 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,135 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,138 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,143 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,146 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,152 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,155 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,160 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,163 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,169 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,434 - .prody - DEBUG - 10 modes were calculated in 0.26s.
2025-07-16 17:35:50,444 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,669 - .prody - DEBUG - 10 modes were calculated in 0.22s.
2025-07-16 17:35:50,676 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:50,679 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:50,702 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:51,010 - .prody - DEBUG - 10 modes were calculated in 0.31s.
2025-07-16 17:35:51,016 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:51,166 - .prody - DEBUG - 10 modes were calculated in 0.15s.
2025-07-16 17:35:51,175 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:51,405 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:51,415 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:51,690 - .prody - DEBUG - 10 modes were calculated in 0.27s.
2025-07-16 17:35:51,703 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:51,956 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:35:51,966 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:52,234 - .prody - DEBUG - 10 modes were calculated in 0.27s.
2025-07-16 17:35:52,244 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:52,498 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:35:52,508 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:52,757 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:35:52,766 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:53,004 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:53,013 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:53,256 - .prody - DEBUG - 10 modes were calculated in 0.24s.
2025-07-16 17:35:53,271 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:53,500 - .prody - DEBUG - 10 modes were calculated in 0.23s.
2025-07-16 17:35:53,509 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:53,523 - .prody - DEBUG - 10 modes were calculated in 0.01s.
2025-07-16 17:35:53,528 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,531 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,536 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,539 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,544 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,547 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,552 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,554 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,559 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,562 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,567 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,570 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,575 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,578 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,587 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:53,844 - .prody - DEBUG - 10 modes were calculated in 0.25s.
2025-07-16 17:35:53,854 - .prody - DEBUG - Kirchhoff was built in 0.01s.
2025-07-16 17:35:53,878 - .prody - DEBUG - 10 modes were calculated in 0.02s.
2025-07-16 17:35:53,883 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,911 - .prody - DEBUG - 10 modes were calculated in 0.03s.
2025-07-16 17:35:53,920 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,938 - .prody - DEBUG - 10 modes were calculated in 0.02s.
2025-07-16 17:35:53,942 - .prody - DEBUG - Kirchhoff was built in 0.00s.
2025-07-16 17:35:53,945 - .prody - DEBUG - 10 modes were calculated in 0.00s.
2025-07-16 17:35:53,950 - .prody - DEBUG - Kirchhoff was built in 0.00s.

           Residues                                                      \
    label_entity_id label_asym_id label_seq_id auth_asym_id auth_seq_id
0                 1             A           23            A         267
1                 1             A           24            A         268
2                 1             A           25            A         269
3                 1             A           26            A         270
4                 1             A           27            A         271
..              ...           ...          ...          ...         ...
235               1             A          259            A         503
236               1             A          260            A         504
237               1             A          261            A         505
238               1             A          262            A         506
239               1             A          263            A         507

                      Label     Amino acids                                  \
    pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C label_comp_id_D
0                   ?     0               0               0               0
1                   ?     0               0               0               0
2                   ?     0               0               0               0
3                   ?     0               0               0               0
4                   ?     0               0               0               0
..                ...   ...             ...             ...             ...
235                 ?     0               0               0               0
236                 ?     0               0               0               0
237                 ?     0               0               0               0
238                 ?     0               0               0               0
239                 ?     0               0               0               0

     ...   HHBlits                                                    \
     ...      M->M      M->I      M->D      I->M      I->I      D->M
0    ...  0.965936  0.018880  0.014875  1.000000  0.000000  0.000000
1    ...  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000
2    ...  0.948027  0.016735  0.035526  1.000000  0.000000  0.000000
3    ...  1.000000  0.000000  0.000000  0.000000  0.000000  0.837987
4    ...  0.970634  0.029097  0.000000  0.142892  0.857376  0.000000
..   ...       ...       ...       ...       ...       ...       ...
235  ...  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000
236  ...  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000
237  ...  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000
238  ...  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000
239  ...  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000


         D->D   Neff Neff_I Neff_D
0    1.000000  5.675  1.003  1.054
1    1.000000  5.749  0.000  1.110
2    1.000000  5.796  1.002  1.110
3    0.161993  5.842  0.000  1.192
4    1.000000  6.014  1.037  1.000
..        ...    ...    ...    ...
235  0.000000  6.133  0.000  0.000
236  0.000000  6.133  0.000  0.000
237  0.000000  6.122  0.000  0.000
238  0.000000  6.110  0.000  0.000
239  0.000000  5.709  0.000  0.000

[240 rows x 173 columns]

In [22]:
pockets_features = get_pockets_features(
    clean_pdb,
    pockets,
    features
)
pockets_features

  Pockets                                                   FPocket  \
      pdb    pocket nres site_in_pocket pocket_in_site Pocket Score
0    6t4k   pocket7   18       0.000000       0.000000       0.1011
1    6t4k   pocket1   32       0.212121       0.218750       0.6382
2    6t4k   pocket2   24       0.727273       1.000000       0.4838
3    6t4k   pocket4   11       0.000000       0.000000       0.2847
4    6t4k   pocket9   12       0.121212       0.333333       0.0635
5    6t4k  pocket10    8       0.000000       0.000000      -0.0422
6    6t4k   pocket5   18       0.000000       0.000000       0.1913
7    6t4k   pocket8    9       0.000000       0.000000       0.0946
8    6t4k   pocket3   12       0.000000       0.000000       0.3352
9    6t4k   pocket6   12       0.000000       0.000000       0.1324

                                                               \
  Drug Score Number of alpha spheres Mean alpha-sphere radius
0     0.0012                    75.0                   3.6407
1     0.9502                   149.0                   3.6986
2     0.9420                   171.0                   3.6925
3     0.0029                    49.0                   3.4688
4     0.0188                    49.0                   3.6567
5     0.0012                    38.0                   3.6787
6     0.0119                    63.0                   3.5531
7     0.0053                    52.0                   3.4860
8     0.0126                    48.0                   3.2805
9     0.0020                    61.0                   3.5795

                                  ...   HHBlits                                \
  Mean alpha-sphere Solvent Acc.  ...      M->M      M->I      M->D      I->M
0                         0.5436  ...  0.985944  0.009781  0.004281  0.256721
1                         0.5210  ...  0.981010  0.015359  0.003607  0.302886
2                         0.5051  ...  0.979908  0.003483  0.016625  0.286110
3                         0.5294  ...  0.966259  0.031770  0.001881  0.163600
4                         0.5735  ...  0.998503  0.001030  0.000464  0.095241
5                         0.6109  ...  0.994015  0.005135  0.000782  0.035083
6                         0.5207  ...  0.964001  0.030956  0.005088  0.328526
7                         0.4960  ...  0.982483  0.014218  0.003329  0.407597
8                         0.3951  ...  0.996113  0.002252  0.001639  0.250000
9                         0.5048  ...  0.981677  0.011481  0.006781  0.110790


       I->I      D->M      D->D      Neff    Neff_I    Neff_D
0  0.187710  0.235136  0.709287  6.248667  0.482889  0.976389
1  0.290861  0.201426  0.548550  6.253406  0.662906  0.800219
2  0.088886  0.136745  0.446590  6.196000  0.376208  0.740500
3  0.381885  0.130397  0.778696  6.360909  0.700182  0.922091
4  0.071448  0.083333  0.250000  6.255750  0.166667  0.336167
5  0.214926  0.000000  0.375000  6.328375  0.264750  0.381500
6  0.171460  0.153127  0.291315  6.339389  0.645389  0.450667
7  0.481250  0.130528  0.869425  6.372556  0.941444  1.068333
8  0.000000  0.083333  0.500000  6.228417  0.251833  0.593500
9  0.305895  0.232276  0.517714  6.216500  0.439500  0.787667

[10 rows x 193 columns]

## Predict

In [23]:
data = prepare_data(pockets_features)
data

,FPocket_Pocket Score,FPocket_Drug Score,FPocket_Number of alpha spheres,FPocket_Mean alpha-sphere radius,FPocket_Mean alpha-sphere Solvent Acc.,FPocket_Mean B-factor of pocket residues,FPocket_Hydrophobicity Score,FPocket_Polarity Score,FPocket_Amino Acid based volume Score,FPocket_Pocket volume (Monte Carlo),...,HHBlits_M->M,HHBlits_M->I,HHBlits_M->D,HHBlits_I->M,HHBlits_I->I,HHBlits_D->M,HHBlits_D->D,HHBlits_Neff,HHBlits_Neff_I,HHBlits_Neff_D
6t4k_pocket7,0.1011,0.0012,75.0,3.6407,0.5436,0.2026,30.4444,10.0,4.2222,582.5712,...,0.985944,0.009781,0.004281,0.256721,0.187710,0.235136,0.709287,6.248667,0.482889,0.976389
6t4k_pocket1,0.6382,0.9502,149.0,3.6986,0.5210,0.0775,64.7188,8.0,4.8750,982.4406,...,0.981010,0.015359,0.003607,0.302886,0.290861,0.201426,0.548550,6.253406,0.662906,0.800219
6t4k_pocket2,0.4838,0.9420,171.0,3.6925,0.5051,0.2603,61.2083,7.0,4.5000,705.7756,...,0.979908,0.003483,0.016625,0.286110,0.088886,0.136745,0.446590,6.196000,0.376208,0.740500
6t4k_pocket4,0.2847,0.0029,49.0,3.4688,0.5294,0.0798,17.0000,8.0,4.2727,411.9718,...,0.966259,0.031770,0.001881,0.163600,0.381885,0.130397,0.778696,6.360909,0.700182,0.922091
6t4k_pocket9,0.0635,0.0188,49.0,3.6567,0.5735,0.3240,12.8333,6.0,4.3333,515.8089,...,0.998503,0.001030,0.000464,0.095241,0.071448,0.083333,0.250000,6.255750,0.166667,0.336167
6t4k_pocket10,-0.0422,0.0012,38.0,3.6787,0.6109,0.2755,11.7500,6.0,3.7500,288.8607,...,0.994015,0.005135,0.000782,0.035083,0.214926,0.000000,0.375000,6.328375,0.264750,0.381500
6t4k_pocket5,0.1913,0.0119,63.0,3.5531,0.5207,0.1777,33.6111,8.0,4.7778,485.4208,...,0.964001,0.030956,0.005088,0.328526,0.171460,0.153127,0.291315,6.339389,0.645389,0.450667
6t4k_pocket8,0.0946,0.0053,52.0,3.4860,0.4960,0.1498,29.1111,4.0,4.1111,354.1554,...,0.982483,0.014218,0.003329,0.407597,0.481250,0.130528,0.869425,6.372556,0.941444,1.068333
6t4k_pocket3,0.3352,0.0126,48.0,3.2805,0.3951,0.2059,50.5000,5.0,4.2500,188.6404,...,0.996113,0.002252,0.001639,0.250000,0.000000,0.083333,0.500000,6.228417,0.251833,0.593500
6t4k_pocket6,0.1324,0.0020,61.0,3.5795,0.5048,0.2302,6.9167,8.0,4.2500,598.8709,...,0.981677,0.011481,0.006781,0.110790,0.305895,0.232276,0.517714,6.216500,0.439500,0.787667

In [24]:
preds = model.predict_proba(data)[[1]].sort_values(1, ascending=False)
preds

                      1
6t4k_pocket2   0.849338
6t4k_pocket1   0.602851
6t4k_pocket5   0.002789
6t4k_pocket7   0.000516
6t4k_pocket9   0.000358
6t4k_pocket4   0.000327
6t4k_pocket3   0.000320
6t4k_pocket6   0.000168
6t4k_pocket10  0.000143
6t4k_pocket8   0.000135

### View

In [25]:
v = view_pockets(
    clean_pdb,
    pockets={"pocket2": {"color": "green"}, "pocket1": {"color": "blue"}}, # {"pocketn": {"color": ""}}
    site_residues=site.residues,
    modulator_residues=site.modulator_residues,
)
v

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

### Optional: view allosteric network pathways

**View the allosteric pathways originating from the predicted pocket towards spatially distant residues in the structure.**

The allosteric network can be chosen between [correlationplus](https://github.com/tekpinar/correlationplus) (Dynamical Cross-Correlation from Elastic Network Models) or ProDy's [Perturbation Response Scanning](http://www.bahargroup.org/prody/prs/). The shortest paths between residues of the source pocket and other spatially distant residues (given a distance threshold) are calculated using [NetworkX](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.weighted.multi_source_dijkstra.html) with Dijkstra’s algorithm.

In [26]:
paths, G = get_pathways(
    clean_pdb,
    pathways="correlationplus", # or 'prs'
    source_pocket="pocket2",
    pathway_dist_threshold=20,
    top_pathways=10
)

2025-07-16 17:36:30,770 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-07-16 17:36:30,774 - .prody - WARNING - WARNING No anisotropic B factors found
2025-07-16 17:36:30,774 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.03s.
2025-07-16 17:36:30,842 - .prody - DEBUG - Hessian was built in 0.06s.
2025-07-16 17:36:32,658 - .prody - DEBUG - 100 modes were calculated in 1.82s.

In [27]:
# The pathway number and rank is stored in 'label_asym_id',
# the order of the residues in the pathway in 'label_seq_id', 
# and the path length (lower "better") in 'occupancy'
paths.set_index(
    ["label_asym_id", "occupancy", "label_seq_id"]
)[
    ["auth_asym_id", "auth_comp_id", "auth_seq_id", 'pdbx_PDB_ins_code']
]

                                     auth_asym_id auth_comp_id auth_seq_id  \
label_asym_id occupancy label_seq_id
P104_top1     0.889891  1                       A          MET         358
                        2                       A          VAL         361
                        3                       A          ARG         364
                        4                       A          MET         365
                        5                       A          TYR         369
                        6                       A          ASN         370
                        7                       A          ALA         371
P143_top2     0.898231  1                       A          MET         358
                        2                       A          VAL         361
                        3                       A          VAL         363
                        4                       A          LEU         407
                        5                       A          LEU         410
P144_top3     0.901008  1                       A          MET         358
                        2                       A          VAL         361
                        3                       A          ARG         364
                        4                       A          CYS         366
                        5                       A          SER         408
                        6                       A          HIS         411
P146_top4     0.901257  1                       A          MET         358
                        2                       A          VAL         360
                        3                       A          SER         413
                        4                       A          ILE         417
                        5                       A          THR         421
P182_top5     1.059482  1                       A          LYS         354
                        2                       A          ALA         449
P106_top6     1.106634  1                       A          MET         358
                        2                       A          VAL         361
                        3                       A          ARG         364
                        4                       A          MET         365
                        5                       A          TYR         369
                        6                       A          ASN         370
                        7                       A          ASN         373
P184_top7     1.107651  1                       A          MET         358
                        2                       A          VAL         360
                        3                       A          LEU         419
                        4                       A          THR         421
                        5                       A          PHE         450
                        6                       A          HIS         451
P26_top8      1.126594  1                       A          LEU         293
                        2                       A          MET         358
                        3                       A          VAL         361
                        4                       A          ARG         364
                        5                       A          MET         365
                        6                       A          ALA         368
P181_top9     1.171904  1                       A          LYS         354
                        2                       A          LEU         448
                        3                       A          ALA         449
P29_top10     1.203302  1                       A          ARG         296
                        2                       A          MET         358
                        3                       A          VAL         361
                        4                       A          ARG         364
                        5                       A          MET         365
                        6                       A          TYR         369
                        7                       A          ASN         370

                                     pdbx_PDB_ins_code
label_asym_id occupancy label_seq_id
P104_top1     0.889891  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
                        6                            ?
                        7                            ?
P143_top2     0.898231  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
P144_top3     0.901008  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
                        6                            ?
P146_top4     0.901257  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
P182_top5     1.059482  1                            ?
                        2                            ?
P106_top6     1.106634  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
                        6                            ?
                        7                            ?
P184_top7     1.107651  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
                        6                            ?
P26_top8      1.126594  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
                        6                            ?
P181_top9     1.171904  1                            ?
                        2                            ?
                        3                            ?
P29_top10     1.203302  1                            ?
                        2                            ?
                        3                            ?
                        4                            ?
                        5                            ?
                        6                            ?
                        7                            ?

In [28]:
# The function also returns the NetworkX Graph, storing in each edge the crosscorrelation 'value' calculated by correlationplus (higher is "more important"), and its transformation to a distance (shorter/lower is "more important")
G.edges(data=True)

EdgeDataView([(0, 1, {'value': 0.2503965031864735, 'distance': 1.3847096017702873}), (0, 2, {'value': 0.15535782691534972, 'distance': 1.8620242565142662}), (0, 3, {'value': 0.15544896654486615, 'distance': 1.8614377852178858}), (0, 4, {'value': 0.1273717805890785, 'distance': 2.0606450559688443}), (0, 5, {'value': 0.13196866543035582, 'distance': 2.0251907611014035}), (0, 6, {'value': 0.12733149165663377, 'distance': 2.060961415724329}), (0, 7, {'value': 0.11387590522732688, 'distance': 2.1726459663451894}), (0, 8, {'value': 0.1489624966617311, 'distance': 1.904060699262243}), (0, 9, {'value': 0.09776956382145939, 'distance': 2.325141949518143}), (0, 10, {'value': -0.011292062693835295, 'distance': 4.483655128990853}), (0, 11, {'value': -0.022503339841244533, 'distance': 3.7940914999610085}), (0, 12, {'value': -0.01559452086515476, 'distance': 4.160835589888711}), (0, 13, {'value': -0.05212622847877872, 'distance': 2.95408701301849}), (0, 14, {'value': -0.10283810842985885, 'distance': 2.2745992813604023}), (0, 15, {'value': -0.08610799740539499, 'distance': 2.4521529761685996}), (0, 16, {'value': -0.052840025708513184, 'distance': 2.9404862948680117}), (0, 17, {'value': -0.10728666941534233, 'distance': 2.2322508653191573}), (0, 18, {'value': -0.13241507721149054, 'distance': 2.0218137591909064}), (0, 19, {'value': -0.13296911362924893, 'distance': 2.0176383995605307}), (0, 20, {'value': -0.12979344706897655, 'distance': 2.041810954112689}), (0, 21, {'value': -0.10917805080645865, 'distance': 2.2147752276560326}), (0, 22, {'value': -0.10120582858443664, 'distance': 2.290598920198558}), (0, 23, {'value': -0.06814424711388711, 'distance': 2.686128525784676}), (0, 24, {'value': -0.061398893907269346, 'distance': 2.790363443243953}), (0, 25, {'value': -0.07069622888950697, 'distance': 2.649363033968126}), (0, 26, {'value': -0.10934703101101162, 'distance': 2.2132286753309454}), (0, 27, {'value': -0.05560957046774303, 'distance': 2.8893999448410734}), (0, 28, {'value': -0.05397094033278484, 'distance': 2.9193095017252064}), (0, 29, {'value': -0.07776024392014824, 'distance': 2.554124970141649}), (0, 30, {'value': -0.04454017337068749, 'distance': 3.1113637032371955}), (0, 31, {'value': -0.03600279007575704, 'distance': 3.324158814649173}), (0, 32, {'value': -0.023139395010244104, 'distance': 3.7662186601024565}), (0, 33, {'value': -0.003542011165675971, 'distance': 5.643060305936267}), (0, 34, {'value': 0.005368156032647634, 'distance': 5.22727062726678}), (0, 35, {'value': 0.021898571255797326, 'distance': 3.8213338390840987}), (0, 36, {'value': 0.021118318798853397, 'distance': 3.857614379287274}), (0, 37, {'value': 0.020192249947859318, 'distance': 3.902456365617197}), (0, 38, {'value': 0.02903800924407062, 'distance': 3.5391496101391544}), (0, 39, {'value': 0.042243342556909, 'distance': 3.164308487539993}), (0, 40, {'value': 0.03970184554600504, 'distance': 3.226357580876835}), (0, 41, {'value': 0.044226055962291275, 'distance': 3.118441140565775}), (0, 42, {'value': 0.06291274214390354, 'distance': 2.766006543092316}), (0, 43, {'value': 0.053430130981161006, 'distance': 2.9293804238459216}), (0, 44, {'value': 0.05066563104107591, 'distance': 2.982507468254389}), (0, 45, {'value': 0.05703890453086189, 'distance': 2.864021691808047}), (0, 46, {'value': 0.07514045395215704, 'distance': 2.58839618512804}), (0, 47, {'value': 0.056641045493270675, 'distance': 2.871021354544357}), (0, 48, {'value': 0.05029928047290767, 'distance': 2.989764487811322}), (0, 49, {'value': 0.06312361984986124, 'distance': 2.7626602405482727}), (0, 50, {'value': 0.07074751777467671, 'distance': 2.6486378143963587}), (0, 51, {'value': 0.04840270855734112, 'distance': 3.0281994852368253}), (0, 52, {'value': 0.01708454494790553, 'distance': 4.0695809708344335}), (0, 53, {'value': 0.02718455279192632, 'distance': 3.6051063432792576}), (0, 54, {'value': 0.021603651496939557, 'distance': 3.8348928825067823}), (0, 55, {'value': -0.0020963192829117627, 'distance': 6.16757171846439}), (0, 56, {'value': -0.027651963635808244, 'distance': 3.5880585008017065}), (0, 57, {'value': -0.04534374317009145, 'distance': 3.093483058469065}), (0, 58, {'value': -0.056809779383898175, 'distance': 2.868046779220641}), (0, 59, {'value': -0.07679949770102466, 'distance': 2.5665571671802216}), (0, 60, {'value': -0.10046222292165861, 'distance': 2.29797350452065}), (0, 61, {'value': -0.10670125829542502, 'distance': 2.2377223195376548}), (0, 62, {'value': -0.11448767393995156, 'distance': 2.1672881052275446}), (0, 63, {'value': -0.12269029194515876, 'distance': 2.098092043496194}), (0, 64, {'value': -0.13890080930848786, 'distance': 1.973995196484443}), (0, 65, {'value': -0.1485353443435383, 'distance': 1.9069323342792424}), (0, 66, {'value': -0.13314326976471266, 'distance': 2.0163295077547656}), (0, 67, {'value': -0.1309408390883592, 'distance': 2.033009661162988}), (0, 68, {'value': -0.15214804953373823, 'distance': 1.882901216512972}), (0, 69, {'value': -0.1419930141072146, 'distance': 1.9519774129765266}), (0, 70, {'value': -0.08201354815186096, 'distance': 2.500870812808165}), (0, 71, {'value': -0.07665757675809819, 'distance': 2.5684068177361024}), (0, 72, {'value': -0.028041712359831113, 'distance': 3.574062115551605}), (0, 73, {'value': -0.07136003610184755, 'distance': 2.6400172717855246}), (0, 74, {'value': -0.13347483358249035, 'distance': 2.013842324911206}), (0, 75, {'value': -0.11889306771805973, 'distance': 2.129530773038789}), (0, 76, {'value': -0.057891338999829435, 'distance': 2.8491874748136463}), (0, 77, {'value': -0.1239744484509279, 'distance': 2.087679788423996}), (0, 78, {'value': -0.09878406292478806, 'distance': 2.3148189845457767}), (0, 79, {'value': -0.11523454142388502, 'distance': 2.160785729236045}), (0, 80, {'value': -0.10168651389370373, 'distance': 2.285860582634772}), (0, 81, {'value': -0.1301317026694554, 'distance': 2.039208237221572}), (0, 82, {'value': -0.15553879258188352, 'distance': 1.8608601030660867}), (0, 83, {'value': -0.1294772565305081, 'distance': 2.044250031790142}), (0, 84, {'value': -0.12552457352675064, 'distance': 2.075253727616998}), (0, 85, {'value': -0.1480706818586052, 'distance': 1.9100655333438719}), (0, 86, {'value': -0.1465811268687989, 'distance': 1.9201762309527117}), (0, 87, {'value': -0.12120373034328627, 'distance': 2.1102824201600447}), (0, 88, {'value': -0.10947505344794663, 'distance': 2.2120585699397255}), (0, 89, {'value': -0.1330427439677509, 'distance': 2.0170848126603533}), (0, 90, {'value': -0.1354505957060143, 'distance': 1.9991483061007194}), (0, 91, {'value': -0.10082483861377176, 'distance': 2.294370529962659}), (0, 92, {'value': -0.10866509517784215, 'distance': 2.2194846397391212}), (0, 93, {'value': -0.13686199823840212, 'distance': 1.9887821666556524}), (0, 94, {'value': -0.12193554587479503, 'distance': 2.104262679155729}), (0, 95, {'value': -0.10224449195144114, 'distance': 2.2803883451752682}), (0, 96, {'value': -0.14322360562224032, 'distance': 1.943348188328009}), (0, 97, {'value': -0.1469453196923468, 'distance': 1.91769473047996}), (0, 98, {'value': -0.12618661823477015, 'distance': 2.0699933637470496}), (0, 99, {'value': -0.13768959751906737, 'distance': 1.9827534143622854}), (0, 100, {'value': -0.14855175956083397, 'distance': 1.9068218265056895}), (0, 101, {'value': -0.13021348615723258, 'distance': 2.038579967575356}), (0, 102, {'value': -0.10917879591982121, 'distance': 2.2147684029251673}), (0, 103, {'value': -0.10641556147694506, 'distance': 2.2404034498890493}), (0, 104, {'value': -0.07415207811251961, 'distance': 2.601637172512535}), (0, 105, {'value': -0.03839978165040403, 'distance': 3.2597034805502028}), (0, 106, {'value': -0.03590534422475677, 'distance': 3.3268691035167195}), (0, 107, {'value': -0.04031309253081371, 'distance': 3.2110789622895406}), (0, 108, {'value': -0.04287640260878627, 'distance': 3.1494336378007177}), (0, 109, {'value': -0.06619697352572271, 'distance': 2.7151205201119017}), (0, 110, {'value': -0.0826283785579514, 'distance': 2.4934020802812418}), (0, 111, {'value': -0.04496245797981841, 'distance': 3.1019273832806684}), (0, 112, {'value': -0.03276424827729798, 'distance': 3.4184173200895644}), (0, 113, {'value': -0.04921370735625194, 'distance': 3.011583070165575}), (0, 114, {'value': -0.04664728082276277, 'distance': 3.0651406218512913}), (0, 115, {'value': -0.04764607653558189, 'distance': 3.0439549715161793}), (0, 116, {'value': -0.0070183332587103004, 'distance': 4.95922937518498}), (0, 117, {'value': 0.013698129057341179, 'distance': 4.2904959486288385}), (0, 118, {'value': 0.03252308186784924, 'distance': 3.4258052006613258}), (0, 119, {'value': 0.07956394836062297, 'distance': 2.5311941872004504}), (0, 120, {'value': 0.06591574969847679, 'distance': 2.7193778579502057}), (0, 121, {'value': 0.08449961239854954, 'distance': 2.471008320794569}), (0, 122, {'value': 0.1097034976139284, 'distance': 2.2099740206486307}), (0, 123, {'value': 0.0881276946194804, 'distance': 2.4289684307276773}), (0, 124, {'value': 0.11452056903582684, 'distance': 2.1670008221552255}), (0, 125, {'value': 0.12316110955753352, 'distance': 2.094261939773138}), (0, 126, {'value': 0.07677672649041513, 'distance': 2.5668537132191642}), (0, 127, {'value': 0.08226084504074496, 'distance': 2.4978600322735347}), (0, 128, {'value': 0.040420807740114334, 'distance': 3.2084105597923216}), (0, 129, {'value': 0.03887691327321693, 'distance': 3.247354668940298}), (0, 130, {'value': 0.051880025598770974, 'distance': 2.9588214078360497}), (0, 131, {'value': 0.021899067503290837, 'distance': 3.821311178160591}), (0, 132, {'value': 0.013718438511365321, 'distance': 4.289014402391761}), (0, 133, {'value': -0.018501082473088164, 'distance': 3.989925983499912}), (0, 134, {'value': -0.028091532472844426, 'distance': 3.572287048941146}), (0, 135, {'value': -0.03780571259685214, 'distance': 3.2752950354232357}), (0, 136, {'value': -0.06693053897479831, 'distance': 2.7040999151477854}), (0, 137, {'value': -0.09093804344266473, 'distance': 2.3975768356358724}), (0, 138, {'value': -0.07904343688082882, 'distance': 2.5377577320325946}), (0, 139, {'value': -0.08972116330476582, 'distance': 2.4110485933215333}), (0, 140, {'value': -0.12879406260754364, 'distance': 2.049540557377604}), (0, 141, {'value': -0.12491871135119842, 'distance': 2.0800920554077815}), (0, 142, {'value': -0.06872040828881572, 'distance': 2.6777090464330744}), (0, 143, {'value': -0.10399144208351463, 'distance': 2.2634466622689167}), (0, 144, {'value': -0.1345447757735155, 'distance': 2.0058582235291764}), (0, 145, {'value': -0.1576059942499319, 'distance': 1.847657062355932}), (0, 146, {'value': -0.13397013248857909, 'distance': 2.010138389287237}), (0, 147, {'value': -0.13794696160903736, 'distance': 1.9808859976182394}), (0, 148, {'value': -0.07348023939625002, 'distance': 2.610738748053057}), (0, 149, {'value': -0.10726203221885966, 'distance': 2.232480530622873}), (0, 150, {'value': -0.1553425513160048, 'distance': 1.8621225866118725}), (0, 151, {'value': -0.11095395618243437, 'distance': 2.198639964881435}), (0, 152, {'value': -0.08881975752359496, 'distance': 2.4211461488384387}), (0, 153, {'value': -0.14915889361006177, 'distance': 1.9027431354655244}), (0, 154, {'value': -0.16492160453033755, 'distance': 1.8022850369838301}), (0, 155, {'value': -0.13832987520405918, 'distance': 1.978114040027794}), (0, 156, {'value': -0.14009063948941722, 'distance': 1.9654656347992907}), (0, 157, {'value': -0.15428382335028595, 'distance': 1.8689613585756917}), (0, 158, {'value': -0.15627892974998847, 'distance': 1.8561128517051046}), (0, 159, {'value': -0.14019967972152975, 'distance': 1.9646875826914463}), (0, 160, {'value': -0.10238565899611739, 'distance': 2.2790086162835363}), (0, 161, {'value': -0.09596563835473722, 'distance': 2.3437650759723194}), (0, 162, {'value': -0.06645572741719598, 'distance': 2.71121929210961}), (0, 163, {'value': -0.08732595765767033, 'distance': 2.438107511305751}), (0, 164, {'value': -0.041861134565709474, 'distance': 3.1733974356277543}), (0, 165, {'value': -0.04045945574789602, 'distance': 3.2074548752260053}), (0, 166, {'value': -0.07875320937943907, 'distance': 2.5414362363842993}), (0, 167, {'value': -0.05536354531237506, 'distance': 2.8938339116135987}), (0, 168, {'value': -0.06129480944239598, 'distance': 2.7920600989859117}), (0, 169, {'value': -0.056971609827443315, 'distance': 2.8652021918773936}), (0, 170, {'value': -0.0414778115876877, 'distance': 3.1825966321557666}), (0, 171, {'value': -0.09045564849677487, 'distance': 2.4028956102044177}), (0, 172, {'value': -0.11135758966234247, 'distance': 2.195008719205309}), (0, 173, {'value': -0.06429826509160831, 'distance': 2.7442226150180398}), (0, 174, {'value': -0.02662678940213856, 'distance': 3.6258374130626576}), (0, 175, {'value': -0.057905330086906494, 'distance': 2.848945825601906}), (0, 176, {'value': -0.058243919786611136, 'distance': 2.8431155571609965}), (0, 177, {'value': -0.02818023051653422, 'distance': 3.569134557912483}), (0, 178, {'value': 0.030138466437139286, 'distance': 3.5019529362139807}), (0, 179, {'value': -0.0009181511196607893, 'distance': 6.993147474380295}), (0, 180, {'value': -0.005215409681524643, 'distance': 5.25613744457736}), (0, 181, {'value': 0.09351908764307758, 'distance': 2.369589707914165}), (0, 182, {'value': 0.08780290847130677, 'distance': 2.432660642403691}), (0, 183, {'value': -0.010830317101262754, 'distance': 4.525405847169499}), (0, 184, {'value': -0.008664690840146991, 'distance': 4.748498921192271}), (0, 185, {'value': 0.08315670857476261, 'distance': 2.4870283851781823}), (0, 186, {'value': 0.061927830938519904, 'distance': 2.7817855739039747}), (0, 187, {'value': -0.028783562847837847, 'distance': 3.5479507554791643}), (0, 188, {'value': -0.023625665445793483, 'distance': 3.7454215976544507}), (0, 189, {'value': 0.06386082110593552, 'distance': 2.751049219212196}), (0, 190, {'value': -0.019598471554906006, 'distance': 3.9323036476545763}), (0, 191, {'value': -0.0250474789827129, 'distance': 3.6869820570042307}), (0, 192, {'value': -0.05196092269197746, 'distance': 2.9572633113558866}), (0, 193, {'value': -0.05022620129695058, 'distance': 2.9912184313506187}), (0, 194, {'value': -0.04517110557564246, 'distance': 3.0972976325939454}), (0, 195, {'value': -0.0695154817806697, 'distance': 2.6662057783992084}), (0, 196, {'value': -0.08849688454884234, 'distance': 2.4247879201259943}), (0, 197, {'value': -0.044509064187876944, 'distance': 3.11206239946931}), (0, 198, {'value': -0.05070008297121063, 'distance': 2.981827713149475}), (0, 199, {'value': -0.11336561483366349, 'distance': 2.1771371460096947}), (0, 200, {'value': -0.09865619173012423, 'distance': 2.3161142747232564}), (0, 201, {'value': -0.04154058591975716, 'distance': 3.1810843326075724}), (0, 202, {'value': -0.04661531199014329, 'distance': 3.0658261878906177}), (0, 203, {'value': -0.03601502662220652, 'distance': 3.3238189946771586}), (0, 204, {'value': -0.049146923498668844, 'distance': 3.0129410091276805}), (0, 205, {'value': -0.07974769716441348, 'distance': 2.5288874018758825}), (0, 206, {'value': -0.06688929131488007, 'distance': 2.7047163807421413}), (0, 207, {'value': -0.020956454203040622, 'distance': 3.865308556824369}), (0, 208, {'value': -0.01930096449134215, 'distance': 3.947600159864386}), (0, 209, {'value': -0.04009878504122883, 'distance': 3.2164092194139227}), (0, 210, {'value': 0.03172717734877335, 'distance': 3.4505816052630007}), (0, 211, {'value': 0.021345209657614276, 'distance': 3.8469278906424496}), (0, 212, {'value': 0.012517104419399717, 'distance': 4.380659137573792}), (0, 213, {'value': 0.04961236119002015, 'distance': 3.003515239603792}), (0, 214, {'value': 0.07020049894825053, 'distance': 2.6563998472057806}), (0, 215, {'value': 0.059349202659514794, 'distance': 2.824316576716313}), (0, 216, {'value': 0.05302332824303317, 'distance': 2.9370232888814938}), (0, 217, {'value': 0.055973030363468325, 'distance': 2.882885288040434}), (0, 218, {'value': 0.08419008735812009, 'distance': 2.4746780811246216}), (0, 219, {'value': 0.05672884697210126, 'distance': 2.86947241605766}), (0, 220, {'value': 0.044472045140230766, 'distance': 3.112894464819572}), (0, 221, {'value': 0.055180134584829114, 'distance': 2.8971522540588444}), (0, 222, {'value': 0.05214313173876475, 'distance': 2.953762790067959}), (0, 223, {'value': 0.05195899074304793, 'distance': 2.957300492851304}), (0, 224, {'value': 0.029336559503971738, 'distance': 3.5289207430426317}), (0, 225, {'value': -0.001538743834328906, 'distance': 6.476788238528009}), (0, 226, {'value': -0.029730253788949387, 'distance': 3.5155900729130116}), (0, 227, {'value': -0.028022936703431305, 'distance': 3.574731901477162}), (0, 228, {'value': -0.0663942777790631, 'distance': 2.7121443901779076}), (0, 229, {'value': -0.09875262335998441, 'distance': 2.3151373007567257}), (0, 230, {'value': -0.10882278191433922, 'distance': 2.2180345656955827}), (0, 231, {'value': -0.04855848707755038, 'distance': 3.0249862688566576}), (0, 232, {'value': -0.04498617877265895, 'distance': 3.1013999535447785}), (0, 233, {'value': -0.09240576155860172, 'distance': 2.381565937926304}), (0, 234, {'value': -0.06455118017059748, 'distance': 2.740296864319373}), (0, 235, {'value': -0.025548390646118285, 'distance': 3.667180914585112}), (0, 236, {'value': -0.038228919027266474, 'distance': 3.2641629820250078}), (0, 237, {'value': -0.020310721893317448, 'distance': 3.896606312048495}), (0, 238, {'value': -0.0035516469120537584, 'distance': 5.6403435836240465}), (0, 239, {'value': 0.0010490580327329744, 'distance': 6.859861676905445}), (1, 2, {'value': 0.19851727943620914, 'distance': 1.6168791285497142}), (1, 3, {'value': 0.19785904338711233, 'distance': 1.620200399841409}), (1, 4, {'value': 0.17653349821372813, 'distance': 1.7342446243730856}), (1, 5, {'value': 0.16027666087395565, 'distance': 1.8308538212718808}), (1, 6, {'value': 0.19138515812837734, 'distance': 1.6534673424837742}), (1, 7, {'value': 0.16182897239892924, 'distance': 1.821215222174081}), (1, 8, {'value': 0.168373746753066, 'distance': 1.7815690825290593}), (1, 9, {'value': 0.11645138652146826, 'distance': 2.150281368553444}), (1, 10, {'value': 0.034416616549725894, 'distance': 3.3692157639367313}), (1, 11, {'value': -0.0027229892483283196, 'distance': 5.90602464752046}), (1, 12, {'value': -0.003782763098124099, 'distance': 5.577300294688485}), (1, 13, {'value': -0.04007573444132719, 'distance': 3.2169842300310245}), (1, 14, {'value': -0.09369569197865425, 'distance': 2.367703057870495}), (1, 15, {'value': -0.07695439603333627, 'distance': 2.5645422798958886}), (1, 16, {'value': -0.05174409974243399, 'distance': 2.9614448496499035}), (1, 17, {'value': -0.10802729952474818, 'distance': 2.2253713021655077}), (1, 18, {'value': -0.1324480302103743, 'distance': 2.02156492877337}), (1, 19, {'value': -0.1325606050869541, 'distance': 2.0207153347035356}), (1, 20, {'value': -0.1255527542477101, 'distance': 2.0750292491975157}), (1, 21, {'value': -0.10405306568266051, 'distance': 2.2628542544133348}), (1, 22, {'value': -0.09887155165587522, 'distance': 2.3139337201822907}), (1, 23, {'value': -0.06743524383357045, 'distance': 2.696587478359709}), (1, 24, {'value': -0.058817250744288944, 'distance': 2.8333200710983255}), (1, 25, {'value': -0.07124175194818629, 'distance': 2.641676215628336}), (1, 26, {'value': -0.11076569883185017, 'distance': 2.200338121899714}), (1, 27, {'value': -0.054506473809904504, 'distance': 2.9094357815180985}), (1, 28, {'value': -0.0501145530177497, 'distance': 2.9934438147218048}), (1, 29, {'value': -0.0757474527814143, 'distance': 2.580350449604279}), (1, 30, {'value': -0.03997474988342883, 'distance': 3.219507253090697}), (1, 31, {'value': -0.028993971524917606, 'distance': 3.5406673155665724}), (1, 32, {'value': -0.015592680116871468, 'distance': 4.160953634991151}), (1, 33, {'value': 0.0063048817902123105, 'dis

In [29]:
view_pockets_pathways(
    clean_pdb, 
    pathways="correlationplus", # or 'prs'
    source_pocket="pocket2", # Source pocket to calculate paths to/from
    pathway_dist_threshold=20, # Minimum distance between residues to calculate paths from
    n_top_pathways=10, # Number of pathways to view in the structure
    pockets={"pocket2": {"color": "green"}}, # {"pocketn": {"color": ""}} # Same dictionary of pockets as above to visualize pockets alongside paths
    site_residues=site.residues,
    modulator_residues=site.modulator_residues,
)

2025-07-16 17:36:33,300 - .prody - WARNING - WARNING Could not find _atom_site_anisotrop in lines.
2025-07-16 17:36:33,301 - .prody - WARNING - WARNING No anisotropic B factors found
2025-07-16 17:36:33,301 - .prody - DEBUG - 1974 atoms and 1 coordinate set(s) were parsed in 0.03s.

Pathway #1 (blue): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ALA:371
Pathway #2 (cyan): A:MET:358, A:VAL:361, A:VAL:363, A:LEU:407, A:LEU:410
Pathway #3 (green): A:MET:358, A:VAL:361, A:ARG:364, A:CYS:366, A:SER:408, A:HIS:411
Pathway #4 (yellow): A:MET:358, A:VAL:360, A:SER:413, A:ILE:417, A:THR:421
Pathway #5 (red): A:LYS:354, A:ALA:449
Pathway #6 (purple): A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370, A:ASN:373
Pathway #7 (grey): A:MET:358, A:VAL:360, A:LEU:419, A:THR:421, A:PHE:450, A:HIS:451
Pathway #8 (light blue): A:LEU:293, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:ALA:368
Pathway #9 (light cyan): A:LYS:354, A:LEU:448, A:ALA:449
Pathway #10 (mint green): A:ARG:296, A:MET:358, A:VAL:361, A:ARG:364, A:MET:365, A:TYR:369, A:ASN:370

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…